OpenConext/OpenConext-engineblock

- library/EngineBlock/Application/Bootstrapper.php
This is to proactively defend against local and remote file inclusion attacks.
This is in most cases already disabled by default in system libraries, but to
be safe we explicitly disable it also.
> Disable the loading of external entities in XML documents.

- application/configs/application.ini
Currently the config has a typo in the technical contact email which causes an exception
> Fix typo in technical contact

- database/patch/patch-0022.sql
- library/EngineBlock/Corto/Model/Consent.php
- library/EngineBlock/Corto/Module/Service/ProcessConsent.php
- library/EngineBlock/Corto/Module/Service/ProvideConsent.php
- src/OpenConext/EngineBlock/ApiBundle/Dto/Consent.php
- src/OpenConext/EngineBlock/Authentication/Entity/Consent.php
- src/OpenConext/EngineBlock/Authentication/Repository/ConsentRepository.php
- src/OpenConext/EngineBlock/Authentication/Tests/Value/ConsentTypeTest.php
- src/OpenConext/EngineBlock/Authentication/Value/ConsentType.php
- tests/phpunit.xml
To determine what type of consent a user has given for a certain service, this should be stored. 
This way, it is possible to inform the user about whether he has implicitly or explicitly consented to releasing his data to a specific service.
Part of: Profile [ticket #106401530](https://www.pivotaltracker.com/story/show/106401530)
> Keep track of consent type given

- composer.lock
In commit a93db11f (updates saml2 dependency), the saml2 package and its dependencies were updated without regard to the required php version.
This commit reverts that mismatch and updates saml2 and its dependencies to match the php 5.3 version requirement.
Fixes issue #245.
> Reverts mismatch of dependencies and php 5.3

- composer.json
- composer.lock
As Engineblock uses parts of EngineBlockFixtures in non-test code,
it should not be a development-only dependency and it should be
shipped on release.
This dependency should be fixed in the future; production code
typically should not depend on EngineBlockFixtures.
> Fix engineblock fixtures dependency

- ldap/schemas/collab.ldif
- ldap/schemas/eduperson-200412.ldif
- ldap/schemas/nleduperson.ldif
OpenLDAP can't handle .schema files. These files are generated by slapd based on the schema files.
> Add OpenLDAP ldif schema files

- database/patch/patch-0010.php
- docs/example.engineblock.ini
- library/EngineBlock/Application/DiContainer.php
Zend_Ldap breaks on some implementations if ldap port is missing.
> Fix missing port breakage in LDAP library

- composer.json
This allows to build the correct configuration on all local envs
so that the application is in a bootable state based on the
correct configuration without having to ship the configuration in
a tarball.
can be invoked with `./bin/composer.phar prepare-env`
> Add prepare-env composer command

- app/config/routing_dev.yml
- app/config/routing_test.yml
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Bindings.feature
The mock IdP route was defined in such a way that
it matched with the metadata route of engineblock itself.
By changing the defition order (first defined is first tried
for match) as well as prefixing the Functional Test URLs this
conflict is resolved.
> Prefix functional testing routes to prevent matching conflicts

- app/Resources/views/layouts/scripts/default.phtml
- theme/material/templates/layouts/scripts/default.phtml
As reported:
> Sending a POST request to several EB URLs with a crafted `sp-entity-id`
or `lang` parameter allows for cross site scripting via the resulting
language switch.
>
> Examples:
POST `/authentication/idp/metadata/key:20140505`  with parameters
`[sp-entity-id=509" src="http://www.example.com/exploit509.js]`.
> POST `/authentication/idp/` with parameters `[lang=509"
src="http://www.example.com/exploit509.js]`
Credits to Nessus for identifying the issue.
Issue was caused by incorrectly escaping variables.
> Closes an XSS vulnerability in the locale switcher

- README.md
Even when not using LDAP, current code still needs PHP LDAP module present, in order to pass a check for this module.
> Document that PHP LDAP module is not optional.

- library/EngineBlock/Application/Bootstrapper.php
We want to control this per application in the webserver, which seems a more appropriate place to handle this kind of configuration. Its settings are not easily changed when it's hardcoded.
> Remove hardcoded Strict-Transport-Security header.

- bin/composer/dump-required-ini-params.sh
This corrects the oversight when fixing the issue in #331, as reported by @tvdijen in the same PR.
> Correct dumping trusted proxy ips configuration

- docs/example.engineblock.ini
Without any value for the base_domain setting, the 'domain' parameter in app/config/ini_parameters.yml will render to 'null' when running bin/composer.phar
More info can be found in #342
> Fix missing (mandatory) setting

- library/EngineBlock/Application/Bootstrapper.php
I ran into a nasty error when I left out the phpsettings from engineblock.ini (since they were already the default in my php.ini)
PHP Fatal error:  Call to a member function toArray() on null in /apps/OpenConext/engineblock/OpenConext-engineblock-5.1.0/library/EngineBlock/Application/Bootstrapper.php on line 139
> Fix for when phpsettings are missing in engineblock.ini

- application/configs/application.ini
- docs/example.engineblock.ini
The example engineblock.ini file contains database-configuration the old style.
When using this file as an example for a manual install, you run into all kinds of database-related errors (like: hostname cannot be null).
This PR should prevent putting manual installers on the wrong track.
> Add new style database-configuration to docs

- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/ClearErrorMessages.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/EngineBlockContext.php
This adds a functional test verifying that the correct error/feedback page is shown when the session is lost.
[127716565](https://www.pivotaltracker.com/story/show/127716565)
#295
> Test session lost feedback page

- library/EngineBlock/User.php
- src/OpenConext/EngineBlock/Authentication/Value/CollabPersonId.php
- src/OpenConext/EngineBlockBridge/Authentication/Repository/UserDirectoryAdapter.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/AttributeManipulation.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/AttributeManipulationWithAllManipulationsBeforeConsent.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/ClearErrorMessages.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockIdpContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/LdapCompatibility.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/FakeUserDirectory.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/MockIdentityProvider.php
- tests/unit/OpenConext/EngineBlock/Authentication/Value/CollabPersonIdTest.php
- tests/unit/OpenConext/EngineBlockBridge/Authentication/Repository/UserDirectoryAdapterTest.php
- tests/unit/OpenConext/EngineBlockBundle/Doctrine/Type/CollabPersonIdTypeTest.php
[134915765](https://www.pivotaltracker.com/story/show/134915765)
In the past, at-signs were replaced by underscores because LDAP had trouble dealing with them. Recently, the way collabPersonIds are generated has changed, breaking compatibility with earlier versions of EB across the platform. In order to reinstate this, a method has been added to reinstate compatibility with all the collabPersonIds present in the platform already.
I have deliberately chosen to create another method for this to be explicit about the quirky implementation of collabPersonIds.
In the future, a way of migrating from old to new collabPersonIds should be devised. Then, we can use the original `CollabPersonId::generateFrom()` method.
> Replace @-sign in collab person ids for compatibility

- composer.json
- composer.lock
This PR updates the SAML2 dependency in order to have the security fix for signature validation noted here: simplesamlphp/saml2#81
This is meant to be cherry-picked into a backported release as well.
> Update simplesamlphp/saml2 dependency

- .travis.yml
- composer.json
- composer.lock
- library/EngineBlock/Application/DiContainer.php
- library/EngineBlock/Application/FunctionalTestDiContainer.php
- library/EngineBlock/User.php
- src/OpenConext/EngineBlock/Authentication/Value/CollabPersonId.php
- src/OpenConext/EngineBlockBridge/Authentication/Repository/UserDirectoryAdapter.php
- src/OpenConext/EngineBlockBundle/Configuration/FeatureConfiguration.php
- src/OpenConext/EngineBlockBundle/Configuration/FeatureConfigurationInterface.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/EngineBlockContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockIdpContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Encryption.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/LdapCompatibility.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Fixtures/FunctionalTestingFeatureConfiguration.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/FakeUserDirectory.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/MockIdentityProvider.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Resources/config/services.yml
- tests/OpenConext/EngineBlock/Authentication/Value/CollabPersonIdTest.php
- tests/OpenConext/EngineBlockBridge/Authentication/Repository/UserDirectoryAdapterTest.php
- tests/OpenConext/EngineBlockBundle/Doctrine/Type/CollabPersonIdTypeTest.php
[134915765](https://www.pivotaltracker.com/story/show/134915765)
This PR contains backports of a fix for [LDAP/CollabPersonId](https://github.com/OpenConext/OpenConext-engineblock/pull/360) [generation](https://github.com/OpenConext/OpenConext-engineblock/pull/363) and a dependency update for [SAML2 regarding security and EPTIs](https://github.com/OpenConext/OpenConext-engineblock/pull/362).
> Backport LDAP/CollabPersonId fix and SAML2 version number to 5.0.0

- UPGRADING.md
- database/DoctrineMigrations/Version20161209145942.php
- database/DoctrineMigrations/Version20161209152354.php
- library/EngineBlock/Corto/Model/Consent.php
- library/EngineBlock/Corto/Module/Service/ProcessConsent.php
- src/OpenConext/EngineBlock/Authentication/Dto/Consent.php
- src/OpenConext/EngineBlock/Authentication/Model/Consent.php
- src/OpenConext/EngineBlock/Authentication/Repository/ConsentRepository.php
[130002585](https://www.pivotaltracker.com/story/show/130002585)
OpenConext/OpenConext-engineblock#316
This PR prevents consent_date from updating upon each consent and removes the tracking of the last date on which consent has been given. The usage_date column has been removed from the consent table.
This impacts Profile, as a consumer of the Consent API, see: OpenConext/OpenConext-profile#73
> Drop usage date and only update consent once

- application/configs/application.ini
This ini overrides the engineblock.ini written during provisioning.
The previous values were added to use the correct syntax, but used the some default values that conflicted with the default OpenConext-deploy development environment, see https://github.com/OpenConext/OpenConext-engineblock/pull/352 by @tvdijen 
This change is transparent about how it can be configured (and how it is configured in OpenConext-deploy).
> Correct and comment out DB settings in ini

- composer.json
- composer.lock
This reverts the work done by cherry pick: 1602773ee1ac529da96c101aaef968dc6e83c36d.
The PR, backporting the SAML2 bump from master (https://github.com/OpenConext/OpenConext-engineblock/pull/362), related to that fix: https://github.com/OpenConext/OpenConext-engineblock/pull/364
This is reversion is necessary because the SAML2 version bump contains a change in the way AllowCreate is to be set in SAML2: https://github.com/simplesamlphp/saml2/commit/aecda70e72970c8d66af1d18d5b762a8df5731ed.
**Security notice**
This will cause EB 5.0.x to lack an important security update. This should be fixed ASAP.
**Note**
This should also be fixed on master, but the version bump that introduced this change was [already present in 5.1](https://github.com/OpenConext/OpenConext-engineblock/commit/0ce17afbe3fd …
> Revert SAML2 version bump back to 1.7.2 (5.0.x)

- bin/composer/zend-framework-post-install.sh
We are explicitly creating backups in order to be sure this works on every system (or most systems).
Mac's BSD grep requires a file-extension for backups when using `-i`. In our previous script, `-i -e` was creating backups with the extension `.php-e`. 
This PR fixes this by setting an explicit backup extension and then finding and removing files with that extension.
> Remove backups when replacing includes for Zend Framework

- library/EngineBlock/Saml2/AuthnRequestFactory.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/AuthnRequest.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/EngineBlockContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/SingleSignOn.feature
- tests/library/EngineBlock/Test/Corto/ProxyServerTest.php
The SAML2 version bump contains a change in the way AllowCreate is to be set in SAML2: https://github.com/simplesamlphp/saml2/commit/aecda70e72970c8d66af1d18d5b762a8df5731ed.
We were setting this as a string and this caused AllowCreate not to be set anymore, while there are some IdPs out there that require it.
This PR aims to fix that.
In order to properly test this and future requirements regarding AuthnRequests, this PR also introduces infrastructure to be able to query the encoded AuthnRequest XML present in the HTTP response's body.
> Set AllowCreate correctly for SAML2

- library/EngineBlock/Corto/Module/Service/AssertionConsumer.php
- src/OpenConext/EngineBlockBundle/Controller/DebugController.php
- src/OpenConext/EngineBlockBundle/Resources/config/controllers/authentication.yml
This PR solves #380.
Issues were caused by debug requests not registering authentication states correctly.
> Bugfix: debug page causes invalid authentication state

- app/Resources/views/modules/Authentication/View/Proxy/discover.phtml
- library/EngineBlock/Corto/Adapter.php
- library/EngineBlock/Corto/Module/Service/SingleSignOn.php
- library/EngineBlock/Corto/ProxyServer.php
- theme/material/templates/modules/Authentication/View/Proxy/discover.phtml
This has been supplanted by 'selectedidps' (with `s`) introduced in EB 4.5.
However, the old cookie was not removed at that time.
> Remove legacy 'selectedIdp' cookie.

- build.xml
- composer.lock
This PR addresses the following issues:
* (Temporarily) fix security checker for Travis
The SensioLabs security checker has switched to Lets Encrypt, which has broken some things.
Most issues have been fixed, but Travis still needs to offer ssl capabilities to PHP.
See: sensiolabs/security-checker#73, travis-ci/travis-ci#6339, sensiolabs/security-checker#77
* Update simplesamlphp
his regards [SSPSA 201703-01](https://simplesamlphp.org/security/201703-01) and [SSPSA 201703-02](https://simplesamlphp.org/security/201703-02), see https://github.com/simplesamlphp/simplesamlphp/releases/tag/v1.14.12.
> Fix security checker for Travis and update simplesamlphp

- library/EngineBlock/Corto/ProxyServer.php
As per mailinglist-discussion:
protocolBinding is an optional attribute according to the specs;  http://saml2int.org/profile/current/#section82
> No notice on ommiting protocolBinding

- composer.json
- composer.lock
It seems that the openid  library is not in use in the project. It does require a php extension that is not installed on the dev env (php-gmp). By removing the library the extension is no longer required. This solves the first half of https://github.com/OpenConext/OpenConext-deploy/issues/133
> Remove unused vendor library

- database/DoctrineMigrations/Version20161123131704.php
- database/DoctrineMigrations/Version20170331145533.php
It's simple: if it's for some reason already away, the goal has been accomplished, no need to fail.
> Make DROP TABLE migrations more robust to when a table is already gone.

- .travis.yml
This is the change made by arothuis in PR: https://github.com/OpenConext/OpenConext-engineblock/pull/399
The solution was to use array cache in php7 until the current Doctrine version supports php7's memory cache mechanism.
> Use APCu for forward compatibility with PHP 7

- tests/unit/OpenConext/EngineBlockBundle/AttributeAggregation/AttributeAggregationClientTest.php
The test of the AttributerAggregationClient was not yet fixed to include the use of the second paarameter.
This fix should be merged to `master` and the `display-unconnected-idps-wayf` branches.
> AttributerAggregationClient bugfix

- library/EngineBlock/Corto/Adapter.php
- library/EngineBlock/Corto/Module/Bindings.php
- library/EngineBlock/Corto/Module/Service/ContinueToIdp.php
- library/EngineBlock/Corto/Module/Service/SingleSignOn.php
- library/EngineBlock/Corto/ProxyServer.php
- tests/library/EngineBlock/Test/Corto/Module/BindingsTest.php
The two loggers (session and system) have been merged to a single
logger. The three fields have been merged into a new `_logger` field.
All usages in the EngineBlock module have been updated to use the new
logger.
Pivotal tracker: #143228773
> Merged ProxyServer loggers

- application/configs/application.ini
Without them defined at all, you always immediately get the 'stuck-in-authentication-loop' error, without even being redirected to the IdP you picked.
Probably because 0 >= null evaluates to true @ https://github.com/OpenConext/OpenConext-engineblock/blob/master/src/OpenConext/EngineBlockBundle/Authentication/AuthenticationLoopGuard.php#L72
It probably needs a safe default in code as well...
> Uncomment mandatory settings

- library/EngineBlock/Corto/Module/Service/SingleSignOn.php
$application is already defined/initialized on the first line of this function. No need to do it twice
> Remove redeclaration of $application and fix indentation

- library/EngineBlock/Corto/Module/Bindings.php
Just tested this.  Messages will now look like this:
```
Aug  3 11:56:28 vm043 EBLOG[2357]: [2017-08-03 11:56:24] engineblock.NOTICE: IssueInstant of SAML message from IdP "http://172.20.1.240/idp/saml2/idp/metadata.php" is in 179 seconds in the future; might indicate (local or remote) clock synchronization issues {"session_id":"cyhp2mAU,wljvRYRRuoNG-ODI84","request_id":"5982f347862dc"} []
Aug  3 11:57:24 vm043 EBLOG[1144]: [2017-08-03 11:57:23] engineblock.NOTICE: IssueInstant of SAML message from IdP "http://172.20.1.240/idp/saml2/idp/metadata.php" is in 49 seconds in the future; might indicate (local or remote) clock synchronization issues {"session_id":"zvxqV6JSp5OznyuLIbrZpO5oDh0","request_id":"5982f382d3502"} []
```
> Improve warning message for clock sync issues

- application/configs/application.ini
- bin/composer/dump-required-ini-params.sh
- library/EngineBlock/Application/DiContainer.php
- library/EngineBlock/Application/FunctionalTestDiContainer.php
- library/EngineBlock/Corto/Filter/Command/EnforcePolicy.php
- library/EngineBlock/PolicyDecisionPoint/PepValidator.php
- src/OpenConext/EngineBlockBundle/Pdp/Dto/Request.php
- tests/unit/OpenConext/EngineBlockBundle/Pdp/Dto/RequestTest.php
- tests/unit/OpenConext/EngineBlockBundle/Pdp/PdpClientTest.php
- tests/unit/OpenConext/EngineBlockBundle/Pdp/fixture/request.json
StepUp uses PDP for context-based access control, so EngineBlock is no
longer the sole user of PDP. PDP requires a client ID to distinguish
StepUp from EngineBlock.
The client ID must be configured in the ini parameter 'pdp.client_id'.
> Send a client ID to the PDP API endpoint

- library/EngineBlock/Corto/Filter/Command/AttributeAggregator.php
- src/OpenConext/EngineBlockBundle/AttributeAggregation/Dto/Request.php
- tests/unit/OpenConext/EngineBlockBundle/AttributeAggregation/AttributeAggregationClientTest.php
- tests/unit/OpenConext/EngineBlockBundle/AttributeAggregation/Dto/RequestTest.php
The attribute aggregator requires the SP entity ID in the
request. This commit adds the entity ID to the request object as a
user attribute:
{
"userAttributes": [
{
"name": "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified",
"values": [
"urn:collab:person:surfnet.nl:henny"
]
},
{
"name": "SPentityID",
"values": [
"http://localhost/metadata"
]
}
],
"arpAttributes": {}
}
> Add the SP entity ID to the attribute aggregation API

- library/EngineBlock/Corto/Filter/Command/AttributeAggregator.php
- src/OpenConext/EngineBlockBundle/AttributeAggregation/Dto/Request.php
Previous implementation cleared all response attributes before adding
them to the AA request. This was a bug: the attribute aggregator
should receive all attributes in the assertion.
> Send all attributes to the aggregation endpoint

- docs/trusted_proxy.md
I think it's a mistake...
There are no occurrences for 'coin:redirect.sign' anywhere in the EB-code
> Docs: fix name for setting

- composer.json
- composer.lock
Main dependencies affected:
- updates symfony from 2.8.17 to 2.8.31
- updates twig from 1.33.0 to 2.4.4
- updates phpunit from 5.2.11 to 5.6.4
Fixes the following vulnerabilities:
* CVE-2017-16653: CVE-2017-16653: CSRF protection does not use different tokens for HTTP and HTTPS
http://symfony.com/blog/cve-2017-16653-csrf-protection-does-not-use-different-tokens-for-http-and-https
* CVE-2017-16654: CVE-2017-16654: Intl bundle readers breaking out of paths
http://symfony.com/blog/cve-2017-16654-intl-bundle-readers-breaking-out-of-paths
* CVE-2017-16790: CVE-2017-16790: Ensure that submitted data are uploaded files
http://symfony.com/blog/cve-2017-16790-ensure-that-submitted-data-are-uploaded-files
* CVE-2017-16652: CVE-2017-16652: Open redirect vulnerability on security handlers …
> Update symfony to latest security release

- composer.json
- composer.lock
- library/EngineBlock/Arp/AttributeReleasePolicyEnforcer.php
- src/OpenConext/EngineBlockBundle/Controller/Api/AttributeReleasePolicyController.php
This parameter trigger the inclusion of the attribute source. The source is omitted by default, but will be included per attribute when using this parameter.
I've tested this myself using PHPStorm REST Client. But using curl should do just fine. 
**Test info**
Hostname: `https://engine-api.vm.openconext.org`
Endpoint: POST `/arp`
Request body (attributes without sources are sent for each sp)
```
{"showSources":true, "entityIds":["https:\/\/aa.vm.openconext.org\/shibboleth","https:\/\/profile-dev.vm.openconext.org\/app_dev.php\/authentication\/metadata"],"attributes":{"urn:mace:dir:attribute-def:cn":["John Doe"],"urn:oid:2.5.4.3":["John Doe"],"urn:mace:dir:attribute-def:displayName":["John Doe"],"urn:oid:2.16.840.1.113730.3.1.241":["John …
```
> Accept 'showSources' parameter in arp endpoint

- composer.lock
- src/OpenConext/EngineBlockBundle/Controller/Api/AttributeReleasePolicyController.php
- src/OpenConext/EngineBlockBundle/Resources/config/routing_api.yml
The arp configuration of entities can now be read from the EB API using
the /read-arp endpoint. The endpoint expects to be called using POST.
An array of entityIds must be provided to specify what Arp config should
be read.
> Expose the /read-arp endpoint on EB API

- library/EngineBlock/Corto/Module/Service/AssertionConsumer.php
A SAML response can have a signature in the Response, in the Assertion
contained therein, or both. Log all information we have.
> Log sigalg for both Response AND Assertion.

- library/EngineBlock/Corto/Adapter.php
- library/EngineBlock/Corto/Module/Bindings.php
- library/EngineBlock/Corto/Module/Service/SingleSignOn.php
- library/EngineBlock/Corto/ProxyServer.php
The receiveRequest() and receiveResponse() methods on the bindings
module are costly methods that do logging, signature validation and
fetching of metadata. The methods do not cache their results so they
should never be called more than once per request.
Until commit 2ed6926, the receiveRequest() method was called just once
per request, by the Corto SingleSignOn module. Starting from that
commit, the method was called in two places, relying on caching by the
'internal bindings' mechanism to be efficient - which presumably has
never worked as intended for requests. In later commits, two more
invocations of the method were added causing signatures to be
validated four times for a single request.
This commit fixes the issue in three places:
1. The receiveRequest() method on the bindings …
> Do not process authn requests multiple times per request

- composer.json
- composer.lock
The saml-value-object and beberlei assert libraries have been updated
to version 1.3.1 and 2.8.1 respectively.
The saml-value-object required version 2.6 and above of the assert lib,
this was introduced to make use of the isCallable method that was
introduced on the assert library in version 2.6. This allowed the
saml-value-object library to drop the homemade implementation if favor
of beberlei's solution.
In doing so, engineblock-metadata was also bumped one minor release 
to version 2.5.0.
> Update of saml-value-object library

- database/DoctrineMigrations/Version20180118115853.php
- library/EngineBlock/Corto/Module/Bindings.php
- library/EngineBlock/X509/PrivateKey.php
A signature method can be configured per SP and IDP using the
'coin:signature_method' metadata property. If this property is not
set, RSA_SHA1 is used in order to maintain backwards compatibility.
Depends on https://github.com/OpenConext/OpenConext-engineblock-metadata/pull/19 (already merged).
> Create signatures using a configurable signature method

- app/Resources/views/modules/Authentication/View/Feedback/UnsupportedSignatureMethod.phtml
- application/configs/application.ini
- languages/en.php
- languages/nl.php
- library/EngineBlock/Corto/Adapter.php
- library/EngineBlock/Corto/Module/Bindings.php
- library/EngineBlock/Corto/Module/Bindings/UnsupportedSignatureMethodException.php
- library/EngineBlock/Corto/Module/Service/AssertionConsumer.php
- src/OpenConext/EngineBlockBundle/Controller/FeedbackController.php
- src/OpenConext/EngineBlockBundle/EventListener/RedirectToFeedbackPageExceptionListener.php
- src/OpenConext/EngineBlockBundle/Resources/config/routing/feedback.yml
- theme/material/templates/modules/Authentication/View/Feedback/UnsupportedSignatureMethod.phtml
EngineBlock now allows configuring one or more 'forbidden signature
methods'. If an authentication request is signed with such a method,
an error is logged and the generic error page is shown to the user.
Before this commit, the notice 'Received signed AuthnRequest from
Issuer...' was only logged when the signature was contained inside the
SAML message, but not when the signature was sent as a query
parameter. This commit changes this behaviour and logs the used
signature method regardless of how the signature was sent.
> Disallow authn requests signed with forbidden signature methods

- app/Resources/views/modules/Authentication/View/Proxy/consent-slidein-about.phtml
- app/Resources/views/modules/Authentication/View/Proxy/consent.phtml
- application/configs/application.ini
- languages/en.php
- languages/nl.php
- library/EngineBlock/Corto/Module/Service/ProvideConsent.php
- theme/material/templates/modules/Authentication/View/Proxy/consent-slidein-about.phtml
- theme/material/templates/modules/Authentication/View/Proxy/consent.phtml
A new configuration parameter was added to the application.ini. This config is read in the ProvideConsent service and injected into the consent view. The profile url is then fed into the translation helper who in turn sprintf's it into the translation string.
When no application ini is not configured with the profile url, '#' is used as a fallback value, rendering the link useless.
> Make Profile url configurable in application.ini

- library/EngineBlock/Corto/Module/Service/SingleSignOn.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/SpProxy.feature
When dealing with trusted proxies, the incorrect SP name is shown in the
WAYF. The name of the proxy is shown instead of the name of the original
service.
By reading the RequesterId's from the AuthnRequest, we are able to
ascertain the first requester in the chain.
@thijskh is my solution to read the original SP from the requesterId array correct? Or is there a more obvious solution?
> Show correct name of SP in WAYF

- app/Resources/views/layouts/scripts/default.phtml
- app/config/config.yml
- app/config/config_dev.yml
- bin/makeRelease.sh
- src/OpenConext/EngineBlockBundle/Resources/config/compat.yml
- theme/material/templates/layouts/scripts/default.phtml
The makeRelease.sh script replaces a placeholder in config.yml when
creating a tarball, setting the 'asset_version' parameter to the tag,
branch or commit hash used to create the release. This value is used
as cache buster in the html template.
See https://www.pivotaltracker.com/story/show/154839009
> Use release identifier as cache buster

- .travis.yml
- library/EngineBlock/Corto/Adapter.php
- library/EngineBlock/Corto/Module/Bindings.php
- library/EngineBlock/Corto/Module/Service/Metadata.php
- src/OpenConext/EngineBlock/Metadata/MetadataRepository/AbstractMetadataRepository.php
- src/OpenConext/EngineBlock/Metadata/MetadataRepository/CachedDoctrineMetadataRepository.php
- src/OpenConext/EngineBlock/Metadata/MetadataRepository/CompositeMetadataRepository.php
- src/OpenConext/EngineBlock/Metadata/MetadataRepository/MetadataRepositoryInterface.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockIdpContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockSpContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/SingleSignOn.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Fixtures/ServiceRegistryFixture.php
- tests/unit/OpenConext/EngineBlock/Metadata/MetadataRepository/CachedDoctrineMetadataRepositoryTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/MetadataRepository/InMemoryMetadataRepositoryTest.php
These methods are bugs waiting to happen. An entityID should only be
unique on a role basis. Technically an IdP and an SP could have the
same EntityID.
This PR removes these two methods and replaces any instance in the code
with a call to the relevant findSP or findIdP counterpart.
> Remove find/fetchEntityByEntityId methods

- src/OpenConext/EngineBlock/Metadata/MetadataRepository/Filter/CompositeFilter.php
The toExpression method in CompositeFilter contained a possible bug or at least a very confusing code construction. The if statements testing for the size of the expressions tested on the 'expression' variable who
1. Might not have been set
2. Might not be countable
This commit changes the method to the state is was intended to reflect.
> Fix possible bug in CompositeFilter

- .travis.yml
- library/EngineBlock/Corto/Adapter.php
- library/EngineBlock/Corto/Module/Bindings.php
- library/EngineBlock/Corto/Module/Service/Metadata.php
- src/OpenConext/EngineBlock/Metadata/MetadataRepository/AbstractMetadataRepository.php
- src/OpenConext/EngineBlock/Metadata/MetadataRepository/CachedDoctrineMetadataRepository.php
- src/OpenConext/EngineBlock/Metadata/MetadataRepository/CompositeMetadataRepository.php
- src/OpenConext/EngineBlock/Metadata/MetadataRepository/InMemoryMetadataRepository.php
- src/OpenConext/EngineBlock/Metadata/MetadataRepository/MetadataRepositoryInterface.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockIdpContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockSpContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/SingleSignOn.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Fixtures/ServiceRegistryFixture.php
- tests/unit/OpenConext/EngineBlock/Metadata/MetadataRepository/CachedDoctrineMetadataRepositoryTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/MetadataRepository/InMemoryMetadataRepositoryTest.php
Three methods have been moved to the InMemoryMetadataRepository as the only repository still depending on these methods was the InMemory  repository itself.
The remaining methods are shared between the Doctrine and InMemory repositories and my fingers are itching to get rid of the AbstractMetadataRepository altogether.
❕ Note that this branch did not trigger a Travis build. This should be remedied when this PR is merged back on top of #481
> Remove obsolete AbstractMetadataRepository methods

- app/Resources/views/modules/Authentication/View/Proxy/debugidpmail.phtml
- app/Resources/views/modules/Authentication/View/Proxy/debugidpresponse.phtml
- theme/material/templates/modules/Authentication/View/Proxy/debugidpmail.phtml
- theme/material/templates/modules/Authentication/View/Proxy/debugidpresponse.phtml
During the SAML2 upgrade, I failed to grep the /theme folder for misusage of the NameID value object. This commit fixes this for the debugidpmail and debugidpresponse templates.
> Fixed two misusages of the NameID value object

- app/config/config.yml
- database/DoctrineMigrations/Version20180215132859.php
- library/EngineBlock/Corto/Adapter.php
- library/EngineBlock/Corto/Filter/Command/ValidateAllowedConnection.php
- library/EngineBlock/Corto/Module/Service/IdpsMetadata.php
- library/EngineBlock/Corto/Module/Service/SingleSignOn.php
- library/EngineBlock/Corto/ProxyServer.php
- src/OpenConext/EngineBlock/Metadata/Entity/Assembler/JanusPushMetadataAssembler.php
- src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
- src/OpenConext/EngineBlock/Metadata/MetadataRepository/CachedDoctrineMetadataRepository.php
- src/OpenConext/EngineBlock/Metadata/MetadataRepository/DoctrineMetadataRepository.php
- src/OpenConext/EngineBlock/Metadata/MetadataRepository/InMemoryMetadataRepository.php
- src/OpenConext/EngineBlock/Metadata/MetadataRepository/MetadataRepositoryInterface.php
- src/OpenConext/EngineBlock/Metadata/MetadataRepository/Visitor/EngineBlockMetadataVisitor.php
- src/OpenConext/EngineBlockBundle/Doctrine/DqlFunction/Md5.php
This PR adds four improvements to unrelated use-cases in EngineBlock. The main principle is not loading all IDP entity IDs from the database, so the number of IDPs in the database does not affect the amount of traffic to and from the database. 
See [pivotal](https://www.pivotaltracker.com/story/show/154840957) and the individual commits for more information.
> Optimize metadata reading

- library/EngineBlock/Corto/Model/Response/Cache.php
- library/EngineBlock/Corto/Module/Service/AssertionConsumer.php
- library/EngineBlock/Corto/Module/Service/SingleSignOn.php
EngineBlock stores all SAML responses from the IDP in the user
session. Years ago, those responses were re-purposed on subsequent
logins. In order to support key roll-over EngineBlock also had to save
and restore the ID of the used signing key when re-using an old response.
Repurposing of responses is tricky in several ways so that feature was
removed (it's not EngineBlocks responsibility, the IDP should decide
if a session is still valid). But the SAML response is still stored
in the session, and the old signing key ID still overrides active
configuration.
This commit refactors the response cache mechanism:
- the SAML response and ID of the used signing key is not saved to
the session
- leaving only the SP/IDP entity ID combination in the user
session (so no more distinction between …
> Don't store SAML responses in user sessions

- database/DoctrineMigrations/Version20180221133212.php
- library/EngineBlock/Corto/Model/Consent.php
- src/OpenConext/EngineBlockBundle/Authentication/Entity/Consent.php
Relying on the database to set the consent date works, but has some
disadvantages:
* does not work on MySQL (it possibly does in non-strict mode, or
with a nullable field)
* doctrine must be set to 'options={"default": 0}' which is interpreted
as '"default": CURRENT_TIMESTAMP', while DEFAULT 0 in MySQL is a very
different feature than DEFAULT CURRENT_TIMESTAMP - too much
confusion here!
The actual problem we're trying to fix is travis throwing this error
in PR #413:
SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'consent_date'
Instead of changing travis to use MariaDB or trying to fix this issue
by making the SQL compatible with both MySQL and MariaDB, we decided
not to depend on this feature at all and simply insert new rows in the
consent table with …
> Explicitly set the consent date when user gives consent

- application/configs/application.ini
- library/EngineBlock/Attributes/Normalizer.php
- library/EngineBlock/Attributes/Provider/Interface.php
There are some more references to SURF(conext) but those are in the templating layer which I don't want to change right now while they're being ported to twig.
https://www.pivotaltracker.com/n/projects/1425900
> Remove SURF-isms from config and code

- composer.lock
See: https://github.com/paragonie/random_compat/issues/96
This vulnerability is actually two years old, but has recently been
added to the sensio security checker database. EngineBlock was not
affected because the insecure openssl function is only used when all
other providers (like mcrypt) are not installed.
> Apply security update to paragonie/random_compat

- bin/composer/dump-required-ini-params.sh
The configuration was always set to 'null' in ini_parameters.yml, due
to a bug introduced in 917901f.
> Fix missing idp debug mail configuration

- library/EngineBlock/ApplicationSingleton.php
- tests/library/EngineBlock/Test/ApplicationSingletonTest.php
It is not EngineBlocks responsibility to validate it's own
hostname. The webserver should be configured to allow specific
hostnames under which EngineBlock is served.
> Do not validate EngineBlocks own hostname

- theme/material/templates/modules/Authentication/View/Proxy/debug-idp-response.html.twig
The display was removed in commit d9c3ce3.
You can easily test this by adding the following conditions to attributes-2.2.0.json to an attribute not sent by mujina IDP:
```
"Conditions": {
"warning": {
"min": "1"
},
"error": {
"min": "1"
}
}
```
> Restore display of missing attributes on IDP debug page

- README.md
- UPGRADING.md
- application/configs/application.ini
- bin/composer/dump-required-ini-params.sh
- ci/travis/files/engineblock.ini
- docs/example.engineblock.ini
- library/EngineBlock/Application/Bootstrapper.php
- library/EngineBlock/ApplicationSingleton.php
- library/EngineBlock/Corto/Adapter.php
- library/EngineBlock/Http/Request.php
- tests/library/EngineBlock/Test/ApplicationSingletonTest.php
You can already configure this option in earlier versions of EB in
order to be forward compatible.
See PR #510 and https://www.pivotaltracker.com/story/show/155617973
> Require the 'hostname' INI setting

- composer.lock
Updates simplesamlphp to 1.15.3 and saml2 to 3.1.3.
Resolves security advisory SA-201802-01
> Update simplesamlphp packages

- .gitignore
- UPGRADING.md
- application/configs/application.ini
- bin/composer/dump-required-ini-params.sh
- languages/messages.en.php
- languages/messages.nl.php
- library/EngineBlock/Application/DiContainer.php
- library/EngineBlock/Corto/Module/Service/ProvideConsent.php
- src/OpenConext/EngineBlockBundle/Resources/config/services.yml
- src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/I18n.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/ClearErrorMessages.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/PolicyEnforcement.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/SpProxy.feature
- theme/material/templates/layouts/scripts/default.html.twig
- theme/material/templates/modules/Authentication/View/IdentityProvider/help-discover.html.twig
- theme/material/templates/modules/Authentication/View/IdentityProvider/request-access.html.twig
- theme/material/templates/modules/Authentication/View/Index/index.html.twig
- theme/material/templates/modules/Authentication/View/Proxy/consent-slidein-about.html.twig
- theme/material/templates/modules/Authentication/View/Proxy/consent.html.twig
- theme/material/templates/modules/Authentication/View/Proxy/debug-idp-response.html.twig
- theme/material/templates/modules/Authentication/View/Proxy/wayf.html.twig
See the upgrade instructions for a detailed description of the
changes. In summary, the following words are dynamically injected into
the translations in order to have a sane set of default translations
not specifically targeted to the educational world:
- %suiteName%:
- OpenConext (default)
- SURFconext, ACMEconext (example overrides)
- %organisationNoun%:
- organisation/organisatie (default)
- institution/instelling (example overrides)
- %organisationNounPlural%:
- organisations/organisaties (default)
- institutions/instellingen (example overrides)
- %accountNoun%:
- organisation account/organisatieaccount (default)
- institutional account/instellingsaccount (example overrides)
The WAYF help page is a special case because the questions and answers
all have their own translation key, and …
> Allow translation overrides and remove references to SURFconext

- .travis.yml
- library/EngineBlock/Saml2/NameIdResolver.php
- library/EngineBlock/Saml2/ResponseAnnotationDecorator.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/AttributeManipulation.feature
- tests/library/EngineBlock/Test/Saml2/NameIdResolverTest.php
The old style (array format) and new style (object of type NameID) are
now supported in the ResponseAnnotationDecorator.
For more context see [Pivotal](https://www.pivotaltracker.com/story/show/155705429)
:information_source: Note that the build fails on the Security Checker. `paragonie/random_compat` can be patched (which is done in version 5.7) but is postponed for version 5.6 as we are not vulnerable.
> Support old and new NameId style in AM

- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockSpContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/SingleSignOnWithScoping.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/MockServiceProvider.php
Scoped authn requests should limit the selection of available IDPs in
the WAYF, or pre-select an IDP if only a single IDP is scoped.
> Add functional tests for scoped AuthnRequest

- composer.lock
This commit upgrades engineblock-metadata to 3.1.2, which provides a
fix for a bug where all IDPs where shown on the WAYF, unfiltered, when
the experimental caching metadata backend was used.
See:
- https://github.com/OpenConext/OpenConext-engineblock-metadata/pull/24
- https://www.pivotaltracker.com/n/projects/1425900/stories/156995448
- OpenConext/OpenConext-engineblock#524
> Do not show all IDPs in WAYF when using experimental caching

- src/OpenConext/EngineBlock/Metadata/MetadataRepository/CachedDoctrineMetadataRepository.php
- tests/unit/OpenConext/EngineBlock/Metadata/MetadataRepository/CachedDoctrineMetadataRepositoryTest.php
Cached results are only valid for a specific combination of filters
and visitors. If a filter or visitor is appended, the previously
cached results should be discarded. In practice, visitor/filter setup
is only done in the beginning of the request so resetting the cache
has little impact on the total number of queries.
While no bug has been found in EB5.7 (all queries are executed after
setting up the filters) not solving this issue in the repository will
open the door for future bugs if some metadata is queried before
setting up the filters.
> Prevent unfiltered results in cached metadata repository

- src/OpenConext/EngineBlock/Authentication/Dto/Consent.php
- tests/unit/OpenConext/EngineBlock/Authentication/Dto/ConsentTest.php
If no diplay name is present in the metadata of a service provider,
use the name field or the entity ID instead.
See https://www.pivotaltracker.com/story/show/157775822
> Fall back to name or entity ID for display name in consent API

- library/EngineBlock/Arp/AttributeReleasePolicyEnforcer.php
- library/EngineBlock/Corto/Filter/Abstract.php
- library/EngineBlock/Corto/Filter/Command/Abstract.php
- library/EngineBlock/Corto/Filter/Command/AttributeReleasePolicy.php
- library/EngineBlock/Corto/Filter/Command/ResponseAttributeValueTypesModificationInterface.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/AttributeReleasePolicyAndAttributeManipulation.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockIdpContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/MockIdentityProvider.php
The Pivotal story describes the issue that is being fixed here in greater detail. In short, the attribute value type array needed to be updated to prevent the raising of an exception in the saml2 library.
The first commit adds behat tests that touch this problem. The second commit provides the bugfix for the issue.
The sec checker fails on the recent Symfony CVE's. I'm investigating the impact/benefits of a Symfony upgrade. And might open a new PR with the upgrade.
See: https://www.pivotaltracker.com/story/show/1581841791
> Array of value types and array of values have different size

- composer.lock
Version 5.7 did not yet include the symfony upgrade preventing the security checker from going off.
> Upgrade Symfony to 2.8.41

- src/OpenConext/EngineBlock/Metadata/Entity/Assembler/JanusPushMetadataAssembler.php
Before manage 2.0.18, consent should be disabled for all service
providers listed in 'disable_consent_connections'. Starting from the
new version of manage, the objects listed contain a type indicating
default, minimal or no consent.
In order to prevent unexpected behaviour when configuring default or
minimal consent in manage, we now check if the type is present and if
so, read the value to see if it's set to 'no_consent'.
> Prevent unexpected behaviour when using new manage on old EB

- src/OpenConext/EngineBlock/Logger/AuthenticationLogger.php
- src/OpenConext/EngineBlockBridge/Logger/AuthenticationLoggerAdapter.php
- tests/unit/OpenConext/EngineBlock/Logger/AuthenticationLoggerTest.php
- tests/unit/OpenConext/EngineBlockBridge/Logger/AuthenticationLoggerAdapterTest.php
The workflow state of the SP was chosen to serve as the log value. This
value should always be the same for the IdP. The state is stored in the
'workflow_state' key of the log context.
See: https://www.pivotaltracker.com/story/show/158283204
To test this in the dev vm. Tail  `/var/log/messages` grepping on `EBAUTH`. After authentication you should receive something like:
```
Jun 20 14:53:23 apps EBAUTH[5365]: {"channel":"authentication","level":"INFO","message":"login granted","context":{"login_stamp":"2018-06-20T14:53:23+02:00","user_id":"urn:collab:person:example.com:admin","sp_entity_id":"https:\/\/teams.vm.openconext.org\/shibboleth","idp_entity_id":"http:\/\/mock-idp","key_id":null,"proxied_sp_entity_ids":[],"workflow_state":"prodaccepted"},"extra":{"session_id":"5Y53SRgSPB6yuv1N9UWoQ …
```
> Log the workflow state to the auth logs

- src/OpenConext/EngineBlockBridge/ErrorReporter.php
- src/OpenConext/EngineBlockBundle/Controller/FeedbackController.php
- theme/material/templates/modules/Authentication/View/Feedback/authorization-policy-violation.html.twig
- theme/material/templates/modules/Default/View/Error/error.html.twig
PR #529 describes a bug in the policy-decision violation page.
EB5.7 streamlined all error pages: they now all show the 'feedback
info' table. But for PDP errors, the feedbackInfo session entry
contains an object holding the PDP failure - which cannot be cast to
string and should not be shown in the table.
This PR fixes the problem by not storing the PDP object into
'feedbackInfo', so the table can be safely rendered on the PDP error
page.
> Fix error in PDP policy decision error page

- theme/material/templates/modules/Authentication/View/IdentityProvider/request-access.html.twig
Form submission was broken because of a missing hidden input
field. The 'idpEntityId' field was removed by accident in 57df383.
See https://www.pivotaltracker.com/story/show/155516160
> Fix broken request-access form submission

- theme/material/templates/modules/Authentication/View/Proxy/consent.html.twig
Since the bugfix of the 'uneven' attribute value and type arrays was
introduced in the codebase. ARP filtering started introducing some
side effects on the consent screen.
This because attribute value and type arrays are filtered, taking extra
care to keep the keys intact. This might result in filtering away value
0, 2 and 3, leaving index 1.
The previous twig solution was not robust in that aspect and always
showed index 0, as that previously always was the first (and only) entry
in the case of a single value attribute.
Now the first filter is used to get the first array entry from the array
regardless of index, fixing the problem.
See: https://www.pivotaltracker.com/story/show/158184179/comments/191135246
> Use the first array value when single attribute value is shown on consent screen

- theme/material/templates/modules/Authentication/View/Index/index.html.twig
Just removes the section from the Twig template. Removal of the actual
metadata endpoints will be picked up at a later stage in the refactoring
of EB metadata generation.
See: https://www.pivotaltracker.com/story/show/158439992
> Remove eduGAIN section from front page

- library/EngineBlock/Corto/Filter/Command/ProvisionUser.php
When unspecified name id is set for the SP, the wrong name id value
was displayed on the consent screen. This fix sets the correct name id
value for display on consent.
See: the second bugreport from: https://www.pivotaltracker.com/story/show/154912151/comments/191385599
> Actually show the collab name id on consent

- library/EngineBlock/Corto/Filter/Command/ProvisionUser.php
The Transient NameID was generated multiple times during the processing
of the SAMLResponse. Resulting in a reoccurring consent screen. Every
time the NameIDResolver creates (and stores) a new transient NameID the
next time we pass consent, EB thinks new consent must be given.
See first bug report from:
https://www.pivotaltracker.com/story/show/154912151/comments/191385599
> Prevent multiple generations of transient NameID

- app/config/config_dev.yml
- src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/Debug.php
- src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/Feedback.php
- src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/Locale.php
- src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/Metadata.php
- src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/UserAgent.php
- theme/material/templates/layouts/scripts/default.html.twig
- theme/material/templates/layouts/scripts/language-switcher.html.twig
- theme/material/templates/modules/Authentication/View/Proxy/consent.html.twig
During the introduction of twig in engineblock. Some XSS vulnerabilities have been overlooked. This PR aims to fix all of these issues.
> Prevent twig extension XSS vulnerabilities

- build.xml
The app_dev.php file provisioned by OpenConext-deploy (with ENV=dev)
has debugging enabled (true) but the build.xml enable-test-env and
disable-test-env tasks expected the debugging flag to be false.
With this change, the behat-dev task will work without modification of
build.xml or app_dev.php.
> Fix 'enable-test-env' to work out-of-the-box

- README.md
The mentioned 'migrate' script was removed in e729b8d, doctrine
migrations is the only required tool for managing database
changes. The READE now reflects the current situation.
> Update database migration instructions in README

- languages/messages.en.php
- languages/messages.nl.php
- theme/material/templates/modules/Authentication/View/Proxy/wayf.html.twig
The testers found a bug in EB 5.7.4. When there's a previously selected IdP, the gray bar above this section ("Eerder gekozen") is missing. This is now fixed.
Also fixes a nitpick: the page <title> is not very beatiful as witnessed from the filenames of these screenshots
> Revert suggestion title on wayf screen

- src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
Was fixed in https://github.com/OpenConext/OpenConext-engineblock/commit/34cc5a94895e98bc0bc12c9fc12a5f6080d01b7a but probably got lost during Twigification
> Fix SP displayName regression

- library/EngineBlock/Corto/Module/Service/SingleSignOn.php
The 'idp-logo-not-found.png' logo is set with a wrong path. This is now
replaced with a placeholder image.
See [Pivotal](https://www.pivotaltracker.com/story/show/158685306)
> Fix the idp placeholder logo

- README.md
- languages/messages.en.php
- languages/messages.nl.php
- library/EngineBlock/ApplicationSingleton.php
- src/OpenConext/EngineBlockBundle/Controller/FeedbackController.php
When a user wants to log into a service that the IdP does not allow,
and the user is presented with an error page "No connection between
institution and service", the entityID of the SP is listed. Now also
the SP name is shown in this message because that's more meaningful.
Also see the [Pivotal issue](https://www.pivotaltracker.com/story/show/149064131)
> Show SP name on "No connection between institution and service" page

- CHANGELOG.md
- UPGRADING.md
- database/DoctrineMigrations/Version20180724175453.php
- docs/attribute_aggregation.md
- library/EngineBlock/Corto/Filter/Command/AttributeAggregator.php
- src/OpenConext/EngineBlock/Metadata/Entity/Assembler/JanusPushMetadataAssembler.php
- src/OpenConext/EngineBlock/Metadata/Entity/Disassembler/CortoDisassembler.php
- src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Fixtures/ServiceRegistryFixture.php
- tests/library/EngineBlock/Test/Corto/Filter/Command/AttributeAggregatorTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/Entity/Disassembler/CortoDisassemblerTest.php
The attribute aggregator is now only queried when the metadata setting
coin:attribute_aggregation_required is set. This is simplified and
therefore an SP does not require this extra setting to be enabled
anymore.
> Remove attribute_aggregation_required metadata setting

- CHANGELOG.md
- composer.lock
Symfony was upgraded to 2.8.44 to harden against CVE-2018-14773
> Upgrade Symfony to 2.8.44

- CHANGELOG.md
- UPGRADING.md
- app/config/security.yml
- application/configs/application.ini
- bin/composer/dump-required-ini-params.sh
- ci/travis/files/engineblock.ini
- composer.json
- docs/attribute_aggregation.md
- library/EngineBlock/Saml2/NameIdResolver.php
- src/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssembler.php
- src/OpenConext/EngineBlockBundle/Controller/Api/ConnectionsController.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Resources/config/services.yml
- tests/functional/OpenConext/EngineBlockBundle/Controller/Api/ConnectionsControllerTest.php
Instead of using Janus or Manage as an indication for the push API
feature that EngineBlock features, a more generic 'metadata push' nomer
is used.
Also see Pivotal: https://www.pivotaltracker.com/story/show/157912446
> Rename Janus references

- CHANGELOG.md
- UPGRADING.md
- database/DoctrineMigrations/Version20180804090135.php
- library/EngineBlock/SamlHelper.php
- src/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssembler.php
- src/OpenConext/EngineBlock/Metadata/Entity/Disassembler/CortoDisassembler.php
- src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
As per mailinglist discussion:
https://groups.google.com/forum/#!topic/openconext/riXK5xjacIw
Default (current) behaviour:
Trusted proxy sets no requesterId > all attributes are released
New behaviour when 'requesterid_required' is true:
Trusted proxy sets no requesterid > Raise unknown service exception
> Allow enforcing requesterid on trusted proxy

- CHANGELOG.md
- library/EngineBlock/Corto/Module/Bindings.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/EngineBlockContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/SingleSignOn.feature
The return field is filled with the 'return' value that can optionally
be set by the ProcessedAssertionConsumer or AssertionConsumer. When
sending the SAML response using the POST binding, EB now tests if the
setReturn method exists on the SamlMessage which is of the annotated
type in most cases. The method usually exists, so even tho the setter
for 'return' might have never been called, it was still added.
The fix consists of an additional test if the return is not empty.
A simple behat test was added that verifies the return form field is not
added when it should not be.
See https://www.pivotaltracker.com/story/show/159466469
> Prevent adding empty 'return' hidden input field

- library/EngineBlock/Corto/Mapper/Legacy/ResponseTranslator.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/AttributeManipulation.feature
This PR aims to add support for setting NameId objects on the CustomNameId using attribute manipulation.
For now, the added Behat scenario should cause the build to fail, as NameID, set on the CustomNameID field are not yet supported in AM.
More details about the bugfix can be found in Pivotal
https://www.pivotaltracker.com/story/show/159823307
> Test CustomNameId can be set with NameId object

- CHANGELOG.md
- application/configs/application.ini
- bin/composer/dump-required-ini-params.sh
- composer.lock
- src/OpenConext/EngineBlockBundle/HealthCheck/DoctrineConnectionHealthCheck.php
- src/OpenConext/EngineBlockBundle/Resources/config/services.yml
The monitor_database_health_check_query ini config is used to set the
Symfony yml param, which is included in the monitor config that was
added to the services.yml file.
By default a sensible query is set in the application.ini, this can be
overridden if so desired by the end user.
Todo:
> Make database health query configurable

- application/configs/application.ini
This is a fix to check on another db table then the migration table to
prevent the loadbalancer from returning 503 errors when testing. The
test environment doesn't have a migration table because only the tables
are created from the entities.
https://www.pivotaltracker.com/story/show/158906723
> Fix healthcheck query for test env

- src/OpenConext/EngineBlockBundle/HealthCheck/DoctrineConnectionHealthCheck.php
The shutdown function in the monitor bundle isn't always called
after a request. So we need to manually close the connection to
prevent the connections from staying open.
>  Prevent 'Aborted connection' warnings from the DoctrineConnectionHealthCheck

- composer.lock
This change will prevent unwanted entries in the logs with a lot of aborted connections.
> Update monitor-bundle to latest version

- .travis.yml
- CHANGELOG.md
- application/configs/application.ini
- bin/composer/dump-required-ini-params.sh
- languages/messages.en.php
- languages/messages.nl.php
- library/EngineBlock/Application/DiContainer.php
- library/EngineBlock/Corto/Adapter.php
- library/EngineBlock/Corto/Module/Bindings.php
- library/EngineBlock/Corto/Module/Bindings/UnsupportedAcsLocationSchemeException.php
- src/OpenConext/EngineBlock/Metadata/Entity/Assembler/MetadataAssemblerInterface.php
- src/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssembler.php
- src/OpenConext/EngineBlock/Validator/AllowedSchemeValidator.php
- src/OpenConext/EngineBlock/Validator/ValidatorInterface.php
- src/OpenConext/EngineBlockBundle/Controller/Api/ConnectionsController.php
- src/OpenConext/EngineBlockBundle/Controller/FeedbackController.php
- src/OpenConext/EngineBlockBundle/EventListener/RedirectToFeedbackPageExceptionListener.php
- src/OpenConext/EngineBlockBundle/Resources/config/controllers/api.yml
- src/OpenConext/EngineBlockBundle/Resources/config/routing/feedback.yml
- src/OpenConext/EngineBlockBundle/Resources/config/services.yml
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/AcsTinkering.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockSpContext.php
- tests/integration/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssemblerTest.php
- theme/material/templates/modules/Authentication/View/Feedback/unsupported-acs-location-scheme.html.twig
There was a possible XSS vulnerability where EB would take the ACS location from a signed AuthnRequest and use that location to send the SAMLResponse. The URI scheme was prone to XSS, as the JS URI scheme was allowed.
The proposed change makes the allowed URI schemes configurable. By default only allowing the `http` and `https` schemes.
The ACS locations that are received from Manage are also validated.
This PR is first targeted at the 5.8 branch.
:warning: Disclaimer, the build fails on the security checker. This is a well-considered decision.
> Filter ACS location URI scheme to prevent XSS vulnerability

- CHANGELOG.md
- library/EngineBlock/Corto/Filter/Command/ProvisionUser.php
- library/EngineBlock/Corto/Model/Consent.php
- library/EngineBlock/Corto/Model/Consent/Factory.php
- library/EngineBlock/Corto/Module/Service/ProvideConsent.php
More details why this change was made can be found [in the Pivotal issue that was filed](https://www.pivotaltracker.com/story/show/162440852).
This PR ensures the correct NameId value is displayed on the consent screen without overwriting the NameId before the output filtering is applied. When EB is configured to run with `run_all_manipulations_prior_to_consent`, then also the correct values are shown on the consent screen.
Note that the build fails on the security checker. This is an acceptable risk at this point. And will be fixed in EB 5.9
This PR targets release `5.8.6` and should also land on `master` (5.9)
> Stop overwriting the NameId before giving consent

- library/EngineBlock/Corto/Module/Bindings.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/AcsTinkering.feature
Even though our bar is not that high (just needs to start with
'http:' or 'https:'), there's stuff out there that does not meet
this bar. Log it first so we can get that fixed before we block
it.
> Downgrade unsupported ACS location to a warning for now.

- CHANGELOG.md
- src/OpenConext/EngineBlock/Metadata/MultilingualValue.php
In some cases this error message is raised in the logs, and the generic
error message does not help to identify the actual problem.
Before: 'Value "<NULL>" expected to be string, type NULL given.'
After: 'The 'value' of a MultilingualValue should be a string. "%s" given'
> Improve the error message from MultilingualValue

- library/EngineBlock/Corto/Module/Service/SingleSignOn.php
It always showed the English version, despite the current locale
> Fix displayName on WAYF

- .travis.yml
- ci/travis/vhost-apache
- composer.json
- composer.lock
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockIdpContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockSpContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Fixtures/DataStore/AbstractDataStore.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Fixtures/FunctionalTestingAttributeAggregationClient.php
This PR tries to isolate (and fix) the issue with the failing functional tests on PHP 5.6 builds. Behat 3 on Travis Precice in combination with PHP 5.6 causes weird filesystem issues. Where files written to disk (in the project folder) are not always readable.
The following commits address this issue by leveraging Flysystem. Flysystem can easily be set with different locking strategies.
In addition to using Flysystem, an additional manual call to gc_collect_cycles was required to ensure clearing the fixture files does not fail.
One other task that was included in this PR was the move from Travis (precise) to Travis Xenial. Hoping the filesystem issue would not be present on that platform. This was not the case. But moving away from the already decommissioned Precise was a task that was …
> Make tests Behat 3 compatible on Travis PHP 5.6

- CHANGELOG.md
- src/OpenConext/EngineBlockFunctionalTestingBundle/Controllers/ServiceProviderController.php
We are not vulnerable in this situation, but implementing best practices
is always important. For example to prevent serious issues if this code
is ever used as an example / copy paste.
See: https://www.pivotaltracker.com/story/show/161177388
> Harden against hypothetical XXE vulnerability

- languages/messages.en.php
- languages/messages.nl.php
The text is rephrased in order to prevent possible confusion when
minimal consent is rejected.
https://www.pivotaltracker.com/story/show/161508398
> Update the consent reject text

- languages/messages.en.php
- languages/messages.nl.php
- languages/messages.pt.php
- theme/material/templates/modules/Authentication/View/Proxy/consent.html.twig
For some SPs, no attributes are sent from IdP to SP (only NameID). In
those cases, the information below the IdP is missing (which is logical
because no attributes are sent). This PR adds the new text and displays
it in the consent template when no attributes are present.
https://www.pivotaltracker.com/story/show/163524882
> Show explanation when no attributes required

- src/OpenConext/EngineBlockBundle/AttributeAggregation/Dto/Response.php
- tests/unit/OpenConext/EngineBlockBundle/AttributeAggregation/AttributeAggregationClientTest.php
- tests/unit/OpenConext/EngineBlockBundle/AttributeAggregation/fixture/success-response-with-epti.json
AA response values that are non-string should be filtered out of the
AA client response. The EPTI caused this problem to surface. See the
ticket below for more information.
See: https://www.pivotaltracker.com/story/show/162197380
> Filter AA response

- build.xml
The end point: http://security.sensiolabs.org/check_lock was four oh
fouring. The current release of the sec chekcer works correctly on
Travis. So cleaning up the previous Travis specific security check was
the most pragmatic solution to the failing security checks.
> Remove dispensable Travis sec-checker solution

- src/OpenConext/EngineBlock/Exception/InvalidBindingException.php
- src/OpenConext/EngineBlock/Exception/InvalidRequestMethodException.php
- src/OpenConext/EngineBlock/Validator/RequestValidator.php
- src/OpenConext/EngineBlock/Validator/SsoRequestValidator.php
- src/OpenConext/EngineBlockBundle/Controller/IdentityProviderController.php
- src/OpenConext/EngineBlockBundle/Resources/config/controllers/authentication.yml
- src/OpenConext/EngineBlockBundle/Resources/config/services.yml
- tests/functional/OpenConext/EngineBlockBundle/Controller/Api/AttributeReleasePolicyControllerApiTest.php
- tests/integration/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssemblerTest.php
- tests/library/EngineBlock/Test/Corto/Filter/Command/VerifyShibMdScopingAllowsEduPersonPrincipalNameTest.php
- tests/library/EngineBlock/Test/Corto/Filter/Command/VerifyShibMdScopingAllowsSchacHomeOrganisationTest.php
- tests/library/EngineBlock/Test/Corto/Module/BindingsTest.php
- tests/library/EngineBlock/Test/Corto/Module/Service/Metadata/ServiceReplacerTest.php
- tests/library/EngineBlock/Test/Corto/Module/Service/ProcessConsentTest.php
- tests/library/EngineBlock/Test/Corto/XmlToArrayTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/AttributeReleasePolicyTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/MetadataRepository/CachedDoctrineMetadataRepositoryTest.php
- tests/unit/OpenConext/EngineBlock/Validator/SsoRequestValidatorTest.php
- tests/unit/OpenConext/EngineBlockBundle/AttributeAggregation/Dto/AttributeRuleTest.php
- tests/unit/OpenConext/EngineBlockBundle/AttributeAggregation/Dto/RequestTest.php
- tests/unit/OpenConext/EngineBlockBundle/AttributeAggregation/Dto/ResponseTest.php
- tests/unit/OpenConext/EngineBlockBundle/EventListener/ExecutionTimeTrackerEventListenerTest.php
Logging of incorrect requests on the SSO endpoint where quite cryptic. Often resulting in a generic 500 error page with a log entry reading: `Unable to find the current binding.`. 
This PR aims to improve the error reporting portion of this problem. The actual better user-facing error handling is addressed in an upcoming PR. This PR introduces a request validator that is used upon entry of the SSO controller action. It tests if a supported request method is used (GET is currently supported exclusively) and if the correct binding is used (HTTP binding is expected).
If the request does not match these criteria, a meaningfull exception is thrown. Either reflecting the use of an usupported request method. Or in the case of an usuported SAML request binding, will report which binding was …
> Catch SSO endpoint [ab|mis]use earlier

- languages/messages.en.php
- languages/messages.nl.php
- languages/messages.pt.php
- src/OpenConext/EngineBlockBundle/EventListener/MethodNotAllowedHttpExceptionListener.php
- src/OpenConext/EngineBlockBundle/Resources/config/event_listeners.yml
- src/OpenConext/EngineBlockBundle/Resources/config/routing_api.yml
- theme/material/templates/modules/Default/View/Error/method-not-allowed.html.twig
The http 405 (request method not allowed) error handling has been made
more verbose for the users of engine block. A custom error screen was
added where the user is informed of the error situation.
On this screen we do not show the error table as we do during the
authentication process.
Task 1 of: https://www.pivotaltracker.com/story/show/164121663
> Render 405 error pages more elegantly

- app_dev.php.dist
- build.xml
Ant changed the app_dev.php when starting the tests. So 'dev' was
changed to 'test' to run in test mode. This resulted in a corrupt
app_dev.php when a test failed.
> Remove separate test build from ant

- library/EngineBlock/Corto/Module/Bindings.php
- src/OpenConext/EngineBlockBundle/Resources/config/routing/service_provider.yml
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/ClearErrorMessages.feature
We stated that GET was also allowed in order to render more user
friendly error reports. That was not at all the case. In a recent effort
error reporting regarding disallowed request methods was improved.
So we can now start enforcing POST requests on the ACS endpoint. Any
other request method will result in routing exception that in turn will
be handled by the improved error reporting.
Task 2 & 4 of: https://www.pivotaltracker.com/story/show/164121663
Also see: #646
> Allow only POST requests on /sp/consume-assertion

- library/EngineBlock/Corto/Module/Service/SingleSignOn.php
When creating a new authnrequest based on a call to the
unsolicited-single-sign-on endpoint, do not forget to set
the keyid in this new request if it was specified in the
u-s-s-o URL.
This fixes the bug that assertions to SPs in response to unsolicited sso
calls would always be signed with the default key, regardless of any
explicit keyslugs in the unsolicited sso endpoint call.
> Honor explicit keyid in unsolicited single sign on request

- library/EngineBlock/Corto/Module/Service/SingleSignOn.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockSpContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/SpProxy.feature
This bugfix adds a Behat scenario the reproduces the behavior described in the bug report. It then proceeds to fix the issue by preventing IdP scope limiting based on previously selected IdPs.
More details about this bug can be found in:
https://www.pivotaltracker.com/story/show/164069793
> Fix unexpected SSO behaviour for trusted proxy

- languages/messages.en.php
- languages/messages.nl.php
- languages/messages.pt.php
- library/EngineBlock/Corto/Module/Bindings.php
- library/EngineBlock/Corto/Module/Bindings/ClockIssueException.php
- library/EngineBlock/Corto/Module/Bindings/TimingException.php
- src/OpenConext/EngineBlockBundle/Controller/FeedbackController.php
- src/OpenConext/EngineBlockBundle/EventListener/RedirectToFeedbackPageExceptionListener.php
- src/OpenConext/EngineBlockBundle/Resources/config/routing/feedback.yml
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/ClearErrorMessages.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockIdpContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/MockIdentityProvider.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Saml2/ResponseFactory.php
- tests/library/EngineBlock/Test/Corto/Module/BindingsTest.php
- theme/material/templates/modules/Authentication/View/Feedback/clock-issue.html.twig
This PR adds a custom error page for when the issuer instant of the assertion is before/after the allowed time determined by the SAML2 response validator.
The individual commits should give additional information.
Test-tip:
Either manipulate your IdP to send out of time saml responses, or update the response before validating it in the bindins module.
1. Go to: `\EngineBlock_Corto_Module_Bindings::receiveResponse` at line 264
2. Override the NotOnOrAfter of the first assertion by adding line: `$sspResponse->getAssertions()[0]->setNotOnOrAfter(0);` to mimick an idp from the past
3. Override the `$sspResponse->getAssertions()[0]->setNotBefore(strtotime(date('Y-m-d H:i:s', strtotime('+1 year'))));` to mimick an idp from the future
This fixes tasks 1 and 2 of: …
> Improve error reporting for clock related SAMLResponse issues

- theme/material/javascripts/application.js
- theme/material/javascripts/modules/MouseListener.js
When the mouse moves away from the search bar, previously the focus was blurred from the input field.
This behavior made using the search bar very un-user-friendly. Removing this behavior seems to fix the issue at hand.
Fixes https://www.pivotaltracker.com/story/show/165020904
> Prevent blurring the search bar

- languages/messages.pt.php
As suggested in: https://github.com/OpenConext/OpenConext-engineblock/pull/655#discussion_r271282767 by a native speaker, the translation for the clock issue title was updated.
Thanks @domgon!
> Update PT tranlation of error_clock_issue_title

- library/EngineBlock/Corto/ProxyServer.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/ClearErrorMessages.feature
The endpoints needing a session cookie were incomplete and needed to be
fixed.
> Update endpoints needing sessions

- .travis.yml
The build with 10.1 breaks because apparmor kicks in and prevents
mariadb from starting. This is a temporarily workaround and should
maybe be reverted over time.
> Change mariadb version to fix travis builds

- library/EngineBlock/Corto/Module/Service/AssertionConsumer.php
- src/OpenConext/EngineBlock/Exception/MissingParameterException.php
- src/OpenConext/EngineBlock/Validator/AcsRequestValidator.php
- src/OpenConext/EngineBlock/Validator/SamlBindingValidator.php
- src/OpenConext/EngineBlock/Validator/SsoRequestValidator.php
- src/OpenConext/EngineBlockBundle/Authentication/AuthenticationState.php
- src/OpenConext/EngineBlockBundle/Controller/IdentityProviderController.php
- src/OpenConext/EngineBlockBundle/Controller/ServiceProviderController.php
- src/OpenConext/EngineBlockBundle/EventListener/RedirectToFeedbackPageExceptionListener.php
- src/OpenConext/EngineBlockBundle/Resources/config/controllers/authentication.yml
- src/OpenConext/EngineBlockBundle/Resources/config/services.yml
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/ClearErrorMessages.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/EngineBlockContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Service/EngineBlock.php
- tests/unit/OpenConext/EngineBlock/Validator/AcsRequestValidatorTest.php
- tests/unit/OpenConext/EngineBlock/Validator/SamlBindingValidatorTest.php
- tests/unit/OpenConext/EngineBlock/Validator/SsoRequestValidatorTest.php
- tests/unit/OpenConext/EngineBlockBundle/Authentication/AuthenticationStateTest.php
This is done in order to make sure that the 'Current authentication
procedure exceptions' are split up. So the information returned
should be much more informative.
> Add Saml binding validator to acs endpoint

- UPGRADING.md
- application/configs/application.ini
- bin/composer/dump-required-ini-params.sh
- src/OpenConext/EngineBlockBundle/Controller/Api/ConnectionsController.php
- src/OpenConext/EngineBlockBundle/Resources/config/controllers/api.yml
The metadata memory limit needs to be configurable. This is done so
engineblock could be quickly configured to allow more data being
pushed.
https://www.pivotaltracker.com/n/projects/1425900/stories/164329554
https://github.com/OpenConext/OpenConext-deploy/pull/199
> Make the memory limit for push configurable

- languages/messages.en.php
- languages/messages.nl.php
- languages/messages.pt.php
The ul needed to be removed from the session exception message.
> Remove ul from session exception messages

- build.xml
- docs/js_testing.md
- theme/.gitignore
- theme/material/javascripts/tests/visual-regression/error-page/ErrorPage.test.js
- theme/package-lock.json
- theme/package.json
Different error pages are visited and compared to previous snapshots
when a screenshot differs from a previous one, the test will fail. This
test should be run manually for now.
See task 3 of https://www.pivotaltracker.com/story/show/165593518
> Implement visual regression tests for error pages

- build.xml
- database/DoctrineMigrations/Version20190425205743.php
- library/EngineBlock/Corto/Module/Bindings.php
- src/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssembler.php
- src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MinkContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockSpContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Encryption.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Fixtures/ServiceRegistryFixture.php
An option is needed to sign the saml response if the option
`metadata:coin:sign_response` is set. This because some sp's require
the saml response to be signed and not only the assertions.
> Add the possibility to sign a SAML response

- src/OpenConext/EngineBlockFunctionalTestingBundle/Controllers/FeedbackController.php
- theme/material/javascripts/tests/visual-regression/error-page/Footer.test.js
In order to detect regressions in the footer of the feedback page
some tests are added.
> Add visual tests for the feedback page footer

- .travis.yml
- README.md
- bin/makeRelease.sh
Npm was not consistent between builds and changed the package-lock.json.
Therefore we are now using the 'ci' commmand.
https://docs.npmjs.com/cli/ci.html
> Fix npm installation consistency between builds

- library/EngineBlock/Corto/ProxyServer.php
The debugSingleSignOnService was only added to the configuration
array in the corto proxyserver on master but not in the 5.10 release
branch while this was needed. This was done in order to prevent it from
checking if the session did already start.
> Whitelist debugSingleSignOnService for session

- .travis.yml
- src/OpenConext/EngineBlockBundle/Controller/IdentityProviderController.php
The validations are solicited SSO specific. Adding them on the unsolicited SSO endpoint blocks the unsolicited sso attempts.
Removing them for now is the best option right now, adding an additional request validator for unsolicited single sign on is requested in this ticket: https://www.pivotaltracker.com/story/show/165821300
Also see: https://www.pivotaltracker.com/story/show/164121560/comments/202263683
:warning: Cherry pick this on master!
> Remove validation on unsolicitedSingleSignOnAction

- src/OpenConext/EngineBlock/Validator/UnsolicitedSsoRequestValidator.php
- src/OpenConext/EngineBlockBundle/Controller/IdentityProviderController.php
- src/OpenConext/EngineBlockBundle/Resources/config/controllers/authentication.yml
- src/OpenConext/EngineBlockBundle/Resources/config/services.yml
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/EngineBlockContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/UnsolicitedSingleSignOn.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Service/EngineBlock.php
- tests/unit/OpenConext/EngineBlock/Validator/UnsolicitedSsoRequestValidatorTest.php
Three tests where added:
1. Verify that specifying a signing key id works correctly
2. Ensure passing a non existent signing key results in the expected
error
3. Triggering an unsolicited SSO authentication with incorrect/missing
query parameters trigger the expected error.
Resolves task 2 of https://www.pivotaltracker.com/story/show/165821300
:warning: include this in release 5.11, so also merge to `master`
> Enrich unsolicited SSO test coverage

- src/OpenConext/EngineBlockBundle/Controller/FeedbackController.php
- src/OpenConext/EngineBlockBundle/EventListener/FallbackExceptionListener.php
- src/OpenConext/EngineBlockBundle/Resources/config/event_listeners.yml
- src/OpenConext/EngineBlockBundle/Resources/config/routing.yml
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/ClearErrorMessages.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/EngineBlockContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Resources/config/services.yml
- src/OpenConext/EngineBlockFunctionalTestingBundle/Validator/SsoRequestValidator.php
- theme/material/javascripts/tests/visual-regression/error-page/ErrorPage.test.js
That was previously also possible (but might have leaded to a new error condition), and resulted in a new unique request id, timestamp combination upon reload. Making it very hard for service desk to match the request id with the actual error message in logs.
This is resolved by redirecting to the feedback controller. On this controller a new action handles the 'unknown error'.
This action is intentionally not accessible on the authentication/feedback base route. This because the unknown error might not be authentication related.
See: https://www.pivotaltracker.com/story/show/164076480
> Make uncaught error page reloadable

- theme/material/stylesheets/theme/openconext/error-page/_background.sass
When the viewport is smaller than large (1024px), then the surfboard is moved to a position of '-8% left' of the viewport boundary. This makes sure the image is well readable when the viewport size is smaller.
The SVG itself (not tracked in this repo) is updated, the sign is moved to the left of the surfboard.
See point 1 of https://www.pivotaltracker.com/story/show/166437858
> Move the SURFboard to the left on smaller than large viewports

- theme/material/stylesheets/error-page/modules/_feedback-info.sass
By using overflow-wrap with the anywhere option, we should be able to display longer strings in the feedback blocks without losing any text to an overflow hidden option.
Overflow wrap instructs the render engine to find a way to break the string wherever it sees fitting. This might result in grammatically incorrect word-breaks. But this would be virtually impossible to do correctly in the context of an entity id. The ability to read the entire string (which was not possible with the previous text-overflow: ellipsis solution) is a requirement for the support team to be able to find possible problems with the entity ids. 
See task 7 from: https://www.pivotaltracker.com/story/show/166437858
> Improve feedback information word wrapping

- theme/material/stylesheets/error-page/modules/_error-details.sass
The top and bottom margin is set to 1.5em. This visually improves the error feedback block.
Solves point 3 of https://www.pivotaltracker.com/story/show/166437858
> Add margin to the error feedback block

- theme/material/stylesheets/error-page/base/_page.css.sass
- theme/material/stylesheets/error-page/modules/_error-container.sass
The container is now positioned in the exact middle of the page for viewports greater than small.
There are multiple ways to vertical align a container. This one seems to fit the current HTML structure very well.
This fixes point 10 of https://www.pivotaltracker.com/story/show/166437858
> Vertical align the error continer

- bin/makeRelease.sh
When deploying a development branch of EB to our test environment, we do this as root (hysterical raisins). We run `bin/makeRelease.sh` as root after checking out the branch to build the assets.
This fails because NPM thinks this is unsafe and runs installation as user `nobody` in that case. Which has permission problems because that user cannot write to the checked out tree.
The flag `--unsafe-perm` option tells npm not to do this.
This is acceptable I think because it only has effect if you are running `bin/makeRelease.sh` as root. So it does not make normal developer use, or anyone that runs it as non-root, more unsafe. And if you do run bin/makeRelease.sh as root you're already exposed to plenty of risks from other tools (hence we only do this on test).
The longer term solution is to …
> Run node with the unsafe-perm option

- theme/material/stylesheets/application/base/_layout.css.sass
- theme/material/stylesheets/shared/components/_language.css.sass
The language switcher lays below the page container. Therefore
the language switcher isn;t clickable on the error page. After changing
the z-index the required behaviour is restored.
> Increase language switch z-index on the error page

- theme/material/stylesheets/theme/openconext/error-page/_background.sass
The surfboard could be better aligned on wide screens. The surfboard
scales better now with the use of css.
https://www.pivotaltracker.com/story/show/167202154
> Decrease the surfboard offset on the error page

- theme/material/templates/modules/Default/View/Error/method-not-allowed.html.twig
- theme/material/templates/modules/Default/View/Error/not-found.html.twig
The language switch is hidden because it will not work out of the box
because the lang parameter is read from the request but the parameters
are empty when on a 404 page.
See: https://www.pivotaltracker.com/story/show/167202103/comments/204653786
> Hide language switch on 400 and 405 page

- theme/package-lock.json
Versions of lodash before 4.17.12 are vulnerable to Prototype Pollution. The function defaultsDeep allows a malicious user to modify the prototype of Object via {constructor: {prototype: {...}}} causing the addition or modification of an existing property that will exist on all objects.
https://www.npmjs.com/advisories/1065
> Bump lodash to mitigate Node sec advisory 1065

- application/configs/application.ini
- bin/composer/dump-required-ini-params.sh
- languages/messages.en.php
- languages/messages.nl.php
- languages/messages.pt.php
- library/EngineBlock/Application/DiContainer.php
- library/EngineBlock/Application/FunctionalTestDiContainer.php
- library/EngineBlock/Corto/Exception/AuthnContextClassRefBlacklisted.php
- library/EngineBlock/Corto/Filter/Command/ValidateAuthnContextClassRef.php
- library/EngineBlock/Corto/Filter/Input.php
- src/OpenConext/EngineBlockBundle/Controller/FeedbackController.php
- src/OpenConext/EngineBlockBundle/EventListener/RedirectToFeedbackPageExceptionListener.php
- src/OpenConext/EngineBlockBundle/Resources/config/routing/feedback.yml
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/ClearErrorMessages.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockIdpContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/MockIdentityProvider.php
- tests/library/EngineBlock/Test/Corto/Filter/Command/ValidateAuthnContextClassRefTest.php
- theme/material/javascripts/tests/visual-regression/error-page/ErrorPage.test.js
- theme/material/templates/modules/Authentication/View/Feedback/authn-context-class-ref-blacklisted.html.twig
Add a configurable regex filter to be able to blacklist certain AuthnContextClassRef attribute values. This will be used to prevent the use of internally used attributes by IdP's other than EngineBlock. And to allow second factor only (SFO) flow in EB.
Also created a [PR](https://github.com/OpenConext/OpenConext-deploy/pull/237) to support the configuration parameter in deploy.
See: https://www.pivotaltracker.com/story/show/166702153
> Add AuthnContextClassRef attribute blacklist filter

- src/OpenConext/EngineBlockFunctionalTestingBundle/Controllers/SfoMockController.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/SfoContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Sfo.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Fixtures/FunctionalTestingSfoGatewayMockConfiguration.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/MockSfoGateway.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Resources/config/controllers.yml
- src/OpenConext/EngineBlockFunctionalTestingBundle/Resources/config/mocks.yml
- src/OpenConext/EngineBlockFunctionalTestingBundle/Resources/config/routing.yml
- src/OpenConext/EngineBlockFunctionalTestingBundle/Resources/config/services.yml
- src/OpenConext/EngineBlockFunctionalTestingBundle/Resources/views/Sso/consumeAssertion.html.twig
- tests/behat.yml
In order to test the SFO functionality in EB a gateway mock is needed.
Therefore a new endpoint is created in the functional testing bundle.
The results could be mocked in order to fake the possible SFO results.
`functional-testing/gateway/second-factor-only/single-sign-on`
> Create gateway SFO mock

- application/configs/application.ini
- docs/filter_commands.md
Some documentation is added to the added SFO logic in order to clarify the SFO/2fa configuration and validation options.
https://www.pivotaltracker.com/story/show/167320950
> Add Sfo/2fa documentation

- theme/material/stylesheets/error-page/modules/_error-title.sass
- theme/material/templates/modules/Authentication/View/Feedback/authorization-policy-violation.html.twig
The HR is now always shown on the error page
The institution message is styled to be non-bold and italic. This makes
it far more distinctive.
Finally only the 'error_authorization_policy_violation_info' is rendered
in a h2 element. The error_authorization_policy_violation_desc is no
longer wrapped in a h2.
[Discussion and more details in Pivotal](https://www.pivotaltracker.com/story/show/167451965)
> Improve PDP error screen styling

- .travis.yml
- library/EngineBlock/Application/DiContainer.php
- library/EngineBlock/Corto/Module/Bindings.php
- library/EngineBlock/Corto/Module/Service/Metadata.php
- library/EngineBlock/Corto/Module/Service/StepupAssertionConsumer.php
- library/EngineBlock/Corto/ProxyServer.php
- library/EngineBlock/Saml2/AuthnRequestFactory.php
- src/OpenConext/EngineBlockBundle/Stepup/StepupEntityFactory.php
- src/OpenConext/EngineBlockBundle/Stepup/StepupGatewayCallOutHelper.php
- src/OpenConext/EngineBlockBundle/Stepup/StepupGatewayLoaMapping.php
- src/OpenConext/EngineBlockBundle/Stepup/StepupIdentityProvider.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Controllers/StepupMockController.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Stepup.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/MockStepupGateway.php
- tests/unit/OpenConext/EngineBlockBundle/Stepup/StepupGatewayLoaMappingTest.php
According to the specs GW should only support redirect binding.
Post binding however is supported in GW but only to support ADFS and
actually this is not official. Therefore we change the binding to
redirect binding so the specs are met.
> Use redirect binding for sfo callout

- theme/material/templates/modules/Authentication/View/Index/index.html.twig
On the homepage the SFO term was still being used.
https://www.pivotaltracker.com/story/show/167864360/comments/205827824
> Fix the use of SFO on homepage

- src/OpenConext/EngineBlockBundle/Resources/config/routing/service_provider.yml
Only post should be allowed on the stepup authentication
acs endpoint.
https://www.pivotaltracker.com/story/show/168050611
> The stepup authentication acs should prevent GET

- theme/material/templates/modules/Authentication/View/Proxy/consent.html.twig
After moving the COIN properties from the SP/AbstractRole metadata entity, the termsOfServiceUrl property was not migrated in the twig template.
I've looked through the templates for other (mis)usages of coins in the twig templates. To no avail.
https://www.pivotaltracker.com/story/show/168565818
> Get termsOfServiceUrl from coins, not SP metadata entity

- theme/package-lock.json
To address:
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
| Dependency of │ jest [dev]                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ jest > jest-cli > @jest/core > @jest/reporters >             │
│               │ istanbul-api > istanbul-reports > handlebars                 │ …
```
> Bump handlebars to version 4.3.1

- theme/material/stylesheets/application/modules/_results.css.sass
The button, displayed when the edit previously chosen selection editor is activated. Would float to the left when the viewport size decreased to <= medium. Resulting in a not so elegantly rendered list of previously chosen IdP's.
As a solution. The button now remains floated to the right, but still retains his own row. This to ensure the IdP labels are able to use the maximum width of the row.
See: https://www.pivotaltracker.com/story/show/166694766
> Prevent WAYF c-button from floating left

- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Metadata.feature
This feature now only verifies the correct generation of the Engine
SP proxy metadata. The entity id, display name, and signature methods
are verified.
> Provide metadata Behat test

- composer.json
- composer.lock
- src/OpenConext/EngineBlock/Metadata/AttributeReleasePolicy.php
- src/OpenConext/EngineBlock/Metadata/Entity/AbstractRole.php
- src/OpenConext/EngineBlock/Metadata/Entity/Disassembler/CortoDisassembler.php
- src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/I18n.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Controllers/IdentityProviderController.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/EngineBlockContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Fixtures/ServiceRegistryFixture.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/AbstractMockEntityFactory.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/EntityRegistry.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/MockIdentityProvider.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/MockIdentityProviderFactory.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/MockStepupGateway.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Saml2/Compat/Container.php
The Composer PHP requirements where not set correctly yet. They still forced PHP 5. And that is not particularly useful when working with PHP 7.2
https://www.pivotaltracker.com/story/show/168775915
> Update Composer for improved PHP 7.2 support

- CHANGELOG.md
- README.md
- UPGRADING.md
With the EngineBlock 6.0 release, the different user facing documentation needed some updates. The release notes and upgrading notes received some background information about the 6.0 release. And from the readme, some outdated information was removed. And some important requirements have been added.
> Update changelog, readme, and the upgrading notes

- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MinkContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/FrontPage.feature
- theme/material/templates/modules/Authentication/View/Index/index.html.twig
The EB homepage advertised the possibility to open IdP metadata with the certificate of a specified SP. This feature was not longer supported in Engine. At least, I was not able to reproduce the behavior described for this feature.
There was not a lot to clean up, so only the homepage links have been removed.
See: https://www.pivotaltracker.com/story/show/168249086
> Remove idp metadata with sp-entity-id from home

- languages/messages.en.php
- languages/messages.nl.php
- languages/messages.pt.php
- src/OpenConext/EngineBlockBundle/Controller/FeedbackController.php
- src/OpenConext/EngineBlockBundle/EventListener/RedirectToFeedbackPageExceptionListener.php
- src/OpenConext/EngineBlockBundle/Resources/config/routing/feedback.yml
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/FrontPage.feature
- theme/material/javascripts/tests/visual-regression/error-page/ErrorPage.test.js
- theme/material/templates/modules/Authentication/View/Feedback/metadata-entity-not-found.html.twig
- theme/material/templates/modules/Authentication/View/Index/index.html.twig
The metadata actions where results can be modified using an SP entity ID would result in a generic 500 error. This is not terribly user-friendly. And this PR aims to make the error more clear to the end user by
providing a custom error message. This message is partly built up out of the exception message (which states what entity id was referenced) and a custom error message (translatable).
See: https://www.pivotaltracker.com/story/show/168258776
> Show custom error when metadata not found

- .travis.yml
- src/OpenConext/EngineBlock/Entities/Adapter/IdentityProviderEntity.php
- src/OpenConext/EngineBlock/Entities/Adapter/ServiceProviderEntity.php
- src/OpenConext/EngineBlock/Entities/Decorator/AbstractIdentityProvider.php
- src/OpenConext/EngineBlock/Entities/Decorator/AbstractServiceProvider.php
- src/OpenConext/EngineBlock/Entities/Decorator/IdentityProviderProxy.php
- src/OpenConext/EngineBlock/Entities/Decorator/IdentityProviderStepup.php
- src/OpenConext/EngineBlock/Entities/Decorator/ServiceProviderProxy.php
- src/OpenConext/EngineBlock/Entities/Decorator/ServiceProviderStepup.php
- src/OpenConext/EngineBlock/Entities/Factory/IdentityProviderFactory.php
- src/OpenConext/EngineBlock/Entities/Factory/ServiceProviderFactory.php
- src/OpenConext/EngineBlock/Entities/IdentityProviderEntityInterface.php
- src/OpenConext/EngineBlock/Entities/ServiceProviderEntityInterface.php
- src/OpenConext/EngineBlock/Metadata/Coins.php
- src/OpenConext/EngineBlock/Metadata/Entity/IdentityProvider.php
- src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
- src/OpenConext/EngineBlockBundle/Controller/MetadataController.php
- src/OpenConext/EngineBlockBundle/Controller/StepupController.php
- src/OpenConext/EngineBlockBundle/Metadata/MetadataFactory.php
- src/OpenConext/EngineBlockBundle/Metadata/Service/MetadataService.php
- src/OpenConext/EngineBlockBundle/Metadata/ValueObjects/IdentityProviderMetadataCollection.php
- src/OpenConext/EngineBlockBundle/Resources/config/routing/metadata.yml
- tests/integration/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssemblerTest.php
- tests/unit/OpenConext/EngineBlockBundle/Metadata/MetadataFactoryTest.php
- theme/material/templates/modules/Authentication/View/Metadata/idps.html.twig
A uniform entity factory which will return immutable entities is
required to enforce immutable state in entities. This will also prevent
a proliferation of factories to initiate different entities.
https://www.pivotaltracker.com/story/show/168980646
> Create metadata entity factory

- src/OpenConext/EngineBlockBundle/Controller/MetadataController.php
- src/OpenConext/EngineBlockBundle/Controller/StepupController.php
- src/OpenConext/EngineBlockBundle/Metadata/MetadataFactory.php
- src/OpenConext/EngineBlockBundle/Metadata/Service/MetadataService.php
- src/OpenConext/EngineBlockBundle/Metadata/ValueObjects/IdentityProviderMetadataCollection.php
- src/OpenConext/EngineBlockBundle/Resources/config/routing/metadata.yml
- tests/unit/OpenConext/EngineBlockBundle/Metadata/MetadataFactoryTest.php
- theme/material/templates/modules/Authentication/View/Metadata/idps.html.twig
The old metadata endpoints are updated in order to use the new
metadata endpoint generation logic with the help of twig.
https://www.pivotaltracker.com/story/show/168258709
The filtering of the proxy IdP's of an SP still needs to be implemented:
`library/EngineBlock/Corto/Module/Service/IdpsMetadata.php`
https://www.pivotaltracker.com/story/show/168979140
> Implement new metadata logic to old endpoints

- library/EngineBlock/Corto/Module/Service/AssertionConsumer.php
- library/EngineBlock/Corto/Module/Service/SingleSignOn.php
- library/EngineBlock/Corto/Module/Service/StepupAssertionConsumer.php
- library/EngineBlock/Corto/ProxyServer.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Stepup.feature
When configuring stepup functionality the trusted proxy wasn't taken into account. So only the configuration of the trusted proxy was used and not the configuration of the proxied SP.
This need to be cherrypicked to release 5.13 and included in release 6.1
https://www.pivotaltracker.com/story/show/169033643
> Add missing trusted proxy to stepup callout

- tests/unit/OpenConext/EngineBlock/Metadata/X509/KeyPairFactoryTest.php
Some test were still failing because the tests weren't properly
initialized after the phpunit upgrade.
> Fix keypair factory test after phpunit update

- src/OpenConext/EngineBlock/Metadata/Entity/IdentityProvider.php
- src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
- src/OpenConext/EngineBlock/Metadata/Factory/Adapter/IdentityProviderEntity.php
- src/OpenConext/EngineBlock/Metadata/Factory/Adapter/ServiceProviderEntity.php
- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/AbstractIdentityProvider.php
- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/AbstractServiceProvider.php
- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/IdentityProviderProxy.php
- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/IdentityProviderStepup.php
- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/ServiceProviderProxy.php
- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/ServiceProviderStepup.php
- src/OpenConext/EngineBlock/Metadata/Factory/Factory/IdentityProviderFactory.php
- src/OpenConext/EngineBlock/Metadata/Factory/Factory/ServiceProviderFactory.php
The EntityFactory architecture was created during a POC but
was lacking documentation. This is added to improve the
inline documentation of the architecture.
This is to address:
https://github.com/OpenConext/OpenConext-engineblock/pull/773#issuecomment-539434966
https://www.pivotaltracker.com/story/show/168980646
> Add missing documentation to EntityFactory

- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/IdentityProviderProxy.php
- src/OpenConext/EngineBlock/Metadata/MetadataRepository/IdpsMetadataRepository.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Metadata.feature
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/AbstractEntityTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Decorator/IdentityProviderProxyTest.php
- theme/material/templates/modules/Authentication/View/Metadata/idp.xml.twig
- theme/material/templates/modules/Authentication/View/Metadata/idps.xml.twig
There were some considerations raised during the review of the
refactoring of the ServiceReplacer. #786 
See: https://github.com/OpenConext/OpenConext-engineblock/pull/786
- slo service shouldn't be replaced when empty
- sso check was invalid
- repository EB check should be addressed later on after refactor
- re-enabled metadata feature test
- improved decorator test message
#788
Also the twig templates were unified for idp and idps so they would
become the same as the sp template.
The npm audit test is still failing but this should be addressed later on as it couldn't be fixed by running just `npm audit fix`.
> Address issue PR 787 788

- src/OpenConext/EngineBlock/Metadata/Factory/Adapter/IdentityProviderEntity.php
- src/OpenConext/EngineBlock/Metadata/Factory/Adapter/ServiceProviderEntity.php
- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/AbstractIdentityProvider.php
- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/AbstractServiceProvider.php
- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineBlockIdentityProviderInformation.php
- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineBlockIdentityProviderMetadata.php
- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineBlockServiceProviderInformation.php
- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineBlockServiceProviderMetadata.php
- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/ServiceProviderProxy.php
- src/OpenConext/EngineBlock/Metadata/Factory/Factory/IdentityProviderFactory.php
- src/OpenConext/EngineBlock/Metadata/Factory/Factory/ServiceProviderFactory.php
- src/OpenConext/EngineBlock/Metadata/Factory/IdentityProviderEntityInterface.php
- src/OpenConext/EngineBlock/Metadata/Factory/ServiceProviderEntityInterface.php
- src/OpenConext/EngineBlock/Metadata/MetadataRepository/IdpsMetadataRepository.php
- src/OpenConext/EngineBlock/Xml/MetadataProvider.php
- src/OpenConext/EngineBlockBundle/Controller/MetadataController.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Decorator/ServiceProviderProxyTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Factory/IdentityProviderFactoryTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Factory/ServiceProviderFactoryTest.php
The stepup metadata endpoint needed to be created. This change will make
sure that the entity is created.
Some minor adjustments where needed to allow optional fields.
Also the EB information is moved to a dedicated decorator as this is
won't be needed for all metadata endpoints.
https://www.pivotaltracker.com/story/show/169035362
I'll address adding decorator tests and the final implementation in a later PR
This is only a MVP to let the stepup metadata endpoint work.
> Create stepup metadata entity with factory

- .travis.yml
The version of the chromedriver needs to be updated because the version of chrome is updated. This resulted in a brower /driver mismatch. This fix will make sure that the required version gets selected as described in the chromedriver documentation
https://chromedriver.chromium.org/downloads/version-selection
> Update ChromeDriver to match Chrome version

- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineBlockIdentityProviderInformation.php
- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineBlockServiceProviderInformation.php
- tests/unit/OpenConext/EngineBlock/Xml/MetadataRendererTest.php
- theme/material/templates/modules/Authentication/View/Metadata/partial/ui_info.xml.twig
- theme/material/templates/modules/Authentication/View/Metadata/sp.xml.twig
The sp metadata service name and description values were not shown
if no attributes were set in the sp metadata twig template. This is changed now.
Requested in:
https://github.com/OpenConext/OpenConext-engineblock/pull/788#discussion_r337923991
> Show service info if no attributes are set (twig)

- .editorconfig
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Metadata.feature
The used keys are validated to be sure the EB keys are used
for signing and that the correct key is propagated as the one.
that should be used.
> Add test coverage for used keys

- library/EngineBlock/Corto/Filter/Command/AttributeAggregator.php
- src/OpenConext/EngineBlockBundle/AttributeAggregation/Dto/Request.php
- tests/library/EngineBlock/Test/Corto/Filter/Command/AttributeAggregatorTest.php
- tests/unit/OpenConext/EngineBlockBundle/AttributeAggregation/AttributeAggregationClientTest.php
- tests/unit/OpenConext/EngineBlockBundle/AttributeAggregation/Dto/RequestTest.php
The new Manage / SURF CRM attribute aggregator requires the IdP entityID for the query to Manage. Added it to `OpenConext\EngineBlockBundle\AttributeAggregation\Dto\Request` including test assertions.
> Added IDPentityID to the Attribute Aggregation request

- CHANGELOG.md
- composer.lock
This change will apply the countermeasures to harden against
CVE 2019-3465 and will effectively bump `robrichards/xmlseclibs` to
version 3.0.4
> Implement countermeasures against CVE 2019-3465

- theme/package-lock.json
Report from NPM audit:
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Denial of Service
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ jest [dev]
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ jest > jest-cli > @jest/core > @jest/reporters >
│               │ istanbul-api > istanbul-reports > handlebars
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1300
└───────────────┴──────────────────────────────────────────────────────────────┘
```
This …
> Upgrade handlebars to 4.5.1

- src/OpenConext/EngineBlock/Metadata/Entity/Disassembler/CortoDisassembler.php
- src/OpenConext/EngineBlock/Metadata/Factory/Factory/ServiceProviderFactory.php
This was first tagged to be removed in release 6.2, but we can rid ourselves of this dependency in 6.1. As EB should stop depending on these coins in 6.1
See: https://www.pivotaltracker.com/story/show/164925138
> Stop disasembling the Edugain publication settings

- library/EngineBlock/Corto/Adapter.php
- library/EngineBlock/Corto/ProxyServer.php
- src/OpenConext/EngineBlock/Metadata/Entity/AbstractRole.php
- src/OpenConext/EngineBlock/Metadata/Entity/IdentityProvider.php
- src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
- src/OpenConext/EngineBlock/Metadata/Factory/Adapter/IdentityProviderEntity.php
- src/OpenConext/EngineBlock/Metadata/Factory/Adapter/ServiceProviderEntity.php
- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/AbstractIdentityProvider.php
- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/AbstractServiceProvider.php
- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/IdentityProviderProxy.php
- src/OpenConext/EngineBlock/Metadata/Factory/Helper/EngineBlockServiceProviderMetadata.php
- src/OpenConext/EngineBlock/Metadata/Factory/IdentityProviderEntityInterface.php
- src/OpenConext/EngineBlock/Metadata/Factory/ServiceProviderEntityInterface.php
- src/OpenConext/EngineBlock/Metadata/MetadataRepository/Visitor/EngineBlockMetadataVisitor.php
- src/OpenConext/EngineBlock/Stepup/StepupEntityFactory.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/AbstractEntityTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Adapter/IdentityProviderEntityTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Adapter/ServiceProviderEntityTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Decorator/IdentityProviderProxyTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Factory/IdentityProviderFactoryTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Factory/ServiceProviderFactoryTest.php
Remove ResponseProcessingService logic from ORM entities and move this
to the ProxyServer class so legacy code only exists in the legacy
namespace as this is only used there to temporarily inject the
ConsentService used for internal binding.
https://www.pivotaltracker.com/story/show/169204880
> Remove ResponseProcessingService

- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/ServiceProviderStepup.php
- src/OpenConext/EngineBlock/Metadata/Factory/Helper/EngineBlockIdentityProviderMetadata.php
- src/OpenConext/EngineBlock/Metadata/Factory/Helper/EngineBlockServiceProviderMetadata.php
- src/OpenConext/EngineBlock/Xml/MetadataRenderer.php
- src/OpenConext/EngineBlockBundle/Resources/config/services.yml
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Helper/EngineBlockIdentityProviderMetadataTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Helper/EngineBlockServiceProviderMetadataTest.php
- tests/unit/OpenConext/EngineBlock/Xml/MetadataRendererTest.php
- theme/material/templates/modules/Authentication/View/Metadata/partial/organization.xml.twig
The translations weren't working for the organization block and
only english translations were used. This is fixed.
https://www.pivotaltracker.com/story/show/169257771
> Use correct language value in organization metadata

- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineBlockIdentityProvider.php
- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineBlockIdentityProviderInformation.php
- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineBlockServiceProvider.php
- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineBlockServiceProviderInformation.php
- src/OpenConext/EngineBlock/Metadata/Factory/Factory/IdentityProviderFactory.php
- src/OpenConext/EngineBlock/Metadata/Factory/Factory/ServiceProviderFactory.php
- src/OpenConext/EngineBlock/Metadata/Factory/Helper/IdentityProviderMetadataHelper.php
- src/OpenConext/EngineBlock/Metadata/Factory/Helper/ServiceProviderMetadataHelper.php
- src/OpenConext/EngineBlock/Xml/MetadataRenderer.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineBlockServiceProviderTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineblockIdentityProviderTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Factory/IdentityProviderFactoryTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Factory/ServiceProviderFactoryTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Helper/EngineBlockIdentityProviderMetadataTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Helper/EngineBlockServiceProviderMetadataTest.php
- tests/unit/OpenConext/EngineBlock/Xml/MetadataRendererTest.php
Some decorators and helpers naming didn't reflect the purpose of
the class properly.
https://www.pivotaltracker.com/story/show/169257771
> Adjust decorator naming to reflect purpose

- languages/messages.en.php
Some typos were on the no token feedback page. The typos are fixed and the missing link to the registration support page is also added.
https://www.pivotaltracker.com/n/projects/1425900/stories/169087364
> Fix typos for stepup no token

- composer.lock
The symfony/mime needed to be updated in order to mitigate:
- [CVE-2019-18888] Prevent argument injection in a MimeTypeGuesser
> Update symfony/mime dependency to pass build

- application/configs/application.ini
- library/EngineBlock/Application/DiContainer.php
- library/EngineBlock/Corto/Module/Service/StepupAssertionConsumer.php
- library/EngineBlock/Corto/Module/Services.php
- library/EngineBlock/Corto/ProxyServer.php
- src/OpenConext/EngineBlock/Exception/LoaNotFoundException.php
- src/OpenConext/EngineBlock/Metadata/Loa.php
- src/OpenConext/EngineBlock/Metadata/LoaRepository.php
- src/OpenConext/EngineBlockBundle/Resources/config/services.yml
- src/OpenConext/EngineBlockBundle/Stepup/StepupDecision.php
- src/OpenConext/EngineBlockBundle/Stepup/StepupGatewayCallOutHelper.php
- src/OpenConext/EngineBlockBundle/Stepup/StepupGatewayLoaMapping.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Controllers/StepupMockController.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/StepupContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Stepup.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/MockStepupGateway.php
- tests/unit/OpenConext/EngineBlock/Metadata/LoaRepositoryTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/LoaTest.php
- tests/unit/OpenConext/EngineBlockBundle/Stepup/StepupDecisionTest.php
- tests/unit/OpenConext/EngineBlockBundle/Stepup/StepupGatewayLoaMappingTest.php
The first five commits address task 1 and 3 of https://www.pivotaltracker.com/story/show/169392199
Some remarks:
1. A LoaRepository was created, tasked with loading a LoA based on its identifier.
1. The existing Mapping has been kept intact but its API changed slightly as it now returns LoA value objects instead of string identifiers.
The final commit addresses task 2
Here the actual verification is performed.
> Reconfigure LoA settings and verify received LoA

- composer.lock
This security release will protect us against the following vulnerabilities:
CVE-2019-18887: https://symfony.com/cve-2019-18887
CVE-2019-18888: https://symfony.com/cve-2019-18888
CVE-2019-18889: https://symfony.com/cve-2019-18889
> Upgrade Symfony to 3.4.35

- src/OpenConext/EngineBlock/Metadata/Factory/ValueObject/EngineBlockConfiguration.php
- src/OpenConext/EngineBlockBundle/Resources/config/services.yml
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MinkContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Metadata.feature
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineblockIdentityProviderInformationTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineblockServiceProviderInformationTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Factory/IdentityProviderFactoryTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Factory/ServiceProviderFactoryTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/ValueObject/EngineBlockConfigurationTest.php
- theme/material/templates/modules/Authentication/View/Metadata/partial/ui_info.xml.twig
When the IdPs metadata is rendered, Manage configured IdP logo URLs are used. Which are URIs, in contrary to the configured EB logo which is a relative path to the locally sourced logo.
To get both situations to render the logo URI correctly, the EB config object was updated. It now uses the EB hostname to create a logo URI the schema is set to HTTPS as we can assume TLS is used for Engine.
Finally the ui_info.xml.twig was updated to no longer prepend the schema and hostname.
A IdPs Metadata.feature scenario is used to verify that the logos are rendered without double hostnames.
https://www.pivotaltracker.com/story/show/169724838
> Prevent double schema and hostname on logo

- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/ProxiedIdentityProvider.php
- src/OpenConext/EngineBlock/Metadata/Factory/Factory/IdentityProviderFactory.php
- src/OpenConext/EngineBlock/Metadata/MetadataRepository/IdpsMetadataRepository.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineblockIdentityProviderTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Decorator/ProxiedIdentityProviderTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Factory/IdentityProviderFactoryTest.php
Created a new decorator: ProxiedIdentityProvider. This decorator is used in the IdPs metadata. As we want to display the specific IdP UIinfo, which in the previous setup was overridden by the EB values.
The new decorator uses the EB config to be able to use the EB certs, contact persons and sso location.
Tests where added and existing tests where modified.
The test_only_add_entity_id_hash_for_sso_service_url_if_not_eb_self was removed from the EBIdentityProviderTest. This test is now available in the ProxiedIdentityProviderTest.
https://www.pivotaltracker.com/story/show/169708158
> Separate IdP and EngineBlock decorators

- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Decorator/ProxiedIdentityProviderTest.php
The test was broken because a feature was merged back while tests
were broken.
> Fix broken ProxiedIdentityProvider test

- .travis.yml
- app/config/config_test.yml
- library/EngineBlock/Corto/Module/Service/StepupAssertionConsumer.php
- src/OpenConext/EngineBlock/Metadata/Loa.php
When setting a Loa on a Saml2 Assertion, the LOA VO was set on the AuthnContextClassRef.  In certain distro's this resulted in a false positive when asserting the `is_string` method. Because the VO had a `__toString` method.
The method is now removed and explicitly a string is given as parameter while maintaining the VO in Corto itself.
Some additional boyscouting was done:
* Travis branch regex fixed
* Enabled `strict_variables` on test to prevent a silent failure and thus removed magic
https://www.pivotaltracker.com/story/show/169976060
**This needs also to be cherrypicked to 6.0**
> Prevent invalid assertion when stepup LoA is set

- theme/material/templates/modules/Authentication/View/Index/index.html.twig
1. The text for the  `idps-metadata` was not fully correct. A part of the descriptive sentence was removed.
2. An excessive closing div element was removed.
3. The HTML has been reformatted.
See: https://www.pivotaltracker.com/story/show/170357520
> Update text and remove stray closing div tag

- .travis.yml
- theme/package-lock.json
- theme/package.json
We no longer use Chrome:stable on Travis xenial. This resolves the incompatibility between Chrome and the driver.
Finally Node SASS was updated. Even though the 'fix' mentioned above. It was still considered a production dependency by other packages..
> Repair ChromeDriver issue and resolve NodeSass issue

- theme/material/templates/modules/Authentication/View/Metadata/partial/ui_info.xml.twig
When keywords are present they are appended to the UI Info. Adding a functional test for this feature was no trivial task. Given the low complexity, this is something we can get away with. But @pablothedude you'll be the judge.
https://www.pivotaltracker.com/story/show/170401406
> Display keywords when present

- src/OpenConext/EngineBlock/Metadata/Factory/Helper/IdentityProviderMetadataHelper.php
- theme/material/templates/modules/Authentication/View/Metadata/idp.xml.twig
- theme/material/templates/modules/Authentication/View/Metadata/idps.xml.twig
- theme/material/templates/modules/Authentication/View/Metadata/partial/organization.xml.twig
Initially only SP's where treated with the Organization metadata (consisting of Name, DisplayName and an URL). Now also the IdP and IdPs metadata will display that data.
In addition, empty valued organization data will not be rendered as an empty xml element. But are omitted from the document.
https://www.pivotaltracker.com/story/show/170401380
> Show Organization data in IdP(s) metadata

- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/ProxiedIdentityProvider.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Decorator/ProxiedIdentityProviderTest.php
- theme/material/templates/modules/Authentication/View/Metadata/partial/ui_info.xml.twig
The displayname can always be set because name:en is a required field. Use this preference for the value:
* For EN: displayname:en, name:en
* For NL: displayname:nl, name:nl, name:en
Empty descriptions need not be displayed in the metadata.
Previously an empty tag was rendered, now the tag is omitted in its entirety. It was not a trivial task to verify this change in a functional test, but given the low complexity of this change it is a 'risk' I feel we can take.
https://www.pivotaltracker.com/story/show/170401452
> Metadata UI Info optimalisation

- src/OpenConext/EngineBlock/Xml/DocumentSigner.php
- tests/unit/OpenConext/EngineBlock/Xml/DocumentSignerTest.php
- tests/unit/OpenConext/EngineBlock/Xml/MetadataRendererTest.php
This makes explicit what is signed. Otherwise validation fails
in some implemenations.
Would normally take the first element, the root, but our templates
have comment with TOS in them. Could just remove this? And then
change code to look for firstChild.
> Add explicit reference to metadata xml signature.

- languages/messages.en.php
- languages/messages.nl.php
- languages/messages.pt.php
- theme/material/templates/modules/Authentication/View/Proxy/debug-idp-response.html.twig
They tend to easily get overlooked when all the way at the end of a
line. This will draw attention to the line, so the user can scroll
to the right if needed to get the "why" information.
> debug page: move icons to first column of table.

- application/configs/application.ini
- bin/composer/dump-required-ini-params.sh
**Description**
By default we now set the secure flag on the lang cookie. The in-config-file documentation was also updated to advertise the possible lang cookie settings available.
**Relates to**
Github issue: #831 
Pivotal ticket: https://www.pivotaltracker.com/story/show/171253291
> Change language cookie defaults

- composer.lock
- src/OpenConext/EngineBlockBundle/Authentication/Entity/ServiceProviderUuid.php
**Description:**
As of Doctrine version 2.9.2, a schema comparison change was introduced where index length changes where detected. This change caused the `service_provider_entity_id` index to be notified as a changed column. The correct column length was not set, resulting in recurring migration
creations. 
The problem was resolved by setting the expected index length explicitly on the index definition. 
**Relates to:**
Pivotal ticket: https://www.pivotaltracker.com/story/show/169118938
Introduction of issue: doctrine/dbal#3414
The golden tip: doctrine/dbal#3458
> Prevent recurring migration creation

- application/configs/application.ini
- bin/composer/dump-required-ini-params.sh
- library/EngineBlock/Application/DiContainer.php
- library/EngineBlock/Application/ErrorHandler.php
- library/EngineBlock/ApplicationSingleton.php
- library/EngineBlock/Corto/Adapter.php
- library/EngineBlock/Corto/Module/Bindings.php
- library/EngineBlock/Corto/ProxyServer.php
- src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/Debug.php
- tests/unit/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/DebugTest.php
- theme/material/templates/modules/Authentication/View/Proxy/form.html.twig
- theme/material/templates/modules/Default/View/Error/error.html.twig
It was not used, and provided minimal additional information. Removing it seemed logical.
Regarding the debug Twig extension, the var_dump function was removed. But the print_r and var_export functions have been left in place. As the debug route (used to test EB from the home page) still uses it to create debug info for the helpdesk mail.
https://www.pivotaltracker.com/story/show/164757722
> Disassemble the EB debug feature

- library/EngineBlock/Corto/Filter/Command/LogLogin.php
- library/EngineBlock/Corto/Module/Service/ProcessedAssertionConsumer.php
- library/EngineBlock/Corto/Module/Service/StepupAssertionConsumer.php
- library/EngineBlock/Saml2/ResponseAnnotationDecorator.php
- src/OpenConext/EngineBlock/Logger/AuthenticationLogger.php
- src/OpenConext/EngineBlockBridge/Logger/AuthenticationLoggerAdapter.php
- tests/unit/OpenConext/EngineBlock/Logger/AuthenticationLoggerTest.php
- tests/unit/OpenConext/EngineBlockBridge/Logger/AuthenticationLoggerAdapterTest.php
The original NameID and attained LOA were missing and are now added
to the 'login granted' log.
https://www.pivotaltracker.com/story/show/171404731
The node-sass security warning is fixed in https://github.com/OpenConext/OpenConext-engineblock/pull/847.
> Log original NameID and given LOA on successful login

- UPGRADING.md
- database/DoctrineMigrations/Version20191011132428.php
The response_processing_service_binding property is no longer used and
could be removed after the current release in order to support rolling
updates.
**Please validate before merging this back if we don't break old version because of Doctrine annotations!**
https://github.com/OpenConext/OpenConext-engineblock/pull/779
https://www.pivotaltracker.com/story/show/169178875
> Cleanup unused column

- docs/index.md
- docs/stepup_callout.md
- src/OpenConext/EngineBlock/Exception/MissingStepupEndpointConfigurationException.php
- src/OpenConext/EngineBlock/Stepup/StepupEndpoint.php
- tests/unit/OpenConext/EngineBlock/Stepup/StepupDecisionTest.php
- tests/unit/OpenConext/EngineBlock/Stepup/StepupEndpointTest.php
- tests/unit/OpenConext/EngineBlock/Stepup/StepupGatewayLoaMappingTest.php
Allow empty SFO key to support EB without SFO. This change will allow SFO configuration without a valid key needed in the configuration.
https://github.com/OpenConext/OpenConext-engineblock/issues/852
> Allow empty sfo key

- library/EngineBlock/Saml2/AuthnRequestFactory.php
- tests/library/EngineBlock/Test/Corto/ProxyServerTest.php
This allows the SP to communicate e.g. desired authentication parameters (strength) to the IdP in a generic way.
> If the SP provided a RequestedAuthnContext in the AuthnRequest, replicate this to the IdP

- library/EngineBlock/Corto/Filter/Command/LogLogin.php
- library/EngineBlock/Corto/Module/Service/ProcessedAssertionConsumer.php
- library/EngineBlock/Corto/Module/Service/StepupAssertionConsumer.php
- library/EngineBlock/Saml2/ResponseAnnotationDecorator.php
- src/OpenConext/EngineBlock/Logger/AuthenticationLogger.php
- src/OpenConext/EngineBlockBridge/Logger/AuthenticationLoggerAdapter.php
- tests/unit/OpenConext/EngineBlock/Logger/AuthenticationLoggerTest.php
- tests/unit/OpenConext/EngineBlockBridge/Logger/AuthenticationLoggerAdapterTest.php
The Loa was not logged when AM was being used. This change
logs the authncontextclassref instead which won't get lost during
deserializing the entiy when using AM.
https://www.pivotaltracker.com/story/show/171404731
> Log AuthnContextClassRef on successful login

- src/OpenConext/EngineBlock/Metadata/Coins.php
- src/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssembler.php
- src/OpenConext/EngineBlock/Metadata/Entity/IdentityProvider.php
- src/OpenConext/EngineBlock/Metadata/MfaEntity.php
- src/OpenConext/EngineBlock/Metadata/MfaEntityCollection.php
- tests/integration/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssemblerTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/MfaEntityCollectionTest.php
Added ability to read the `mfa_entities` data from the Manage metadata push.
For some reason Travis no longer reports back to Github on the build status. But the link below can be used for details about the QA build.
Note: Build breaks on security issue that should be resolved in a separate PR
See: https://www.pivotaltracker.com/story/show/172718043
See: https://travis-ci.org/github/OpenConext/OpenConext-engineblock/builds/704306933
> Assemble authcontextclassref combinations

- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/MfaAuthncontextclassref.feature
**Be aware this is build on top of #861 so this has te be merged back first!**
This will prove that for the unsolicted flow the authncontextclassref
is set when configured for the IdP SP combination.
https://www.pivotaltracker.com/story/show/172719874
> Test unsolicited presence of authcontextclassref

- app/config/config_test.yml
- src/OpenConext/EngineBlockBundle/Configuration/TestFeatureConfiguration.php
- src/OpenConext/EngineBlockBundle/Controller/Api/ConnectionsController.php
- tests/functional/OpenConext/EngineBlockBundle/Controller/Api/ConnectionsControllerTest.php
- tests/functional/OpenConext/EngineBlockBundle/Controller/Api/ConsentControllerTest.php
- tests/functional/OpenConext/EngineBlockBundle/Controller/Api/DeprovisionControllerTest.php
The previously skipped api tests failed on the inability to overwrite the `engineblock.features service`. This is disallowed for obvious
reasons, by using a test stand in for the feature configuration this problem can be resolved.
The test stand in has a setter to customize the contents of the features. Note that this version of the configuration should only be
used in testing scenarios.
See: https://www.pivotaltracker.com/story/show/174085599
> Enable skipped API tests

- library/EngineBlock/Corto/ProxyServer.php
- library/EngineBlock/Saml2/AuthnRequestAnnotationDecorator.php
- src/OpenConext/EngineBlock/Metadata/MfaEntityCollection.php
- src/OpenConext/EngineBlock/Metadata/MfaEntityFactory.php
- src/OpenConext/EngineBlock/Metadata/MfaEntityInterface.php
- src/OpenConext/EngineBlock/Metadata/TransparentMfaEntity.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockSpContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/MfaAuthnContextClassRef.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/MockServiceProvider.php
- tests/integration/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssemblerTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/MfaEntityFactoryTest.php
The `transparent_authn_context` MFA entity level is interpreted. And Engine will pass the RequestedAuthnContext transparantly to the targetted IdP.
The story goes into greater detail on why this feature was added.
https://www.pivotaltracker.com/story/show/173305494
> Implement the special case AuthnContextClassRef config option for transparent RequestedAuthnContext

- library/EngineBlock/Corto/Filter/Command/ValidateMfaAuthnContextClassRef.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/MfaAuthnContextClassRef.feature
- tests/library/EngineBlock/Test/Corto/Filter/Command/ValidateMfaAuthnContextClassRefTest.php
When the SP is configured to transparently pass its authentication context to and from the IdP.
See: https://www.pivotaltracker.com/story/show/173305494
> Do not apply ValidateMfaAuthnContextClassRef filter for transparent use case

- languages/messages.en.php
- languages/messages.nl.php
- languages/messages.pt.php
- library/EngineBlock/ApplicationSingleton.php
- library/EngineBlock/Corto/Module/Service/SingleSignOn.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/ClearErrorMessages.feature
- theme/material/stylesheets/error-page/modules/_feedback-info.sass
When no ids are connected to a proxied SP, previously the SP info of the proxy was displayed on the feedback info. This change will ensure both the SP and proxy SP are represented on the feedback info page.
@thijskh Two questions: 
1) Do you agree with the proposed labels in the feedback info table? __Proxy SP__ and _Proxy SP Name_ ? Shorter abbreviations might be more economical.
2) The columns might need reorganization to get optimal screen realestate for the proxy sp name. For now I'd like to show you this for verification.
See: https://www.pivotaltracker.com/story/show/174036058
> Show proxied SP and proxy in feedback info

- theme/material/templates/modules/Authentication/View/Proxy/consent-slidein-about.html.twig
The template tries to translate 'support_url' which is not in
languages/ (so results in just the string "support_url" as the url).
Probably 'openconext_support_url' was intended; this works.
> Fix use of nonexistent 'support_url'.

- UPGRADING.md
- application/configs/attributes.json
~The urn:oid:1.3.6.1.4.1.1466.115.121.1.15 attribute was previously released by default when the SHO was in the ARP. This oid is not valid and was added for historic reasons. It's not clear which SP's still rely on this attribute. So by default the attribute is not released by EB, but can be enabled using the 'eb.arp_remove_non_conforming_sho_attribute' feature flag.~
Simply removing the alias from the config was a more pragmatic solution. Federations relying on the alias can manually put it back if need be.
See: https://www.pivotaltracker.com/story/show/164237578
> Remove non conforming SHO oid from config

- src/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssembler.php
- src/OpenConext/EngineBlock/Metadata/Factory/Adapter/IdentityProviderEntity.php
- src/OpenConext/EngineBlock/Metadata/Factory/Adapter/ServiceProviderEntity.php
- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/AbstractIdentityProvider.php
- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/AbstractServiceProvider.php
- src/OpenConext/EngineBlock/Metadata/Factory/Helper/IdentityProviderMetadataHelper.php
- src/OpenConext/EngineBlock/Metadata/Factory/Helper/ServiceProviderMetadataHelper.php
- src/OpenConext/EngineBlock/Metadata/Factory/IdentityProviderEntityInterface.php
- src/OpenConext/EngineBlock/Metadata/Factory/ServiceProviderEntityInterface.php
- src/OpenConext/EngineBlock/Metadata/Organization.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/AbstractEntityTest.php
- theme/material/templates/modules/Authentication/View/Metadata/partial/organization.xml.twig
1. Organization data is now always assembled in the PushMetadataAssembler
2. Still only displayed on the metadata field when all data is complete.
3. An additional bugfix was applied, where the displayname was never rendered
https://www.pivotaltracker.com/story/show/170744290
> Move metadata organization business rules away from metadata assembler

- library/EngineBlock/Corto/Module/Bindings.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/SpProxy.feature
When the trusted proxy does not sing its requests, we error out of the single sing on flow. The error is generic and has a non descriptive error message is raised.
See https://www.pivotaltracker.com/story/show/153995599
> Add trusted proxy signing verification

- theme/package-lock.json
- theme/package.json
Amonst the dot-prop upgrade, the other dependencies where also upgraded. 
This upgrade prevents:
CVE-2020-8116 high severity
Vulnerable versions: < 4.2.1
> Upgrade dot-prop to version 5.2.0

- library/EngineBlock/Corto/Module/Bindings.php
- library/EngineBlock/Corto/Module/Service/AssertionConsumer.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/IsPassive.feature
These NoPassive status responses are sent by the IdP who is not
able/allowed to process a Passive authentication.
Previously we would show a custom error page. But on this occasion it's
better to let the SP decide how to proceed in this situation.
See: https://www.pivotaltracker.com/story/show/164238276
Closes: https://github.com/OpenConext/OpenConext-engineblock/issues/39
> Send NoPassive status response back to issuing SP

- app/AppKernel.php
In deploy a different cache and log path are used. When performing a
clean install this will result in errors because an unknown path is
being used. This change will resolve that.
> Change symfony cache path to reflect deploy path

- library/EngineBlock/ApplicationSingleton.php
- library/EngineBlock/Corto/Model/Response/Cache.php
- library/EngineBlock/Corto/Module/Bindings.php
The Issuer object was stored in the CachedResponses session. Causing problems with successive use of the
CachedResponses data which is expected to be a string representation of the SP/IdP entityID.
https://www.pivotaltracker.com/story/show/174627328
> Store entityId of issuer, not the value object

- library/EngineBlock/Corto/Module/Service/AssertionConsumer.php
The no passive decision was moved back up into the ACS process method.
This prevents the signature method check to fail, causing the display of
a different error page.
https://www.pivotaltracker.com/story/show/164238276/comments/217704651
> Move NoPassive response processing up in the ACS proces

- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineBlockIdentityProvider.php
- src/OpenConext/EngineBlock/Metadata/Factory/Decorator/ProxiedIdentityProvider.php
- src/OpenConext/EngineBlock/Metadata/Factory/Factory/IdentityProviderFactory.php
- src/OpenConext/EngineBlock/Metadata/MetadataRepository/IdpsMetadataRepository.php
- src/OpenConext/EngineBlock/Metadata/X509/KeyPairFactory.php
- src/OpenConext/EngineBlock/Xml/MetadataProvider.php
- src/OpenConext/EngineBlock/Xml/MetadataRenderer.php
- src/OpenConext/EngineBlockBundle/Controller/MetadataController.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Decorator/EngineblockIdentityProviderTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Decorator/ProxiedIdentityProviderTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Factory/IdentityProviderFactoryTest.php
The rollover key was not present in the IdP metadata of EngineBlock. This is taken care of in this commit.
An additional challenge arose: The Key Id is not always explicitly defined when opening the IdP metadata, in fact it is only used in roll-over scenarios. Setting the default by default caused the SSO URl to be filled with key:default. Where this is not a requirement.
https://www.pivotaltracker.com/story/show/174672018
> Print the key-id in the SSO locations of the IdP metadata

- theme/package-lock.json
- theme/package.json
This was a two step process.
1. npm upgrade (good practice to update packages regularly)
2. manually resolve the jpeg-js package to version 0.4.0
Details on why jpeg-js needed to be upgraded:
CVE-2020-8175
moderate severity
Vulnerable versions: < 0.4.0
Patched version: 0.4.0
Uncontrolled resource consumption in jpeg-js before 0.4.0 may allow
attacker to launch denial of service attacks using specially a crafted
JPEG image.
> Upgrade jpeg-js to v0.4.0

- library/EngineBlock/Corto/Filter/Command/ValidateMfaAuthnContextClassRef.php
- library/EngineBlock/Corto/Filter/Input.php
- library/EngineBlock/Corto/ProxyServer.php
- tests/library/EngineBlock/Test/Corto/Filter/Command/ValidateMfaAuthnContextClassRefTest.php
So this also works when the SP in question is behind a trusted proxy.
> Whether MFA AuthnContext must be added should be based on original SP

- CHANGELOG.md
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/MfaAuthnContextClassRef.feature
This adds a test for the recently closed #893. I promised to test this feature, and writing a Behat scenario proved least difficult and should yield a good regression measure.
> Test whether MFA AuthnContext must be added should be based on original SP

- .github/workflows/test-integration.yml
- app/config/config_test.yml
- build.xml
- docs/js_testing.md
- src/OpenConext/EngineBlockFunctionalTestingBundle/Controllers/ConsentController.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Helper/TestEntitySeeder.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Resources/languages/messages.en.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Resources/languages/messages.nl.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Resources/languages/messages.pt.php
The low hanging fruit for overriding the default consent functional testing controller has been updated here.
What remains to do is setting the attributes and more importantly the attribute sources.
The new query parameters available on this endpoint can be found in the js-testing readme file.
NameID overriding is a somewhat strange override. When you use the `name-id` query param, the name id is set to be `unspecified`. Even if you use the `persistent-name-id` feature flag.
> Improve consent test endpoint

- library/EngineBlock/Corto/Module/Bindings.php
- library/EngineBlock/Exception/UnknownServiceProvider.php
- src/OpenConext/EngineBlockBundle/EventListener/RedirectToFeedbackPageExceptionListener.php
This is actually a bugfix. Sending an AuthnRequest to EB >= 6.3.1 that has no `Destination` parameter (which is indeed optional in the spec):
```xml
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
ID="CORTO7b58fe48a7c62ea17e02b50a68b0dfa021d69280"
Version="2.0"
IssueInstant="2020-09-22T14:43:47Z"
>
<saml:Issuer>http://example.org</saml:Issuer>
</samlp:AuthnRequest>
```
Would yield a fatal error:
```
Argument 2 passed to EngineBlock_Corto_Module_Bindings::_verifyKnownSP() must be of the type string, null given, called in /opt/openconext/OpenConext-engineblock-6.3.4/library/EngineBlock/Corto/Module/Bindings.php on line 188
```
Type `string` was added to the `$destination` parameter of `_verifyKnownSP()` in 6.3.1. …
> Clean up unused usage of authnrequest destination

- theme/base/javascripts/wayf.js
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/wayf_content.html.twig
This change adds support for the Skeune WAYF design, which is WIP to
begin with. So the change to the wayf.js must be considered temporary
code.
In order to continue to the IdP, an entity Id must be set on the form.
This form consists of hidden form fields (request id, entityId and so
forth) the form is then submitted.
The other code is only accessible when using the old theme.
> Put temporary code in place to make WAYF function

- theme/base/stylesheets/pages/wayf.scss
- theme/base/stylesheets/shared.scss
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/search.html.twig
- theme/cypress/integration/skeune/wayf/a11y.spec.js
- theme/cypress/support/commands.js
- theme/skeune/translations/messages.en.php
- theme/skeune/translations/messages.nl.php
- theme/skeune/translations/messages.pt.php
Added a new command to get rid of the symfony debugbar during testing.
- There was a contrast issue with the edit button, because the font wasn't large enough.  Increased the font size to resolve.
- There was an issue with an extra open strong tag.  Removing it fixed that.
- The search form lacked a submit button.  Fixed that while keeping the styling the same.  Also added an aria-role as per best practice.
- The focus styles for the footer didn't show clearly as it was blue on blue.  Changed those to white.
- Buttons lacked a pointer when hovering above them, added those generically.
- The Idp lacked a type for it's button: added that.  It also has a button nested in a link.  So added a comment to disable event bubbling on the button to avoid accidentally triggering the link.
> Add automatic a11y test and fix problems

- library/EngineBlock/Corto/Filter/Abstract.php
Should fix:
Oct  3 13:52:09 sv1810952 EBLOG[1527]: [2020-10-03 13:52:09] app.ERROR: Call to a member function getValue() on null {"session_id":"o6v872d3nh68rrlt1tn40jrv2g","request_id":"5f7865e9c3ebe"} {"exception":"[object] (Error(code: 0): Call to a member function getValue() on null at /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.3.5/library/EngineBlock/Corto/Filter/Abstract.php:75)"}
Although I haven't tested this yet..
> Response without NameID is valid behaviour

- src/OpenConext/EngineBlock/Xml/DocumentSigner.php
- tests/unit/OpenConext/EngineBlock/Xml/DocumentSignerTest.php
This fixes parsing of our generated XML with some remote entities, notably ADFS. This was present in the old metadata (pre-twig) and is also present in e.g. the signed Responses we send and in metadata generated by other products.
XML before:
```xml
<ds:Reference URI="#EB...">
<ds:Transforms>
<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
</ds:Transforms>
<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
<ds:DigestValue>...</ds:DigestValue>
</ds:Reference>
```
XML after:
```xml
<ds:Reference URI="#EB...">
<ds:Transforms>
<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
</ds:Transforms>
<ds:DigestMethod …
```
> Also add c14n method to the reference transforms in XML metadata.

- src/OpenConext/EngineBlockFunctionalTestingBundle/Controllers/ConsentController.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Resources/config/routing.yml
- theme/base/stylesheets/application.scss
- theme/base/stylesheets/pages/form.scss
- theme/base/stylesheets/shared.scss
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Shared/header.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/form.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/wayf_content.html.twig
- theme/skeune/stylesheets/application.scss
This is the form EB pages use to send back SAML messages (supports both SAMLResponse and SAMLRequest) but I only know of it using it to send back SAMLResponses to the SP.
I added a functional testing endpoint to render the form. In order to prevent the infinite loop and test other stuff:
1. Manually remove the auto submit code from the body tag of the twig template to prevent a submit loop
2. You can test no-js capabilities by disabling JS in your browser (duh)
See: `https://engine.vm.openconext.org/functional-testing/send`
Mobile:
Larger browser screen:
No-JS
I'm aware the no-js styling is lacking in theming, and does not have good a11y feature (like outline on focus). For now I'd like to await a first review of the basic styling.
> Style the redirect form

- theme/base/javascripts/application.js
- theme/base/javascripts/consent.js
- theme/base/javascripts/consent/addA11ySupport.js
- theme/base/javascripts/consent/focusAcceptButton.js
- theme/base/javascripts/page.js
- theme/base/stylesheets/pages/consent.scss
- theme/base/templates/layouts/scripts/default.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/ctas.html.twig
- theme/base/templates/modules/Default/Partials/button.html.twig
- theme/openconext/javascripts/application.js
- theme/openconext/javascripts/consent.js
- theme/openconext/javascripts/consent/initAttributesToggle.js
- theme/openconext/javascripts/consent/initSlideIns.js
- theme/openconext/javascripts/consent/initTooltips.js
- theme/openconext/javascripts/hideNoScript.js
Made a generic initializePage function.
Split up all js functions in seperate files for the consent page, put those in a consent subfolder.
Created a initializeConsent function for both openconext / base (skeune) which contains all relevant JS with updated selectors.
Removed the inline JS from default.html.twig.
Imported the JS for consent in application.js for both openconext / base (skeune).
> Refactor JS code for consent page

- database/DoctrineMigrations/Version20191011132428.php
- database/DoctrineMigrations/Version20200226103409.php
- database/DoctrineMigrations/Version20201005161700.php
This PR consists of a migration that drops the last database table related eduGAIN references.
The commit warns: `To be released post EngineBlock 6.2 for rollbackability` Now that we are in the 6.3 tier, this can be merged now.
> Remove the remaining eduGAIN metadafields

- src/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssembler.php
The assembly of the organization value objects would read possibly
undefined properties from the metadata 'connections' stdClass.
This would result in notices in the log, and even errors. As these
metadata values are not required, a safeguard was added to the import
logic
See point 3 of:
https://github.com/OpenConext/OpenConext-engineblock/issues/920#issue-714118630
> Prevent undefined access in Assembler

- theme/material/templates/modules/Authentication/View/Metadata/partial/organization.xml.twig
As per Slack-discussion, the recent changes in https://github.com/OpenConext/OpenConext-engineblock/pull/878 cause a schema violation, because a specific order of elements is demanded.
Also see par [2.3.2.1](https://docs.oasis-open.org/security/saml/v2.0/saml-metadata-2.0-os.pdf) of the specs
> Fix sequence / schema violation

- app/config/parameters.yml.dist
- docs/js_testing.md
- library/EngineBlock/Application/DiContainer.php
- library/EngineBlock/Corto/Module/Service/SingleSignOn.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Controllers/WayfController.php
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/remainingIdps.html.twig
- theme/cypress/integration/skeune/wayf/WayfGeneralBehaviour.js
This feature flag toggles the default IdP banner on the WAYF in the preselection twig template.
By default this feature is enabled and can be set in the parameters.yml
> Introduce display_default_idp_banner_on_wayf feature flag

- theme/base/javascripts/wayf/noAccess/handleCancelNoAccess.js
- theme/base/javascripts/wayf/search/hideIdpsWhenCutoffNoSearch.js
- theme/base/javascripts/wayf/search/searchAndSortIdps.js
- theme/base/javascripts/wayf/search/showFoundIdpsWhenCutoff.js
- theme/base/stylesheets/pages/wayf.scss
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp/idpList.html.twig
- theme/cypress/integration/skeune/wayf/WayfGeneralBehaviour.js
Support the cutoff point feature flag.  This means hiding all remaining Idps on the page when there would be more, unless the user is searching.
> Support cutoff point feature flag

- theme/base/javascripts/consent/addA11ySupport.js
- theme/base/javascripts/utility/handleAriaPressed.js
- theme/base/javascripts/wayf/handleDeleteDisable.js
- theme/base/javascripts/wayf/mouseBehaviour.js
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/preselection.html.twig
Refactored it to be more general in consent, then added it in the WAYF.
> Add accessibility support for aria-pressed attribute on labels in the WAYF

- app/config/parameters.yml.dist
- docs/js_testing.md
- library/EngineBlock/Application/DiContainer.php
- library/EngineBlock/Corto/Module/Service/SingleSignOn.php
- src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/Wayf.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Controllers/WayfController.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Helper/TestEntitySeeder.php
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp/idp.html.twig
- theme/cypress/integration/skeune/wayf/WayfGeneralBehaviour.js
Allow configuration of the default IdP entity ID. This id is then used to mark the default IdP in the wayf list. Or at least to easily select it when the link in the banner is clicked.
To test this feature, use this qurey param in the function testing wayf
https://engine.vm.openconext.org/functional-testing/wayf?defaultIdpEntityId=https://example.com/entityId/3
> Add the default IdP EntityID configuration parameter

- theme/cypress/support/commands.js
Ensure all custom cypress commands can be used by other themes as well
> Ensure all cypress commands are theme agnostic

- src/OpenConext/EngineBlock/Metadata/ConsentSettings.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Consent.feature
- tests/unit/OpenConext/EngineBlock/Metadata/ConsentSettingsTest.php
- theme/cypress/integration/skeune/consent/consent.skeune.spec.js
By default when no idp/sp configuration is available the consent style
is set to be minimal.
> Change default isMinimalConsent behavior

- theme/base/javascripts/wayf/search/toggleDefaultIdPLinkVisibility.js
- theme/base/javascripts/wayf/searchBehaviour.js
- theme/cypress/integration/skeune/wayf/WayfGeneralBehaviour.js
When searching, the default IdP should be hidden. When the search bar is
empty, the idp banner should re-appear.
> Show and hide default IdP when searching

- src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/Wayf.php
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp/idp.html.twig
- web/app.php
The test WAYF did not function as intened. It did not show the previously selected IdP's as the cookie could not be used by the Twig Function:
1. The TWIG function compared the EnittyID of the IDP in a case sensitive manner (good thing) but the EntityId was lower cased in the Twig template (no bueno).
2. The cookie for previous selection was no longer indexed on entityID, making the matching logic in the Twig function impossible. This was also fixed by re-indexing the values once they where loaded in the function.
> Repair the previously selected feature in test

- docker/php-fpm/Dockerfile-php72
- docker/php-fpm/Dockerfile-php74
Download the composer 1 installer instead of using the latest and greatest. This should enable the dependencies to install without error on the GitHub Actions pipelines.
> Use Composer 1 while not Composer 2 compatible

- library/EngineBlock/Corto/Module/Service/ContinueToIdp.php
Oct 30 19:14:34 sv2010010 EBLOG-FIN[21532]: [2020-10-30 19:14:34] app.ERROR: Undefined index: idp [/apps/installation/OpenConext-engineblock/engine.broker.fin.rijksdienst.nl/OpenConext-engineblock-6.3.6/library/EngineBlock/Corto/Module/Service/ContinueToIdp.php:67]
This should never happen in the first place, but it could happen if a session is lost.. The undefined index error can be prevented
> Fix undefined index error

- theme/base/stylesheets/pages/consent.scss
The whitespace needed to be a bit more roomy. By setting a margin-right on the title, this should not interfere with other viewports as they render title and text beneath each other.
> Increase whitespace between consent title and text

- src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/Wayf.php
In the previous situation the previously selected IdPs where only shown in the shortlist. This is not very intuitive when clicking the 'select a different IdP' link from the short list. As the IdPs you used before are no longer available for selection.
> Leave the previously selected IdPs in the 'select another IdP' list

- theme/base/javascripts/wayf/search/toggleSearchAndResetButton.js
- theme/base/stylesheets/pages/wayf.scss
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/search.html.twig
And hide the reset button visually. When typing, show the reset button (remove the class).
The background has also been removed from the poirot element. This prevents setting extra logic to color with the parent elements focus style. E.g. when the search bar is focussed, you want the poirot to be focussed too
> Show search icon on page load

- library/EngineBlock/Application/DiContainer.php
- library/EngineBlock/Corto/Module/Service/SingleSignOn.php
Only show default IdP when available and when the feature is enabled. Testing this feature showed an error in the way this feature was created. The di container checked for the existence of a config setting, and not for the existence of a the wayf parameter. This was also fixed in this commit
> Only show default IdP when available

- theme/base/stylesheets/pages/wayf.scss
By removing the justification layout directive from the stylesheet, the texts are now aligned similarly between the connected and disconnected IdPs.
See screenshots for a concept of what I'm on about.
*Full width browser*
*Mobile*
PS. Only consider the last commit of this PR (this branch was based on the fix cypress tests PR)
> Align IdP titles between connected and disconnected variaties

- library/EngineBlock/Corto/Module/Service/SingleSignOn.php
- src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/ConnectedIdps.php
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/remainingIdps.html.twig
- theme/skeune/translations/messages.en.php
- theme/skeune/translations/messages.nl.php
- theme/skeune/translations/messages.pt.php
Only show the defautl IdP when it is connected. This makes more sense from an user perspective. 
And we now show the actual IdP title instead of always rendering eduID as the default IdP name.
> Only show default idp when connected

- theme/base/stylesheets/pages/consent.scss
- theme/base/templates/modules/Authentication/View/Proxy/consent.html.twig
Making this a micro commit to avoid merge conflicts down the road.
To be clear: 
- moved the h2 in the consent__content div
- ensured that all h2's one level down from the consent container will have the same styling
- added a consent__content-body div
- moved styling from consent__content to consent__content-body
> Isolate current consent content

- theme/base/stylesheets/pages/wayf.scss
You can test this by using the following code to replace line 14 in idp.html.twig & and using the logo that triggered the bug report ![conext_logo](https://user-images.githubusercontent.com/4058016/99978217-f482d200-2da5-11eb-9451-8aaff67b679c.png)
(or something similar):
```
{% if loop.index == 1 %}
{% set logoUrl = '/images/temp/conext_logo.png' %}
{% else %}
{% set logoUrl = idp.logo %}
{% endif %}
```
> Ensure logo height never grows too big

- languages/messages.en.php
- languages/messages.nl.php
- languages/messages.pt.php
- src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/AbstractEntityTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Adapter/ServiceProviderEntityTest.php
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/disclaimerList.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/consent.html.twig
The following fallback sequence was implemented.
Show:
1. Organization Display Name
2. Organization Name when 1 is not available
3. 'Unknown' when 1 and 2 are not available
> Use organization name for SP in disclaimer text

- app/config/parameters.yml.dist
- docker/php-fpm/Dockerfile-php72
- docker/php-fpm/Dockerfile-php74
- docker/php-fpm/app.ini
The fixes were found by @pablothedude  in https://github.com/OpenConext/OpenConext-engineblock/pull/992.  Porting them here so I can simply rebase all open PRs after applying the fix.
> Fix bugs in the CI

- theme/base/stylesheets/pages/consent.scss
I could not find a reason as to why they appear to be slightly misaligned, but did confirm it was only with the first four.
> Fix vertical alignment of the first four attribute values

- theme/base/stylesheets/pages/consent/idpRow.scss
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/idpRow.html.twig
On Safari there are two bugs:
- the label for mobile throws off the alignment of the paragraph under certain fringe conditions
- on MacOS Big Sur 14.0.1 the text-alignment of the labels is left instead of the set value of right.
Aside from that the label for the second row is in blue rather than in dark gray.
> Ensure content of idprow is aligned correctly on Safari & accross source-type

- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/consentContent.html.twig
The name used in the h2 did not fit with the designs.  As such when the same name was used in the disclaimer list, it "came out of nowhere".
> Use organizationName in consent h2 title

- theme/base/stylesheets/classes.scss
- theme/base/templates/modules/Authentication/View/Proxy/form.html.twig
The spinner on the form page serves no purpose when the user has JS disabled.  As such, it and the associated text are now hidden when that is the case.
> Hide spinner & associated text on nojs for form

- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/defaultAttribute.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/engineBlockAttribute.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/tooltip.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/attributes.html.twig
- theme/cypress/integration/skeune/consent/consent.general.spec.js
- theme/cypress/integration/skeune/consent/consent.keyboard.spec.js
- theme/cypress/integration/skeune/consent/consent.mouse.spec.js
Given that there are potentially different attribute-lists, we need to ensure that the id for a tooltip is unique.  In this PR i've added the attributeSource (SP) name as part of the id, so that each attribute source is guaranteed to have a unique id.
> Ensure the id of a tooltip is unique

- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/disclaimerList.html.twig
- theme/skeune/translations/messages.en.php
- theme/skeune/translations/messages.nl.php
- theme/skeune/translations/messages.pt.php
As always use orgNoun.
Get rid of "institution part" and replace with sp Name
Correct faulty Dutch translation
> Adjust text for security disclaimer

- theme/base/javascripts/wayf/deleteDisable/setConnectability.js
- theme/base/javascripts/wayf/handleClickingDisabledIdp.js
- theme/base/javascripts/wayf/noAccess/attachClickHandlerToRequestButton.js
- theme/base/stylesheets/pages/wayf/noAccess.scss
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp/idp.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/noAccess/ctas.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/noAccess/helpdesk.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/noAccess/noAccess.html.twig
- theme/skeune/translations/messages.en.php
- theme/skeune/translations/messages.nl.php
- theme/skeune/translations/messages.pt.php
When an idp cannot request access a different form needs to be shown when clicking the no-access button.  This PR fixes that.
> Differentiate noAccess form when unconnectable

- theme/base/stylesheets/pages/wayf/idpList.scss
Safari took the width of the submit button into account after a repaint (it shouldn't as visually hidden).  Fixed it and added a comment for clarification.
> Fix Safari repaint bug

- src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/ConnectedIdps.php
- theme/base/javascripts/wayf/utility/sortAndReindex.js
- theme/base/javascripts/wayf/utility/sortIdpList.js
- theme/base/javascripts/wayf/utility/sortIdpMethods.js
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/preselection.html.twig
The previously selected idps should be ordered descending by the amount of times they were used to log in before.
> Sort previously selected idps by count

- src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
The algorithm for specifying a name is now:
If OrgDisplayName:TAAL is set: OrgDisplayname:TAAL;
Elseif OrgName:TAAL is set: OrgName:TAAL
Elseif OrgDisplayName:en is set: OrgDisplayname:en
Elseif OrgName:en is set: OrgName:en
Else "Onbekend"
> Use english name as backup of locale-specific name

- theme/base/stylesheets/pages/consent.scss
To make the screen a tad more good-looking (almost impossible, i know), this PR adds a margin to the bottom of the consent screen.  That way, we can see it's lovely blue bottom.
> Add a bit of margin to the bottom of the consent screen

- theme/base/stylesheets/pages/wayf/idpList.scss
- theme/base/stylesheets/pages/wayf/previousSelection.scss
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/preselection.html.twig
- theme/cypress/support/commands.js
- remove double focus for edit button on wayf
- hide deleteDisable button (and it's outline) when there is no content
- enlarge touch surface of delete button
> Resolve smaller a11y bugs

- theme/base/stylesheets/pages/wayf/remainingIdps.scss
On tablets the design sometimes uses elements of the mobile design.  For the informational that means the icon isn't shown entirely as the padding is the mobile one and the text is single-line.  
This pr solves that by adding a min-height to the informational.
> Ensure informational is big enough for icon

- theme/base/stylesheets/front-page/base/_page.sass
On the index page, links don't break nicely on mobile.  This pr resolves that in a generic way
> Ensure links don't overflow on mobile

- theme/base/stylesheets/pages/consent/attribute.scss
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/defaultAttribute.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/engineBlockAttribute.html.twig
The idea here is to allow enough room for at least a 40-character attribute value, both on all screen sizes.  The reason being that we want to ensure that the identifier fits 95% of the time.  Because identifiers tend to be persistent nameids, which are a sh1-hash, that means 40 characters.
> Increase room for tooltipless attribute values

- src/OpenConext/EngineBlockFunctionalTestingBundle/Controllers/WayfController.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Helper/TestEntitySeeder.php
- theme/README.md
- theme/base/javascripts/utility/hideElement.js
- theme/base/javascripts/utility/showElement.js
- theme/base/javascripts/wayf/idpFocus/arrowDown.js
- theme/base/javascripts/wayf/idpFocus/arrowUp.js
- theme/base/javascripts/wayf/idpFocus/focusOnNextIdp.js
- theme/base/javascripts/wayf/idpFocus/focusOnPreviousIdp.js
- theme/base/javascripts/wayf/keyboardBehaviour.js
- theme/base/javascripts/wayf/search/toggleSearchAndResetButton.js
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp/idpList.html.twig
- theme/cypress/integration/skeune/wayf/wayf.general.spec.js
- The sort works once searching has commenced, but not on load.  Fixed that in this PR.
- Also added a way to test this & the sort with more realistic data.
- The search navigation by arrow didn't work with the new sorting so fixed that.
- Noticed the submit button was hidden when the reset button was visible, so ensured it stays accessible to aural UI.
> Sort unconnected idps after connected idps on load

- theme/openconext/stylesheets/application/modules/_redirect.css.sass
- theme/openconext/templates/modules/Authentication/View/Proxy/form.html.twig
The page itself no longer had the right styling and the spinner was in a different place
Before:
After: normal
> Restore redirect page for openConext theme

- theme/base/stylesheets/pages/consent/idpRow.scss
Fix the label in the paragraph of the idpRow getting focus on mobile when it's empty (aka, when the input is unchecked).  Issue reported by @MKodde [here](https://github.com/OpenConext/OpenConext-engineblock/pull/1031#issuecomment-747327699)
> Hide label in idprow when unchecked

- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/disclaimerList.html.twig
As reported by Thijs, there is a stray space after "heeft deze informatie nodig om te kunnen werken" in the first item of the disclaimerlist.  It was caused by formatting of the code.  This PR removes that.
> Remove stray space from consent screen disclaimer

- .github/workflows/test-integration.yml
- app/config/config_test.yml
- app/config/functional_testing.yml.dist
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Consent.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/EngineBlockContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Debug.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/SpProxy.feature
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/list.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/ctas.html.twig
- theme/base/templates/modules/Default/Partials/button.html.twig
- theme/scripts/build.js
The aim of this PR is to run the acceptance tests against the Skeune theme in al its glory. Including translations, and theme specific settings and optimizations.
This allows us to create new tests carelessly in the future. As the new theme should become the new default in the near future.
> Run the Behat acceptance tests against the skeune theme

- src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
- tests/unit/OpenConext/EngineBlock/Metadata/Entity/ServiceProviderTest.php
As one of the [feedback items](https://wiki.surfnet.nl/display/coininfra/Bevindingen+december+2020) it was requested that we [change the algorithm for the SP displayname](https://www.pivotaltracker.com/n/projects/1425900) to:
1. displayname in preferred locale
2. name in preferred locale
3. displayname in english
4. name in english
5. entityID (should never happen as an english name is mandatory)
I took advantage of the opportunity to refactor the organizationName method as well.  This to address the remarks in the previous PRs that dealt with this method: [one by me](https://github.com/OpenConext/OpenConext-engineblock/pull/980#discussion_r529379926) and [one by martin](https://github.com/OpenConext/OpenConext-engineblock/pull/1022/files#r543128672).  The refactor ensures both methods …
> Change algorithm for SP displayname & refactor algorithm for organization name

- bin/makeRelease.sh
- theme/scripts/build.js
~The current makeRelease does not install npm packages.  While there is a build script, this script assumes `npm install` has already run.  Fixed that in this version.~
The script uses `npm ci` to ensure a cleanly installed `node_modules` is composed. In this ticket we also investigated other possible causes for the failing switch between themes. See individual commit messages for more details.
> Ensure build installs npm

- README.md
- app/config/config_dev.yml
- app/config/functional_testing.yml.dist
Additional SF config was required to ensure the twig templates where loaded for the new theme.
Also updated the instructions on how to switch themes in the README.md
> Repair the quirky behavior whilst theme switching

- app/config/parameters.yml.dist
- theme/.babelrc
- theme/base/javascripts/wayf/deleteDisable/savePreviousSelection.js
- theme/base/javascripts/wayf/rememberChoice.js
Several cookie changes:
1. The `http_only` flag was set on the `lang` cookie
2. The rememberchoice and previousSelection cookies where set to be `secure`
:deciduous_tree: To reduce JavaScript build output polution, the babel config was updated to no longer spit very verbose debug output.
See: https://www.pivotaltracker.com/story/show/176287495
See: https://github.com/OpenConext/OpenConext-deploy/pull/320
> Tighten cookie security

- theme/openconext/stylesheets/front-page.scss
The burger and some other small points in the material theme weren't styled properly.  This PR reverts that page to it's old state in the material theme.
The issue was reported [on the wiki](https://wiki.surfnet.nl/pages/viewpage.action?spaceKey=coininfra&title=Bevindingen+januari+2021)
> Style index page in material theme

- app/config/parameters.yml.dist
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MinkContext.php
Other non-PHP components use the lang cookie in their Javascript,
setting the flag on this global cookie would mess up their operations.
Thanks @tveijen voor pointing this out!
See: https://github.com/OpenConext/OpenConext-deploy/pull/320#issuecomment-756109327
See: https://github.com/OpenConext/OpenConext-engineblock/pull/1056
> Remove HttpOnly flag from `lang` cookie

- theme/base/javascripts/wayf/search/toggleSearchAndResetButton.js
- theme/cypress/integration/skeune/wayf/wayf.general.spec.js
Prior to this change, when the user pressed the reset button whilst searching; the default idp remained hidden.
This change ensures the default idp is shown in the above scenario.  It also adds the visibility of the default idp to the test, so if it fails it'll get detected.
[Issue brought up as part of the feedback round](https://wiki.surfnet.nl/display/coininfra/Bevindingen+nav+tests+door+supportteam)
> Ensure hitting reset shows default idp

- theme/base/javascripts/selectors.js
- theme/base/javascripts/utility/fireClickEvent.js
- theme/base/javascripts/wayf/handleIdpBanner.js
Prior to this change, when the user clicked the defaultIdp it focused into view.  Other idps remained visible however.
This change ensures the default idp receives focus and other idps are hidden.
[Issue brought up as part of the feedback round](https://wiki.surfnet.nl/display/coininfra/Bevindingen+nav+tests+door+supportteam)
> Ensure clicking the defaultIdp works correctly

- theme/base/stylesheets/pages/wayf/previousSelection.scss
- theme/base/stylesheets/pages/wayf/remainingIdps.scss
Prior to this change, when on the wayf and hitting the "use another account" button (one needs to have previously selected accounts to do so) there was a weird transition effect.
This change removes the transition animation, thereby also removing the weird transition effect.
[Issue brought up as part of the feedback round](https://wiki.surfnet.nl/display/coininfra/Bevindingen+nav+tests+door+supportteam)
> Remove weird transition in safari

- theme/README.md
- theme/base/stylesheets/components.scss
- theme/base/stylesheets/components/spinner.scss
- theme/base/stylesheets/pages/form.scss
- theme/base/templates/modules/Authentication/View/Proxy/form.html.twig
- theme/skeune/translations/messages.en.php
- theme/skeune/translations/messages.nl.php
- theme/skeune/translations/messages.pt.php
Prior to this change, the spinner page was not adjusted to the new design.
This change ensures that the design fits the skeune theme.  It should look like this: 
[Issue brought up as part of the feedback round](https://wiki.surfnet.nl/display/coininfra/Bevindingen+nav+tests+door+supportteam)
> Redesign the spinner page

- theme/base/javascripts/selectors.js
- theme/cypress/integration/skeune/consent/consent.general.spec.js
- theme/cypress/integration/skeune/consent/consent.keyboard.spec.js
- theme/cypress/integration/skeune/consent/consent.mouse.spec.js
- theme/cypress/integration/skeune/error/error.general.spec.js
- theme/cypress/integration/skeune/index/index.general.spec.js
- theme/cypress/integration/skeune/testSelectors.js
- theme/cypress/integration/skeune/wayf/wayf.general.spec.js
- theme/cypress/integration/skeune/wayf/wayf.keyboard.spec.js
- theme/cypress/integration/skeune/wayf/wayf.mouse.spec.js
Couple cypress tests to same selectors
Prior to this change cypress tests were entirely decoupled from the selectors used in the rest of the application.  This resulted in tests breaking when one of those selectors was changed.
This change imports the selectors from the same file as the one used by the application JS, so that both have a single source of truth.  In instances where special test selectors are needed, a test-selector file is used which composes it's selectors maximally by incorporating the "normal" selectors.
[Issue brought up as part of fixing the IE11 bug for the latest feedback round](https://wiki.surfnet.nl/display/coininfra/Bevindingen+nav+tests+door+supportteam)
> Couple cypress tests to same selectors

- theme/README.md
- theme/base/stylesheets/pages/error-page.scss
- theme/base/templates/modules/Authentication/View/Feedback/authorization-policy-violation.html.twig
- theme/base/templates/modules/Default/View/Error/error.html.twig
Prior to this change the text in the error message was bolded.
This change changes the bold error message to a normal weight error message.  It also adds, in the readme, a link to the page containing functional testing endpoints for all different error pages, so they can be tested.
Last but not least an accessibility improvement was included: the logo now has an empty alt text.
[Issue discovered as part of fixing tickets for the latest feedback round](https://wiki.surfnet.nl/display/coininfra/Bevindingen+nav+tests+door+supportteam)
> Adjust styling of PEP page

- theme/base/javascripts/selectors.js
- theme/base/javascripts/wayf/handleClickingDisabledIdp.js
- theme/base/javascripts/wayf/handleIdpBanner.js
- theme/base/javascripts/wayf/handlePreviousSelectionVisible.js
- theme/base/javascripts/wayf/idpFocus/arrowDown.js
- theme/base/javascripts/wayf/idpFocus/arrowUp.js
- theme/base/javascripts/wayf/matchPreviouslySelectedWithCookie.js
- theme/base/javascripts/wayf/search/assignWeight.js
- theme/base/javascripts/wayf/search/clearWeight.js
- theme/base/javascripts/wayf/searchBehaviour.js
- theme/base/javascripts/wayf/submitForm.js
- theme/base/javascripts/wayf/utility/convertIdpArrayToHtml.js
- theme/base/javascripts/wayf/utility/hasVisibleDisabledButtonAsTarget.js
- theme/base/javascripts/wayf/utility/sortArrayList.js
- theme/base/javascripts/wayf/utility/sortIdpMethods.js
- theme/base/stylesheets/pages/wayf/previousSelection.scss
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp/idp.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp/idpItem.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp/idpList.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/remainingIdps.html.twig
- theme/cypress/integration/skeune/wayf/unit-tests/assignWeight.spec.js
- theme/cypress/integration/skeune/wayf/wayf.general.spec.js
- theme/cypress/support/commands.js
Prior to this change the search in IE11 did not function properly
This change fixes the search.  Turns out querySelectorAll behaviour in IE11 is weird.  So additional checks and balances were added to detect when/if IE acts up.  The element being searched/sorted was also changed from the idp-element to the li.  The change also affected arrow behaviour / cookie behaviour so that was adjusted to fit the changes as well.
[Issue discovered as part of fixing tickets for the latest feedback round](https://wiki.surfnet.nl/display/coininfra/Bevindingen+nav+tests+door+supportteam)
> Ensure IE11 search works

- theme/base/javascripts/wayf/idpFocus/arrowUp.js
- theme/base/javascripts/wayf/idpFocus/checkHover.js
- theme/base/stylesheets/pages/wayf/idpList.scss
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp/idpItem.html.twig
Prior to this change, the connected idps in IE11 showed the disabled button even when not disabled.  This only happened on test2.
This change hides the delete-disabled button by default for remaining idps, and shows it only for those who are disabled.
It also cleans up a forgotten console.log statement, and adds some conditional logic to ensure that the focusOnArrowItem check only happens if there is a focused element (cleaning up the console in IE).
[Issue discovered as part of fixing tickets for the latest feedback round](https://wiki.surfnet.nl/display/coininfra/Bevindingen+nav+tests+door+supportteam)
> Fix IE11 disabled hand bug

- .github/workflows/test-integration.yml
- .gitignore
- bin/securityChecker.sh
- build.xml
The composer depencency is no longer operable, and was removed. This
change uses the new way of running the checker, which is to download the
local checker binary an running that.
> Update security checker to use local checker

- theme/base/javascripts/wayf/matchPreviouslySelectedWithCookie.js
Prior to this change, it was possible that the WAYF was rendered inoperable when syncing cookies.  This happened when an idp was in the cookie, but not available when connecting to a service.  The resulting null error in the JS rendered the entire wayf inoperable.
This change ensures the cookie-syncing doesn't freeze the WAYF.  The problem should be solved with the extra null checks.  But as the sync should never freeze the wayf, it is now wrapped in a try/catch block to be on the safe side.
Issue discovered as part of acceptation testing and [reported in the wiki](https://wiki.surfnet.nl/display/coininfra/Bevindingen+nav+tests+door+supportteam).  It can be tested on functional by adding some of the regular "fake idps" to your selected accounts (preferably only one), then testing with …
> Keep WAYF operable when syncing cookies

- src/OpenConext/EngineBlockFunctionalTestingBundle/Controllers/ConsentController.php
- theme/base/stylesheets/pages/consent/attribute.scss
- theme/base/stylesheets/pages/consent/attributeValue.scss
- theme/base/stylesheets/shared.scss
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/defaultAttribute.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/tooltip.html.twig
- theme/cypress/integration/skeune/consent/consent.general.spec.js
Correct display of tooltip for group attributes
Prior to this change, goup attributes had their tooltip on every row.  The icon for the tooltip was below the value instead of next to it (as for normal attributes) and the tooltip become bold.
This change ensures the tooltip doesn't repeat, the icon is positioned properly and the text of the tooltip is normal weight.
The before screenshot is present in the wiki page mentioned below.  The after screenshot looks like this:
Testing can be done by changing line 93-98 of the ConsentController in the functional testing bundle to:
```
'urn:mace:dir:attribute-def:isMemberOf' => [
'urn:collab:org:vm.openconext.org',
'urn:collab:org:vm.openconext.org2:biefstuk:met:frietjes',
'urn:collab:org:vm.openconext.org3:witloof:in:den:oven', …
```
> Correct display of tooltip for group attributes

- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/source.html.twig
Before, the resulting HTML looked like this:
```html
```
As a side note, this url comes from our own translations files.
> Avoid double encoding logo url for attribute source.

- theme/base/javascripts/wayf/utility/convertIdpArrayToHtml.js
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp/idpItem.html.twig
Prior to this change, when searching all logos became the same placeholder logo in IE11 only.
This change ensures the image url is the correct one, so the logo is the correct one.
Issue discovered as part of acceptation testing and [reported on the wiki](https://wiki.surfnet.nl/display/coininfra/Bevindingen+nav+tests+door+supportteam).
> Ensure images after search are ok in IE11

- theme/base/javascripts/wayf/searchBehaviour.js
Prior to this change, the logo flickers in FF whenever there's an interaction with the search bar.
This change limits the flicker to actual redraws of the idp list by preventing the search handler from being triggered if the previous search term matches the current one.
Issue discovered as part of acceptation testing and [reported on the wiki](https://wiki.surfnet.nl/display/coininfra/Bevindingen+nav+tests+door+supportteam).
> Prevent logo flicker in FF when possible

- theme/base/javascripts/wayf/matchPreviouslySelectedWithCookie.js
Prior to this change, idps added to selected accounts after cookie sync were not deletable because they still had the "remaining" class on them.
This change removes that class ensuring the newly added idp is also deletable.
Steps to reproduce:
- have one previously selected account
- choose a new account to  log in with
- hit the backbutton
- try to delete the newly added account => shouldn't work before this fix, should work after
Issue discovered as part of acceptation testing and [reported on the wiki](https://wiki.surfnet.nl/display/coininfra/Bevindingen+nav+tests+door+supportteam).
> Ensure IdPs are deletable after sync

- theme/base/stylesheets/pages/consent/idpRow.scss
Prior to this change, the logo in the idp-row could overlap with the text.
This change ensures that's no longer possible.  After the change this looks as follows now: 
Issue discovered as part of acceptation testing and [reported on the wiki](https://wiki.surfnet.nl/display/coininfra/Bevindingen+nav+tests+door+supportteam).
> Prevent idprow-logo from overlapping with text

- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/SVG/file_info.svg
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/SVG/shield_key.svg
- theme/base/templates/modules/Default/Partials/warning.html.twig
Prior to this change, there were 3 errors & one warning on the page: three wrong ids in the svgs & one section without a title (warning).
This change ensures that those errors & the warning are fixed.
Issue discovered while studying for WAS certification.
> Fix errors flagged by nu html checker

- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/idpRow.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp/idp.html.twig
- theme/openconext/templates/modules/Authentication/View/Proxy/consent.html.twig
The IdP/Attribute source logo are hosted on a static vhost and do not
change as a result of a new EB software version. They may change for
other reasons but the EB assetversion has no relation to it. Remove the
assetsversion from the request so we do not needlessly invalidate these
logos when upgrading EB.
> Remove assertsversion tag from externally hosted images.

- languages/messages.en.php
- languages/messages.nl.php
- languages/messages.pt.php
- theme/base/javascripts/consent/addA11ySupport.js
- theme/base/javascripts/consent/handleInvisibleTooltips.js
- theme/base/javascripts/consent/hideInvisibleTooltips.js
- theme/base/javascripts/consent/keyboardBehaviour.js
- theme/base/javascripts/consent/showInvisibleTooltips.js
- theme/base/javascripts/consent/toggleTooltipPressedStates.js
- theme/base/javascripts/handlers.js
- theme/base/javascripts/selectors.js
- theme/base/javascripts/utility/changeAriaExpanded.js
- theme/base/stylesheets/pages/consent/attribute.scss
- theme/base/stylesheets/pages/consent/attributeValue.scss
- theme/base/stylesheets/pages/consent/openToggle.scss
- theme/base/stylesheets/shared.scss
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/defaultAttribute.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/engineBlockAttribute.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/list.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/source.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/toggleCheckbox.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/toggleLabel.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/tooltip.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/idpRow.html.twig
- theme/cypress/functions/terminalLog.js
- theme/skeune/templates/modules/Default/Partials/a11yButtonExpandable.html.twig
- theme/skeune/templates/modules/Default/Partials/label.html.twig
- theme/skeune/translations/messages.en.php
- theme/skeune/translations/messages.nl.php
- theme/skeune/translations/messages.pt.php
Prior to this change, there were several issues with the hidden attributes:
- their tooltips were not removed from the tab order when hidden
- showing all hidden attributes did not result in a focus change, meaning SR users were left in the dark
This change ensures that the correct attribute get's focus when showing the hidden attributes.  It also ensures the hidden attribute tooltips are no longer in the taborder.
Issue discovered while studying for WAS certification.
> Handle accessibility for hideable attributes

- theme/base/javascripts/consent/addA11ySupport.js
- theme/base/javascripts/consent/handleNokFocus.js
- theme/base/javascripts/handlers.js
- theme/base/javascripts/selectors.js
- theme/base/stylesheets/pages/consent/ctas.scss
- theme/base/stylesheets/pages/consent/nok.scss
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/ctas.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/nokSection.html.twig
- theme/skeune/templates/modules/Default/Partials/label.html.twig
Prior to this change, pressing the cancel button was implemented for SRs & keyboard users with an aria alert and changes to the aria-hidden state.
This change ensures that clicking the cancel button is implemented for SRs & keyboard users as a disclosure widget.  That means the focus is moved to the title when the nok section is shown and to the button when it the user moves back.  It also means the aria-expanded attribute is set from false to true (or vice versa) depending on whether or not the nok section is shown.
Issue discovered while studying for WAS certification.
> Handle a11y for pressing cancel button in consent screen

- languages/messages.en.php
- languages/messages.nl.php
- languages/messages.pt.php
- library/EngineBlock/Corto/Module/Service/SingleSignOn.php
- src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/Wayf.php
Several changes where made to the WAYF generation logic to reduce the amount of missing translation warnings.
1. Only load the IdP name for the current locale. This gets rid of the missing PT translation on our platform where PT is not an active language. This should solve similar issues for OpenConext users that use only one or two of the supported languages.
2. Translated the `required` translation id
3. Lowered the log level for this missing IdP name log entry.
See: https://www.pivotaltracker.com/story/show/176817180
> Reduce missing translation warnings

- theme/base/translations/messages.en.php
- theme/base/translations/messages.nl.php
- theme/base/translations/messages.pt.php
- theme/openconext/translations/messages.en.php
- theme/openconext/translations/messages.nl.php
- theme/openconext/translations/messages.pt.php
- theme/package-lock.json
- theme/skeune/translations/messages.en.php
- theme/skeune/translations/messages.nl.php
- theme/skeune/translations/messages.pt.php
Prior to this change, theme translations were not overrideable.
This change ensures they are in the same way that the translations in \translations\messages are overrideable.
Issue available in pivotal at https://www.pivotaltracker.com/story/show/176956726
> Make theme translations overrideable

- library/EngineBlock/Corto/Filter/Command/LogLogin.php
- library/EngineBlock/Corto/Module/Service/SingleSignOn.php
- src/OpenConext/EngineBlock/Logger/AuthenticationLogger.php
- src/OpenConext/EngineBlockBridge/Logger/AuthenticationLoggerAdapter.php
- tests/unit/OpenConext/EngineBlock/Logger/AuthenticationLoggerTest.php
- tests/unit/OpenConext/EngineBlockBridge/Logger/AuthenticationLoggerAdapterTest.php
After a successfull login, log the sso endpoint used during authentication. This is available on the _request var present on the
LogLogin command.
https://www.pivotaltracker.com/story/show/175904919
> Log the Engine SSO endpoint used

- src/OpenConext/EngineBlockFunctionalTestingBundle/Helper/TestEntitySeeder.php
Prior to this change, the titles / names / displaytitle were missing in functional tests following the changes for the PT translation.
This change ensures they are restored.
> Fix missing titles in functional tests

- theme/README.md
- theme/base/stylesheets/application.scss
- theme/base/stylesheets/pages/form.scss
- theme/base/stylesheets/pages/logout.scss
- theme/base/stylesheets/shared.scss
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Shared/header.html.twig
- theme/base/templates/modules/Logout/View/Index/index.html.twig
- theme/cypress/integration/shared/logout.a11y.spec.js
- theme/skeune/stylesheets/application.scss
Prior to this change, the logout page had no stying in skeune.
This change:
- adds styling for the logout page
- adds tests for the logout page
- adds documentation for hte logout page
As per the boyscout rule it also fixes a forgotten closing bracket in the forms.scss file.
Issue available in pivotal at https://www.pivotaltracker.com/story/show/177360659
> Ensure logout page is styled for skeune

- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp/idpDeleteDisable.html.twig
Prior to this change, a forgotten debug statement was visible when
deleting an account from "your accounts".
This change removes that statement.
Issue noticed when resolving https://www.pivotaltracker.com/story/show/177506557
> Remove forgotten debug statement

- theme/base/templates/modules/Authentication/View/Feedback/authn-context-class-ref-blacklisted.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/authorization-policy-violation.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/clock-issue.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/custom.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/invalid-acs-binding.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/invalid-acs-location.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/invalid-attribute-value.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/invalid-mfa-authn-context-class-ref.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/metadata-entity-not-found.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/missing-required-fields.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/no-authentication-request-received.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/no-idps.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/received-error-status-code.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/received-invalid-response.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/received-invalid-signed-response.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/session-lost.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/session-not-started.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/stepup-callout-unknown.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/stepup-callout-unmet-loa.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/stepup-callout-user-cancelled.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/stuck-in-authentication-loop.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/unable-to-receive-message.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/unknown-error.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/unknown-identity-provider.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/unknown-preselected-idp.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/unknown-requesterid-in-authnrequest.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/unknown-service-provider.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/unsupported-acs-location-scheme.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/unsupported-signature-method.html.twig
Remove double titles from skeune error pages
Prior to this change, the title element received the textual content
twice.
This change removes the double content.
As per the boyscout rule, a wrong translation tag was also adjusted from
a title in the error body to the actual description.
Issue found when testing https://www.pivotaltracker.com/story/show/176714319
> Remove double titles on skeune error pages

- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Debug.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/SpProxy.feature
- theme/cypress/integration/skeune/wayf/wayf.general.spec.js
- theme/skeune/translations/messages.en.php
- theme/skeune/translations/messages.nl.php
Prior to this change, there was a forgotten instance of
%organisationName% in the english and dutch translation.
This change uses the "account" vernacular instad of the organisationName
variable.
This PR replaces https://github
.com/OpenConext/OpenConext-engineblock/pull/1111 as made by @arnoutt who
noticed the typos.
> Use "account" instead of organisation

- .github/workflows/test-integration.yml
We used php72 in the twig linting script, which is not needed in the CI.
Just plain old "php" wil do.
> Adjust php version in the twig linting script

- languages/messages.en.php
- languages/messages.nl.php
- languages/messages.pt.php
- src/OpenConext/EngineBlock/Stepup/StepupDecision.php
- src/OpenConext/EngineBlockBundle/Authentication/Service/SamlResponseHelper.php
- src/OpenConext/EngineBlockBundle/Resources/config/services.yml
- src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/Feedback.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/EngineBlockContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Stepup.feature
- tests/unit/OpenConext/EngineBlock/Stepup/StepupDecisionTest.php
- theme/base/stylesheets/components/old-not-converted/error-page/footer.scss
- theme/base/templates/modules/Authentication/View/Feedback/partial/saml_response_form.html.twig
- theme/base/templates/modules/Default/View/Error/partial/footer.html.twig
When required data is available, a back to SP button is rendered. Clicking this button sends a AuthnFailed SAML response back to the issuing SP.
https://www.pivotaltracker.com/story/show/176960606
> Add a 'back to SP' button on the Stepup failed error pages

- library/EngineBlock/Application/DiContainer.php
- library/EngineBlock/Corto/Module/Bindings.php
- library/EngineBlock/Corto/Module/Service/AssertionConsumer.php
- library/EngineBlock/Corto/ProxyServer.php
- library/EngineBlock/Saml2/ResponseAnnotationDecorator.php
- src/OpenConext/EngineBlock/Service/MfaHelper.php
- src/OpenConext/EngineBlock/Service/MfaHelperInterface.php
- src/OpenConext/EngineBlockBundle/Resources/config/services.yml
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/MfaAuthnContextClassRef.feature
- tests/unit/OpenConext/EngineBlock/Service/MfaHelperTest.php
When a SP request a AuthnContext and transparent_authn_context is enabled, we pass on to the IDP. There is no way for us to know the meaning or value for this AuthnContext. If a user can't use the requested AuthnContext, the SP should be informed so it can decide what to do.
When an SP is configured for transparant_authn_context, an NoAuthContext saml error from the IDP should be copied to the SP, so it can act accordingly.
https://www.pivotaltracker.com/story/show/173602383
> Transparent SAML error Response for MFA entities

- app/config/config.yml
- app/config/parameters.yml.dist
The result is the same, but it allows disabling the function "proc_open" in the PHP FPM configuration
> Change the mail configuration to smtp in stead of Sendmail

- .github/workflows/test-integration.yml
- theme/package-lock.json
There are quite a lot of security problems being thrown up by npm audit. This PR is to fix those.
After trying out a better fix, we opted to disable the security check for the devdependencies.  Currently upgrading those is not compatible with maintaining support for IE8
> Fix npm audit problems

- languages/messages.en.php
- languages/messages.nl.php
- languages/messages.pt.php
- theme/base/templates/modules/Authentication/View/Feedback/missing-required-fields.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/no-idps.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/received-invalid-signed-response.html.twig
- theme/base/templates/modules/Authentication/View/Feedback/unknown-service-provider.html.twig
- theme/openconext/templates/modules/Authentication/View/Feedback/authn-context-class-ref-blacklisted.html.twig
- theme/openconext/templates/modules/Authentication/View/Feedback/authorization-policy-violation.html.twig
- theme/openconext/templates/modules/Authentication/View/Feedback/clock-issue.html.twig
- theme/openconext/templates/modules/Authentication/View/Feedback/invalid-attribute-value.html.twig
- theme/openconext/templates/modules/Authentication/View/Feedback/invalid-mfa-authn-context-class-ref.html.twig
- theme/openconext/templates/modules/Authentication/View/Feedback/missing-required-fields.html.twig
- theme/openconext/templates/modules/Authentication/View/Feedback/no-idps.html.twig
- theme/openconext/templates/modules/Authentication/View/Feedback/received-invalid-signed-response.html.twig
- theme/openconext/templates/modules/Authentication/View/Feedback/stuck-in-authentication-loop.html.twig
- theme/package-lock.json
Prior to this change:
- the fallback of the unknown-service-provider had
a missing case: that for no idp name.  There was also a word missing
from the Dutch translation.
- there was no fallback for the received an invalid signed response error
- there was a missing fallback for no-idps-error
- the name of the fallbacks for missing required fields was incorrect
- the openconext theme had several missing fallbacks
This change adds the cases & fixes the translation.
Pivotal story at: https://www.pivotaltracker.com/story/show/176714319
Relevant comments at:
- https://www.pivotaltracker.com/story/show/176714319/comments/224272628
- https://www.pivotaltracker.com/story/show/176714319/comments/224272649
> Ensure fallbacks in the error pages function correctly

- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Stepup.feature
- theme/base/templates/modules/Default/View/Error/partial/footer.html.twig
Prior to this change, the back to sp SAML payload provided the wrong
issuer, resulting in an error.
This change temporarily disables the back to sp link so the release can
be finished & this feature tackled in the next release.
Pivotal story at: https://www.pivotaltracker.com/story/show/176960606
> Temporarily disable back to sp link

- theme/base/stylesheets/pages/consent/attributes.scss
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/noAttributes.html.twig
Prior to this change, the no-attributes edge case was unstyled.  This
led to a ugly bullet point.
This change adds styling to the no-attributes edge case.
Pivotal ticket: https://www.pivotaltracker.com/story/show/178379702
> Style the no-attributes case

- library/EngineBlock/Corto/Filter/Command/AddEduPersonTargettedId.php
- library/EngineBlock/Corto/Filter/Output.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/EduPersonTargetedId.feature
Currently EB applies the ARP two times in the filter chain. The second time it is just done because ePTI is first added unconditionally, then the entire ARP is applied to decide whether this is to be let through. So if you have an ARP that results in (a,b) in the first pass, the AddEduPeronTargetedId filter command makes the attribute set be (a,b,ePTI), the second ARP is applied and the attribute set is again (a,b).
This has several drawbacks:
- Anything added in the attribute manipulation is filtered out by the second ARP run. This usually means that you need to disable the ARP when having an AM. This has quite some consequences including confusing display in the Consent screen and in Dashboard.
- Attribute aggregation is configured in the ARP so you cannot use AA with an Attribute …
> Apply ARP only once in the filter chain.

- theme/base/templates/modules/Authentication/View/Proxy/form.html.twig
Prior to this change, the spinner page used arrow notation.  This
apparently broke the excel built-in browser.
This change uses the older function notation.
Pivotal ticket @ https://www.pivotaltracker.com/story/show/178713929
> Fix the spinner page in the excel browser

- .docheader
- app/config/config.yml
- app/config/parameters.yml.dist
- composer.json
- docs/sso_notification.md
- library/EngineBlock/Application/DiContainer.php
- library/EngineBlock/Corto/Filter/Command/Helpers/CookieHandler.php
- library/EngineBlock/Corto/Filter/Command/SsoNotificationCookieFilter.php
- library/EngineBlock/Corto/Filter/Input.php
- library/EngineBlock/Corto/Module/Service/SingleSignOn.php
- src/OpenConext/EngineBlock/Service/SsoNotificationService.php
- src/OpenConext/EngineBlockBundle/Configuration/TestFeatureConfiguration.php
- src/OpenConext/EngineBlockBundle/Resources/config/services.yml
- tests/library/EngineBlock/Test/Corto/Filter/Command/SsoNotificationCookieFilterTest.php
- tests/unit/OpenConext/EngineBlock/Service/SsoNotificationServiceTest.php
In this pull request we have added functionality to be able to process SSO Notifications.
**Short introduction on SSO Notifications**
SSO Notifications enable schools to reduce the number of steps users have to take during the login process and increase 
user-friendliness by providing the possibility to skip the WAYF (Where Are You From) screen. This is done via the use 
of a cookie, which can be set for example after the user has logged in on his own environment (for example an intranet page or the 
homepage of an Electronic Learning Environment).
---
Setting SSO Notification cookies is performed by a separate application - the SSO Notification service. Engineblock
is able to read the cookie and retrieve the entity id of the Identity Provider which should be used to start an …
> Add feature for SSO Notifications

- library/EngineBlock/Attributes/Manipulator/ServiceRegistry.php
- library/EngineBlock/Corto/Filter/Command/RunAttributeManipulations.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/AttributeManipulation.feature
The Attribute Manipulations could use any items from the IdP, SP
metadata and prepared response, but could not read the AuthnRequest.
Adding `$requestObj` as an input adds a generic way to access information
from the request. It is (obviously) read only.
We're adding it only in the object form to mirror how the response is
passed, but do not convert it to any legacy format; that seems
unnecessary for a new feature.
There's a behat test that verifies that the AM can indeed read something
from the `$requestObj` variable - the AM itself in this scenario makes
not much sense but shows that we can read something from the object and
do something with it.
> Make the original AuthnRequest available to attribute manipulations.

- app/config/parameters.yml.dist
- src/OpenConext/EngineBlock/Xml/MetadataRenderer.php
- src/OpenConext/EngineBlockBundle/Resources/config/services.yml
- tests/unit/OpenConext/EngineBlock/Xml/MetadataRendererTest.php
- theme/base/templates/modules/Authentication/View/Metadata/sp.xml.twig
- theme/openconext/templates/modules/Authentication/View/Metadata/sp.xml.twig
Currently an IdP based on SimpleSAMLphp (v1.19.1) sends a limited list of attributes to an SP which defines RequestedAttributes, namely only the attributes which are defined in the RequestedAttributes. This limits the use of attribute conditions within Engineblock since the min condition, which adds the attribute to RequestedAttributes, can not be used. 
We have added an option to allow control over the RequestedAttribute list added to the proxy SP metadata of Engineblock where options 'all', 'required' and 'none' are supported. Default has been set to 'all' which is how currently Engineblock works. This may turn out to be a temporary solution if this is handled in SimpleSAMLphp but we wanted to provide this all the same.
> Add configuration options for requested attributes in proxy SP metadata

- library/EngineBlock/Corto/Filter/Command/RunAttributeManipulations.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/AttributeManipulation.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/AttributeReleasePolicy.feature
AttributeValueTypes is an array contains the types (string, bool, int..) for each value of all released attributes in the attributes array. The ARP ensures the two arrays remain consistent after filtering out some values. However, the Attribute Manipulation also has the option to change the released attributes in the `$attributes` array passed to it. AM's do however not have a way to change the corresponding list of types (it is not available to the AM code).
If this is not done, in the case that the resulting set has less values than the original set after ARP, one gets [an Exception from the SAML2 library](https://github.com/simplesamlphp/saml2/blob/04d0ed6c5e51cbb328afe1bdcba2cc7bd84d7e87/src/SAML2/Assertion.php#L1690) that there are more valuetypes than values.
Earlier, this would …
> Reset attributeValueTypes after an Attribute Manipulation

- docker/php-fpm/Dockerfile-php72
- docker/php-fpm/Dockerfile-php74
The build of the PHP FPM container was not passing. This because NPM could not be installed. This was resolved by pulling NPM and Node from the official Node container. NPX needed a manual installation afterwards.
> Verify GHA Test intergration works as intended

- theme/README.md
- theme/package-lock.json
- theme/package.json
- theme/scripts/build.js
- theme/scripts/watch.js
**The following changes have been implemented with this PR:**
- The build script now allows images and fonts to be loaded from custom themes instead of just from the base. To clarify this process we have split the copying in two steps 'copy the base' and 'copy the theme'
- To support our build processes we have upgraded yargs-parser from "18.1.2" to "20.2.9"
- We have added a watch script that will detect any changes to the selected theme and updates the web folder to speed up the development process 'npm run watch'
- The build script will now return error code 1 when a build has failed.
Please let us know if you have any questions.
_Failure with yargs-parser 18.1.2:_
```
exec error: Error: Command failed: cd XX/engineblock/theme/scripts/.. && EB_THEME=kennisnet npm run buildtheme …
```
> Fix build script for custom themes, add watch script and fail build on error

- application/configs/attributes.json
Adding the internal-collabPersonId to the dictionary. This is internally used when a Trusted Proxy is involved in the authentication.
Task 2 of: https://www.pivotaltracker.com/story/show/181121279
> Update attribute dictionary

- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/preselection.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/remainingIdps.html.twig
The IdPs in the WAYF are supposedly sorted: by count (when used before)
or by name (remaining IdPs). This happens in JS and happens correctly
when you use the sort field or clear it. However, the initial state
(the screen as shown when not searching for anything yet) is unsorted.
This is solved in the twig template by sorting the used IdPs (by
count, descending - most often used first) and the remainig IdPs by
displayTitle(lowercase). This is the same algorithm as JS used. Solving
this in the template/HTML means it's also solved for non-JS scenarios.
and there's no need to 'resort' the initial screen before it can be
displayed.
> Initially sort the displayed IdPs in WAYF correctly.

- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/AttributeManipulation.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/AttributeReleasePolicy.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/PolicyEnforcement.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/SpProxy.feature
Thanks to a good sit-down with @thijskh several relevant trusted proxy behavioral tests where identified. Most of which are variations on existing tests that are not TP related. The tests have been specified in the tasks of the story linked below. This PR adds these tests.
> Improve Trused Proxy Behat test coverage

- library/EngineBlock/SamlHelper.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/SpProxy.feature
If the end-SP behind the trusted proxy is unknown, an error message was shown that the trusted proxy itself was unknown. This corrects that in the same fashion as already used in [SingleSignOn::receive()](https://github.com/OpenConext/OpenConext-engineblock/blob/24c1f3dc4ae3b36a49f2a2e33e442379ae113180/library/EngineBlock/Corto/Module/Service/SingleSignOn.php#L178-L179).
https://www.pivotaltracker.com/story/show/178698658
> Display correct information in error message for unknown proxied SP

- src/OpenConext/EngineBlock/Authentication/Dto/Consent.php
- tests/functional/OpenConext/EngineBlockBundle/Controller/Api/ConsentControllerTest.php
- tests/unit/OpenConext/EngineBlock/Authentication/Dto/ConsentTest.php
Retrieval of the right organization name is implemented to the following
algorithm:
```
L = current language, "en" is English the global default language.
If OrganizationDisplayName:L is set, return OrganizationDisplayName:L
else if OrganizationName:L is set, returnOrganizationName:L
else if OrganizationDisplayName:"en" is set, return OrganizationDisplayName:"en"
else if OrganizationName:"en" is set, returnOrganizationName:"en"
else return "unknown" (should not happen on production, Manage check will be added that always one of the fields is present)
```
This is to support Profile in showing the organization offering the
service on the 'my-services' page
More info and background: https://www.pivotaltracker.com/story/show/176872837
> Include organization names in Consent DTO

- theme/base/javascripts/wayf/handleClickingDisabledIdp.js
**Description of issue:**
If you press an unconnected IdP the RA form is shown, but you click the greyed out IdP (which remains visible) again you get errors in the JS console
**Solution:**
Only remove the form from the IdP clone when the form still exists. Clicking on a disconnected idp triggers the script to handle the request access form interactions. One of these actions is to remove the form triggering SSO on the targetted IdP. When the form is already removed in a previous click, a successive click would trigger a console error.
**See:**
https://www.pivotaltracker.com/n/projects/1425900/stories/180935719
> Prevent removal of form from IdP when previously removed

- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp/idp.html.twig
This display name is assumed to be set on the idp row when sending the request access mail message. Not having it set here will result in the mail message not being sent.
See point 3 of: https://www.pivotaltracker.com/story/show/180935719
> Set IdP name on the wayf__idp row

- app/config/config.yml
- app/config/parameters.yml.dist
- database/DoctrineMigrations/Version20220425090852.php
- library/EngineBlock/Corto/Model/Consent.php
- library/EngineBlock/User.php
- src/OpenConext/EngineBlock/Authentication/Repository/ConsentRepository.php
- src/OpenConext/EngineBlock/Service/ConsentService.php
- src/OpenConext/EngineBlock/Service/ConsentServiceInterface.php
- src/OpenConext/EngineBlock/Service/DeprovisionService.php
- src/OpenConext/EngineBlock/Service/DeprovisionServiceInterface.php
- src/OpenConext/EngineBlock/Service/MetadataService.php
- src/OpenConext/EngineBlock/Service/MetadataServiceInterface.php
- src/OpenConext/EngineBlockBundle/Authentication/Entity/Consent.php
- src/OpenConext/EngineBlockBundle/Authentication/Repository/DbalConsentRepository.php
- src/OpenConext/EngineBlockBundle/Configuration/TestFeatureConfiguration.php
- src/OpenConext/EngineBlockBundle/Controller/Api/AttributeReleasePolicyController.php
- src/OpenConext/EngineBlockBundle/Controller/Api/ConsentController.php
- src/OpenConext/EngineBlockBundle/Controller/Api/DeprovisionController.php
- src/OpenConext/EngineBlockBundle/Controller/Api/MetadataController.php
- src/OpenConext/EngineBlockBundle/Factory/CollabPersonIdFactory.php
- src/OpenConext/EngineBlockBundle/Resources/config/repositories.yml
- src/OpenConext/EngineBlockBundle/Resources/config/routing_api.yml
- tests/functional/OpenConext/EngineBlockBundle/Controller/Api/ConsentControllerTest.php
- tests/functional/OpenConext/EngineBlockBundle/Controller/Api/DeprovisionControllerTest.php
- tests/unit/OpenConext/EngineBlock/Service/ConsentServiceTest.php
- tests/unit/OpenConext/EngineBlock/Service/DeprovisionServiceTest.php
An API endpoint is created to remove a single consent row based on a user id and a SP entity id. This allows the profile end user to retract consent for services they have previously granted consent to.
https://www.pivotaltracker.com/story/show/179490276
> Support removal of consent by collab person id and SP entity id

- src/OpenConext/EngineBlockBundle/Controller/Api/ConsentController.php
- tests/functional/OpenConext/EngineBlockBundle/Controller/Api/ConsentControllerTest.php
Makes behaviour more explicit and does not expose code paths that are not needed.
> Disable the Consent-related API endpoints if EB's consent feature is off

- app/config/parameters.yml.dist
- src/OpenConext/EngineBlock/Metadata/Loa.php
- src/OpenConext/EngineBlock/Metadata/LoaRepository.php
- src/OpenConext/EngineBlock/Stepup/StepupDecision.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Stepup.feature
- tests/unit/OpenConext/EngineBlock/Metadata/LoaRepositoryTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/LoaTest.php
- tests/unit/OpenConext/EngineBlock/Stepup/StepupDecisionTest.php
- tests/unit/OpenConext/EngineBlock/Stepup/StepupGatewayLoaMappingTest.php
The config changed slightly to support loa 1.5. The array keys indicating the numeric portion of a loa (1, 1.5, 2 and 3) used to be an integer value. Well the index is now still integer, but multiplied by 10. This to support loa 1.5 (translate to 15 now)
Tests have been updated and extended with the new 1.5 loa.
The Loa and LoaRepository classes have been made more type-strict.
See: https://www.pivotaltracker.com/story/show/182769301
> Support LoA 1.5

- library/EngineBlock/Corto/Module/Service/SingleSignOn.php
The sorting is already done in [Twig](https://github.com/OpenConext/OpenConext-engineblock/blob/master/theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/remainingIdps.html.twig#L11)
Also fixes:
```
app.ERROR: Undefined index: Name_nl [/apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.9.0/library/EngineBlock/Corto/Module/Service/SingleSignOn.php:527
```
> Remove broken sorting code

- docker/php-fpm/Dockerfile-php72
- docker/php-fpm/Dockerfile-php74
xdebug is not needed during integration tests, and pecl will no longer install the latest version as the olders supported php version is 8.0. Since xdebug is not needed, it's better to remove it all together.
> GHA: Remove xdebug from the FPM images

- library/EngineBlock/Corto/Filter/Command/LogLogin.php
- library/EngineBlock/Corto/Module/Service/SingleSignOn.php
- src/OpenConext/EngineBlock/Logger/AuthenticationLogger.php
- src/OpenConext/EngineBlockBridge/Logger/AuthenticationLoggerAdapter.php
- tests/unit/OpenConext/EngineBlock/Logger/AuthenticationLoggerTest.php
- tests/unit/OpenConext/EngineBlockBridge/Logger/AuthenticationLoggerAdapterTest.php
Logline now has new `requestedidps` key. In prettyprinted form (but of course usually a single logline):
```json
{
"channel" : "authentication",
"context" : {
"authncontextclassref" : "urn:thijs:voorbeeld",
"engine_sso_endpoint_used" : "https://engine.test2.surfconext.nl/authentication/idp/single-sign-on",
"idp_entity_id" : "http://mock-idp/",
"key_id" : null,
"login_stamp" : "2023-01-11T16:26:09.899430+01:00",
"original_name_id" : "1a929a9cd49b901a497ac320152aa1cef6d542c9",
"proxied_sp_entity_ids" : [],
"requestedidps" : [
"aap",
"noot",
"http://mock-idp/"
],
"sp_entity_id" : "urn:thki:sid:ee1",
"user_id" : "urn:collab:person:example.com:thijs",
"workflow_state" : "prodaccepted"
},
"extra" : {
"request_id" : "63bed511c8bd1",
"session_id" : "c6crks94rcn88cub6kvm4cel39"
},
"level" : …
```
> Log in log_logins if IDPList has been used

- src/OpenConext/EngineBlockBundle/Controller/IndexController.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/FrontPage.feature
- theme/base/templates/modules/Authentication/View/Index/index.html.twig
- theme/openconext/templates/modules/Authentication/View/Index/index.html.twig
Previously, the index page of Engineblock would look like this (an installation with two keys in the config: the same key is set as 'default' and '20181213'):
There's three links of metadata for each type. However, the first two are duplicated. The URLs without a keyslug are already implying that the default key is used. So there's no actual difference between those two. If the default key changes, both will change. This is confusing and also clutters the page, even more for installs that have a single key defined.
Skip the redundant key:default when generating the list of metadata variants. The URLs with key:default in them will still work but just are not displayed. They will still work because key:default is not otherwise 'special' and just another key in the config. Changing that …
> Display no metadata endpoints with key default

- languages/messages.en.php
- languages/messages.nl.php
- languages/messages.pt.php
- library/EngineBlock/Corto/Exception/UnknownKeyId.php
- library/EngineBlock/Corto/ProxyServer.php
- src/OpenConext/EngineBlock/Metadata/X509/KeyPairFactory.php
- src/OpenConext/EngineBlockBundle/Controller/FeedbackController.php
- src/OpenConext/EngineBlockBundle/EventListener/RedirectToFeedbackPageExceptionListener.php
- src/OpenConext/EngineBlockBundle/Exception/UnknownKeyIdException.php
- src/OpenConext/EngineBlockBundle/Resources/config/routing/feedback.yml
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/ClearErrorMessages.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Metadata.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/UnsolicitedSingleSignOn.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Service/EngineBlock.php
- tests/unit/OpenConext/EngineBlock/Metadata/X509/KeyPairFactoryTest.php
- theme/base/templates/modules/Authentication/View/Feedback/unknown-keyid.html.twig
- theme/openconext/templates/modules/Authentication/View/Feedback/unknown-keyid.html.twig
* Add a concrete error message when someone access a URL (SSO or metadata) with an unknown key id. Unknown is then likely: used to work, but key has been phased out since. But could also be some typo of course.
* While we're at it, add integration tests for metadata endpoints with a keyid specified.
* Clean up an obsolete function.
> Clear error unknown keyid

- src/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssembler.php
- src/OpenConext/EngineBlockBundle/Resources/config/services.yml
- tests/integration/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssemblerTest.php
The current database scheme has varchar(255) for several metadata types. Traditionally, MySQL would just truncate silently any too long values. Modern installations have strict mode enabled which instead generates a justified error. To make EB usable in this configuration, limit the length of some fields that (a) have a trend to sometimes be long, (b) which can be truncated without real loss.
One could consider to enlarge columns but as far as I'm aware description is not used and 255 chars of keywords should be enough for everyone. So for now lets keep it to this simple fix.
> Limit value length of metadata fields to max 255 chars.

- theme/cypress/plugins/index.js
- theme/cypress/support/index.js
- theme/package-lock.json
- theme/package.json
Prior to this change, there was very limited logging of cypress tests in
the CI.
This change adds logging that is on par with the logging in a
non-headless environment via the cypress-terminal-logging plugin.
It also upgrades the html-validate and cypress-html-validate plugins.
> Upgrade cypress logging in CI

- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/MultipleSingleSignOn.feature
A multiple in-flight authentication Behat scenario was disabled in the past as it was deemed unstable. This issue no longer seems present as the test passes with flying colors. Probably as dependencies that hindered this test where upgraded long ago.
https://www.pivotaltracker.com/n/projects/1425900/stories/174358940
> Enable skipped MultipleSingleSignOn scenario

- tests/library/EngineBlock/Test/Corto/Filter/Command/VerifyShibMdScopingAllowsSubjectIdTest.php
This part of the testsuite did not run at all due to a syntax error. When it was made running it turned out the logging tests were not checking the right string.
> Fix ShibMD scope tests.

- .github/workflows/test-integration.yml
There's no relation between changes in a PR and the presence of a security issue or between the frequency of PRs and the frequency we want to check for security issues. So remove it here. We keep the script in bin/ for now, might come in handy at some point.
> No longer run security checker as part of integration tests

- library/EngineBlock/Corto/Module/Service/AssertionConsumer.php
- library/EngineBlock/Corto/ProxyServer.php
- library/EngineBlock/Saml2/AuthnRequestAnnotationDecorator.php
- src/OpenConext/EngineBlock/Metadata/Coins.php
- src/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssembler.php
- src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Controllers/StepupMockController.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/EngineBlockContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/StepupContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Stepup.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Fixtures/ServiceRegistryFixture.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Resources/views/Sso/consumeAssertion.html.twig
- tests/integration/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssemblerTest.php
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Factory/ServiceProviderFactoryTest.php
Manage can push SP Metadata containing the coin:stepup:forceauthn coin.
That value is picked up in the Assembler, and saved on the SP eb5 roles, coin column.
During the StepUp round trip via StepUp Gateway, EB checks if the FoceAuthn flag should be added to that AuthNRequest. If this is specified for that SP, it is added. Otherwise no additional logic is performed.
When dealing with a trusted proxy setup, the stepup settings for the requesting sp are used, not that of the TP.
In order to get insghts in the outgoing AR to the StepUp Gateway, the mock gateway page that is used in the funcitonal tests now displays the received AR as an unsigned xml string. That string is used to perform xpath queries on, determiniing the presense or absence of the forceauthn flag.
See: …
> Support ForceAuthn to Stepup Gateway callout

- src/OpenConext/EngineBlockBundle/Http/Response/JsonHelper.php
This API is used by Profile to get information about the user's IdP for display purposes. It does not use this information at all. We can add more code to avoid the notices or just remove working on something that is not used at all.
> Avoid generating PHP notices when calling metadata API for IdP without SLO

- library/EngineBlock/Corto/ProxyServer.php
> If we have a request ID, it's by definition not unsolicited

- library/EngineBlock/Corto/Adapter.php
- src/OpenConext/EngineBlock/Metadata/MetadataRepository/IdpsMetadataRepository.php
In regular auhtentication the UnknownServiceProvider exception is thrown when an authnrequest is received from an unknown SP. Do the same for when the unknown SP originates from the unsolicited SSO url parameter (before it would throw the generic uncaught exception page).
> Show an Unknown SP error page also when invoking the unsolicited endpoint

- src/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssembler.php
- tests/integration/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssemblerTest.php
This would effectively empty out the database. That is never a desirable outcome, so reject it, whatever the cause.
> Refuse to process incoming metadata push with 0 connections in it.

- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/disclaimerList.html.twig
Previously we would show the eula URL (that we mistakenly translated to be the privacy statement of the SP). In a recent change, we use the correct value sent to us from Manage (see #1234 for details). That PR did everything to load the correct data onto the SP/IdP, but would never show it on the consent screen.
This PR fixes that.
https://www.pivotaltracker.com/story/show/185134950
> Display the correct privacy statement url on consent screen

- docs/stepup_callout.md
- library/EngineBlock/Corto/Exception/ReceivedErrorStatusCode.php
- src/OpenConext/EngineBlockBundle/Authentication/Service/SamlResponseHelper.php
- src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/Feedback.php
- src/OpenConext/EngineBlockBundle/Value/FeedbackInformation.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Stepup.feature
- tests/unit/OpenConext/EngineBlockBundle/Authentication/Service/SamlResponseHelperTest.php
- theme/base/templates/modules/Default/View/Error/partial/footer.html.twig
When the preconditions are met, a Back to SP link is displayed on the error feedback page. The preconditions are described and discussed on the Pivotal story found in the link below.
The way this works is as follows: when EB sees that a response from the IdP is not successful, it throws an exception. This results in a user facing feedback page where the end user is instructed that authentication failed for a given reason (they can vary (cancelled, no auth context, ..). On that page the user is kind of stuck. But by pressing the back to sp button, the user can now travel back to the SP with the SamlFailedResponse. Allowing the SP to deal with the failed authentication instead of remain stranded at Engine.
Some what was most challenging was how to port all required data to the feedback …
> Show back to SP link on error page

- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp/idp.html.twig
The WAYF would perform requests for literally `/images/placeholder.png?v={{ assetsVersion }}`, because of this misuse of Twig variable interpolation.
> Fix WAYF placeholder.png having uninterpolated assetsVersion variable

- .github/workflows/tag-release.yml
- bin/makeRelease.sh
- composer.json
- composer.lock
- docker/docker-compose-tag-release.yml
The 'openconext' container is now based on the BaseContainers Apache 2 PHP 7.2 Composer 2 Node 14 base image.
As the build tag script only utilizes npm & composer to build the tarbal, this image should suffice nicely.
To get a working tarbal a couple of minor tweaks were in order.
1. We for now ignore the dependency on ext_exif, could be added to the base container @quartje ?
2. To get npm in the path, the login script must be run when executing code in the container (`tag-release.yml` L22)
> Move to modern BaseContainer base image

- bin/makeRelease.sh
The tag-release script calls the `makeRelease.sh` script. That script was not yet made aware that we stopped using NPM. Now that it uses Yarn, we should now be able to create releases once again. 
Tested on my dev machine, and it did create a sensible Tarbal there.
> Substitue NPM for Yarn in makeRelease.sh

- src/OpenConext/EngineBlock/Service/RequestAccessMailer.php
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/noAccess/requestForm.html.twig
* The 'motivation' field seems to be actually required, since submitting the form without it filled fails (with no message). Simplest solution is to also make it required in the front end so it's clear to the user they need to fill this in. It also makes sense to require a motivation with the report.
* Mails fail to send because the From is set to the user's emailadress, which we may not be allowed to send mail as at all. Change this to the To address which we own and can send mail as.
> Request Access bugfixes

- src/OpenConext/EngineBlockFunctionalTestingBundle/Controllers/ConsentController.php
- theme/base/templates/modules/Authentication/View/Proxy/form.html.twig
This was inadvertently broken in #1272
> Restore functionality of RelayState and return parameters to SPs

- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/FrontPage.feature
- theme/base/templates/modules/Authentication/View/Index/index.html.twig
- theme/openconext/templates/modules/Authentication/View/Index/index.html.twig
Since these other types do not (currently) do anything with the keyId, this is just confusing and should not be published.
> Do not generate per-keyId metadata links for non-IdP metadata

- library/EngineBlock/Corto/Module/Service/SingleSignOn.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Debug.feature
This ensures we have a fresh session of the user to test against, so any changes to the IdP config will be reflected in this debug result.
> When starting an engine IdP debug authentication, force authentication at the IdP

- theme/base/templates/layouts/scripts/default.html.twig
This happens mostly when someone pastes a link to a social medium which redirects immediately to OpenConext and e.g. shows a WAYF. The social preview of that link is then the logo of the first IdP in the wayf. This improves on that by ensuring that the logo used is the OpenConext instance's own logo. This is a less "random" experience.
There are more fields available in the OpenGraph specification but we do not have readily available content for those fields. The fields we add now we can fill with information we already have in the template so are a quick way to improve the social previews over the previous situation.
> Improve social previews of EB URLs

- src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/Feedback.php
The function will return false if any of the needed info is not available, however EB would already fail with a type error inside the getSamlFailedResponse() method. By reordering these checks we prevent the type error for this case.
Closes: #1288
> Check for needed parameters before constructing an auth failed response.

- .github/workflows/test-integration.yml
- .gitignore
- CHANGELOG.md
- UPGRADING.md
- app/config/config.yml
- app/config/config_test.yml
- app/config/functional_testing.yml.dist
- app/config/parameters.yml.dist
- docker/php-fpm/Dockerfile-php72
- library/EngineBlock/Application/DiContainer.php
- library/EngineBlock/Corto/Module/Service/StepupAssertionConsumer.php
- library/EngineBlock/Corto/ProxyServer.php
- src/OpenConext/EngineBlock/Metadata/Factory/Factory/ServiceProviderFactory.php
- src/OpenConext/EngineBlock/Stepup/StepupEntityFactory.php
- src/OpenConext/EngineBlockBundle/Configuration/TestFeatureConfiguration.php
- src/OpenConext/EngineBlockBundle/Resources/config/services.yml
- src/OpenConext/EngineBlockFunctionalTestingBundle/Controllers/StepupMockController.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/EngineBlockContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/StepupContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/StepupKeyRollover.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Fixtures/FunctionalTestingFeatureConfiguration.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/MockStepupGateway.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Resources/config/mocks.yml
- src/OpenConext/EngineBlockFunctionalTestingBundle/Resources/config/services.yml
- tests/behat.yml
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Factory/ServiceProviderFactoryTest.php
Currently the SAML EntityID of the engineblock SP that us used to do Stepup (SFO) authenticatons to the Stepup-Gateway is always https://<engineblock.sever.domain.name>/authentication/stepup/metadata
The key used to sign the SAML AuthnRequests from this SP is the engineblock default key.
To facilitate a rolling configuration update I want the SP entityID that is used for Stepup to be configurable so that at the same time that the engineblock default key is updated, this entityID can be changed. This then allows two entities, with two different keys, to be configured in the Stepup-Gateway.
https://www.pivotaltracker.com/story/show/186200738
> Support overriding StepUp EntityId

- app/config/parameters.yml.dist
- library/EngineBlock/Application/DiContainer.php
- library/EngineBlock/Corto/Filter/Command/LogLogin.php
- library/EngineBlock/Corto/Filter/Output.php
- src/OpenConext/EngineBlock/Logger/AuthenticationLogger.php
- src/OpenConext/EngineBlockBridge/Logger/AuthenticationLoggerAdapter.php
- tests/unit/OpenConext/EngineBlock/Logger/AuthenticationLoggerTest.php
- tests/unit/OpenConext/EngineBlockBridge/Logger/AuthenticationLoggerAdapterTest.php
Hi all,
With these changes we would like to contribute support for enriching the authentication logging. For some context, this refers to the logging done with 'login granted' where information such as timestamp, SP, IdP etc. is logged. These changes allow the configuration of a mapping in parameters.yml to enrich the logging information with response attributes. 
The mapping consists of a label and the name of attribute that is desired e.g. in parameters.yml:
```
auth.log.attributes: 
myLabel1: attributeKey1
myLabel2: attributeKey2
...
```
Default value is empty array.
The logging would then look like
authentication.INFO: login granted {"login_stamp":"2024-04-26T12:02:42.904740+02:00","user_id":"<xxx>","sp_entity_id":"<sp>","idp_entity_id":"<idp>","key_id":null,"proxied_sp_entity_ids":[], …
> Support for authentication logging enrichment

- library/EngineBlock/Corto/Module/Service/SingleSignOn.php
When constructing the WAYF data, previously the current locale was not considered and the method would just in order use the first available of en, nl, or pt. With this change, Engine will first see if there are keywords for the current locale of the WAYF, if not, use en as a fallback, otherwise return Undefined as before.
Closes: #1303
> Locale is considered when providing keywords to WAYF

- src/OpenConext/EngineBlockBundle/Controller/Api/ConnectionsController.php
- tests/functional/OpenConext/EngineBlockBundle/Controller/Api/ConnectionsControllerTest.php
When the pushConnectionsAction fails because the DoctrineMetadataPushRepository failed to save the assembled roles data. We should throw a HTTP exception. Otherwise the action would not output JSON. Resulting in a user facing error page. Which is not user friendly for a consumer
Fixes: https://github.com/OpenConext/OpenConext-engineblock/issues/1309
> Ensure HTTP exception is thrown when API fails

- .github/workflows/tag-release.yml
Some time ago docker compose has become a default plugin shipped with docker, in stead of a separate package. So the command "docker-compose" has changed to "docker compose" 
This will fix the workflow that creates the release.
> GHA: change "docker-compose" to "docker compose" for the release workflow

- app/config/config.yml
- app/config/parameters.yml.dist
- src/OpenConext/EngineBlockBundle/Configuration/TestFeatureConfiguration.php
- src/OpenConext/EngineBlockBundle/Controller/IdentityProviderController.php
- src/OpenConext/EngineBlockBundle/Resources/config/controllers/authentication.yml
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Consent.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/UnsolicitedSingleSignOnDisabled.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Resources/config/controllers.yml
> Add feature flag to disable IdP-initiated authentication flow

- src/OpenConext/EngineBlock/Metadata/MfaEntityCollection.php
Make it clear where this occurs (MFA list) and mention the ID that's duplicated
> Improve error message on duplicate SP entityID in PUSH

- library/EngineBlock/Corto/Filter/Command/AddIdentityAttributes.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/NameIdFormat.feature
Due to the NameId juggling taking place during the Input filtering. There MUST be a point in time when we set the correct outgoing NameId value and format. And that is done in the AddIdentityAttributes filter.
During the optimization I moved the 'were done here' return statement to a block that seemed to make more sense to me. But that caused the NameId from not being set even though it was resolved.
So I moved that block back to the position where it is supposed to be.
It is meant as a guard from injustly overwriting the eduPersonTargettedId. Not for preventing the setting of the correct NameId in the subject.
Fixes: #1318
> Ensure the NameID is correctly set

- src/OpenConext/EngineBlock/Service/ReleaseAsEnforcer.php
- tests/unit/OpenConext/EngineBlock/Service/ReleaseAsEnforcerTest.php
When Manage configures an override for an attribute name. But the targetted attribute is not in the assertion, then Engine would add an empty attribute with the overridden value to the assertion. The SAML2 lib would then warn us that an empty attribute value can not be processed.
To fix that. I added a test statement that verifies if the targetted attribute is present in the assertion. If not, the substitution is not made and a warning is logged.
See, Fixes: https://github.com/OpenConext/OpenConext-engineblock/issues/1321
> Prevent adding empty renamed attribute

- library/EngineBlock/Corto/Module/Service/StepupAssertionConsumer.php
This should always be the case, we request a LoA from Stepup for NameID A, then we should receive a response that contains that same NameID A. This is defense in depth, should at some point in the entire chain another check fail and an adversary be able to switch or replay assertions, this will guard against them being accepted by Engineblock as valid.
> Stepup ACS: add check that returned NameID matches the one we requested.

- app/config/parameters.yml.dist
For new installs this makes sense - the scope check is only done when you add scopes in Manage anyway, but if you add them, it's a safer default that they are actually enforced.
The feature flag mostly exists to phase in scopes where you previously not had enabled them, so you want to start logging first.
> Default feature block_user_on_violation to on

- docker/Dockerfile.prod
- docker/conf/logging.yml
Since Docker logs to stdout, the ident to distinguish between the authentication and application logs is no longer applicable.  
Furthermore, logging using the regular formatters lead to all logs landing in a single line, making it hard to read and distinguish. It also hits the 16KB logline length of Docker
Using the syslog formatter fixes those issues.
> Docker: Log to json, fixes multiline logging in Docker

- library/EngineBlock/Corto/Module/Service/AssertionConsumer.php
- library/EngineBlock/Corto/Module/Service/StepupAssertionConsumer.php
This value is not the keyID but the original authnrequest ID. This is superfluous as EB log messages already log tracing information in the session_id and request_id parameters that are logged with every message. Just leave out this confusingly named value.
Closes: #1343
> Remove confusing key_id from stepup callout logging

- library/EngineBlock/Validator/Urn.php
- tests/library/EngineBlock/Test/Validator/UrnTest.php
To prevent false positives, we can make use of the [PCRE_DOLLAR_ENDONLY](https://www.php.net/manual/en/reference.pcre.pattern.modifiers.php) flag (`D`) that will constraint the `$` anchor to match the end of the string only, not a newline character.
> Bugfix: stricter regex; disallow trailing newline

- theme/base/stylesheets/classes.scss
Prior to this change, long uninterruptible strings would cause a linebreak that was not visually pleasing, mainly identifiers. This change widens the container so linebreaks for identifiers occur less.
Resolves https://github.com/OpenConext/OpenConext-engineblock/issues/1324
> Make content container slightly wider

- library/EngineBlock/Application/TestDiContainer.php
- library/EngineBlock/Corto/Filter/Command/EnforcePolicy.php
- library/EngineBlock/Exception/PdpCheckFailed.php
- tests/library/EngineBlock/Test/Corto/Filter/Command/EnforcePolicyTest.php
Prior to this change, mulitple stacktraces would be printed in the logs when this error occured without making it clear which error was triggered. This change ensures a specific exception gets thrown so it won't trigger the exception stack dump.
Fixes https://github.com/OpenConext/OpenConext-engineblock/issues/1285
> Improve handling of PDP timeout error

- theme/base/templates/modules/Authentication/View/Proxy/debug-idp-mail.txt.twig
- theme/openconext/templates/modules/Authentication/View/Proxy/debug-idp-mail.txt.twig
Prior to this change, the idp debug email was difficult to read, especially when there was no translated attribute name available. This change improves the formatting and readability of the mail.
Fixes https://github.com/OpenConext/OpenConext-engineblock/issues/1330
> Improve IDP debug email

- src/OpenConext/EngineBlock/Metadata/AttributeReleasePolicy.php
- src/OpenConext/EngineBlockBundle/Controller/Api/ConnectionsController.php
- tests/library/EngineBlock/Test/Arp/AttributeReleasePolicyTest.php
Validate numeric key in ARP settings on metadata push.
https://github.com/OpenConext/OpenConext-engineblock/issues/1336
> Add ARP numeric key exception

- library/EngineBlock/Corto/ProxyServer.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MinkContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/SessionIndex.feature
This was a privacy issue because this allows different SP to correlate users, defeating persistent and transient NameID mechanisms. https://github.com/OpenConext/OpenConext-engineblock/issues/41
> Use assertion id for session index

- src/OpenConext/EngineBlock/Metadata/Coins.php
- src/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssembler.php
- src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
- tests/integration/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssemblerTest.php
- tests/integration/OpenConext/EngineBlock/Metadata/Entity/Assembler/fixtures/metadata_coin_collab.json
- tests/unit/OpenConext/EngineBlock/Metadata/Factory/Factory/ServiceProviderFactoryTest.php
Prior to this change, the coin value was ignored.
Within the `coin:collab_enabled`, EB will not know wheter to perform an external SBS authorization check (not yet implemented).
This change reads and stores `coin:collab_enabled` from the metadata push for ServiceProviders.
See https://github.com/OpenConext/OpenConext-engineblock/issues/1804
> Read & store metadata coin collab_enabled

- app/config/config.yml
Prior to this change, doctrine would generate database migrations erroneously. It should not update anything.
This change sets the correct MariaDB version, so doctrine no longer detects changes.
> Fix: Use correct database engine version

- app/config/config.yml
- app/config/config_ci.yml
- app/config/config_test.yml
This is needed so the correct migrations are generated.
> Correct the db server version based on production.

- languages/messages.en.php
- languages/messages.nl.php
- languages/messages.pt.php
- library/EngineBlock/Corto/Exception/UnknownIdentityProviderSigningKey.php
- library/EngineBlock/Corto/Module/Bindings.php
- src/OpenConext/EngineBlockBundle/Controller/FeedbackController.php
- src/OpenConext/EngineBlockBundle/EventListener/RedirectToFeedbackPageExceptionListener.php
- src/OpenConext/EngineBlockBundle/Resources/config/routing/feedback.yml
- theme/base/templates/modules/Authentication/View/Feedback/unknown-signing-key.html.twig
- theme/openconext/templates/modules/Authentication/View/Feedback/unknown-signing-key.html.twig
An explicit IdP signing key check is added for easier debugging.
The ease of debugging should outweigh the drawbacks of moving the responsibility of the SAML2 library also to EB and the performance penalties for doing this twice.
https://github.com/OpenConext/OpenConext-engineblock/issues/1328
> Add explicit IdP signing key feedback

- library/EngineBlock/Corto/ProxyServer.php
- src/OpenConext/EngineBlock/Metadata/Coins.php
- src/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssembler.php
- src/OpenConext/EngineBlock/Metadata/Entity/Disassembler/CortoDisassembler.php
- src/OpenConext/EngineBlock/Metadata/Entity/IdentityProvider.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MfaEntitiesContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockSpContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/MfaAuthnContextClassRef.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Fixtures/ServiceRegistryFixture.php
As discussed on Slack with Peter, I have a use-case for sending a custom RequestedAuthnContext towards an IdP _by default_. MfaEntities-settings always take precedence over this default value.
> Feat: configurable default RequestedAuthnContext

- app/config/config.yml
- app/config/parameters.yml.dist
- library/EngineBlock/Application/DiContainer.php
- library/EngineBlock/Corto/Module/Service/AssertionConsumer.php
- library/EngineBlock/Corto/ProxyServer.php
- src/OpenConext/EngineBlock/Stepup/StepupGatewayCallOutHelper.php
- src/OpenConext/EngineBlock/Stepup/StepupGsspUserAttributeExtension.php
- src/OpenConext/EngineBlockBundle/Configuration/TestFeatureConfiguration.php
- src/OpenConext/EngineBlockBundle/Resources/config/services.yml
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/EngineBlockContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Stepup.feature
This will add a feature to send a configurable set of attributes to Stepup. It shall be used to be able to validate an AzureMFA GSSP without the need to register it first in Stepup.
https://github.com/OpenConext/OpenConext-engineblock/issues/1826
> Allow configurable user attributes for Stepup

- theme/base/templates/modules/Authentication/View/Feedback/partial/saml_response_form.html.twig
- theme/base/templates/modules/Authentication/View/IdentityProvider/request-access.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/defaultAttribute.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/engineBlockAttribute.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/toggleCheckbox.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/ctas.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/idpRow.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/Shared/spinner.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/contentHeader.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp/idpForm.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/noAccess/requestForm.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/preselection.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/rememberChoice.html.twig
- theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/search.html.twig
- theme/openconext/templates/modules/Authentication/View/IdentityProvider/request-access.html.twig
- theme/openconext/templates/modules/Authentication/View/Proxy/consent.html.twig
- theme/openconext/templates/modules/Authentication/View/Proxy/debug-idp-response.html.twig
- theme/openconext/templates/modules/Authentication/View/Proxy/wayf.html.twig
Fixes various cases reported in the W3c HTML validator
> Remove trailing slash on void elements

- library/EngineBlock/Corto/Filter/Command/EnforcePolicy.php
- src/OpenConext/EngineBlock/Metadata/Coins.php
- src/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssembler.php
- src/OpenConext/EngineBlock/Metadata/Entity/IdentityProvider.php
- src/OpenConext/EngineBlock/Stepup/StepupEntityFactory.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockIdpContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockSpContext.php
- src/OpenConext/EngineBlockFunctionalTestingBundle/Features/PolicyEnforcement.feature
- src/OpenConext/EngineBlockFunctionalTestingBundle/Fixtures/ServiceRegistryFixture.php
- tests/integration/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssemblerTest.php
- tests/library/EngineBlock/Test/Corto/Filter/Command/EnforcePolicyTest.php
Prior to this change, the policyEnforcementDecisionRequired coin would only function for serviceproviders. This change reads the policyEnforcementDecisionRequired coin for Identity providers as well.
See https://github.com/OpenConext/OpenConext-engineblock/issues/1857
> Allow IdP to trigger PDP callout
