OpenConext/OpenConext-engineblock

app/AppKernel.php
app/config/security.yml
application/configs/application.ini
src/OpenConext/EngineBlock/ApiBundle/Resources/config/services.yml
src/OpenConext/EngineBlock/ApiBundle/Service/FeaturesService.php

Supersedes #203.
Part of [Create a new API user in EngineBlock](https://www.pivotaltracker.com/story/show/106403426)

Add new API user and role for Profile

---

composer.json
composer.lock
library/EngineBlock/Database/ConnectionFactory.php
src/OpenConext/EngineBlock/Authentication/Entity/Consent.php
src/OpenConext/EngineBlock/Authentication/Exception/InvalidArgumentException.php
src/OpenConext/EngineBlock/Authentication/Repository/ConsentRepository.php
src/OpenConext/EngineBlock/AuthenticationBundle/Resources/config/repositories.yml
src/OpenConext/EngineBlock/CompatibilityBundle/Resources/config/services.yml

https://www.pivotaltracker.com/story/show/107288656
Includes some unrelated docblock changes.

Allow querying of consents for a particular user

---

languages/en.php
languages/nl.php

These translations have been added on master, but not develop.

Update from master

---

tests/library/EngineBlock/Test/Corto/Module/Service/ProcessConsentTest.php
tests/library/EngineBlock/Test/Corto/Module/Service/ProvideConsentTest.php

Also fixes typo in test name.
[Ticket 110963664](https://www.pivotaltracker.com/story/show/110963664)

Fixes tests to use updated API

---

composer.json
composer.lock
database/patch/patch-0023.sql
database/patch/patch-0024.sql
src/OpenConext/EngineBlock/ApiBundle/Dto/Consent.php

Part of [Ticket 107474726](https://www.pivotaltracker.com/story/show/107474726)
Updates metadata and adds support urls to service providers accessible through the consent API.
Also updates dbpatches to keep patches 'in sync' between branches.

Add url to service provider

---

.travis.php.ini
.travis.yml

[Ticket 111133268](https://www.pivotaltracker.com/story/show/111133268)
See PR #241.

Add travis config

---

.travis.php.ini
.travis.yml
composer.json
composer.lock
database/patch/patch-0023.sql
database/patch/patch-0024.sql
src/OpenConext/EngineBlock/ApiBundle/Dto/Consent.php
tests/library/EngineBlock/Test/Corto/Module/Service/ProcessConsentTest.php
tests/library/EngineBlock/Test/Corto/Module/Service/ProvideConsentTest.php

Brings refactor up-to-date with dev.

Update from 5.x-dev

---

composer.json
composer.lock
library/EngineBlock/Corto/Module/Bindings.php
library/EngineBlock/Corto/Module/Service/AssertionConsumer.php

Adds logging of signature method algorithms of sent AuthnRequests and incoming Assertions.
[Ticket 110650550](https://www.pivotaltracker.com/story/show/110650550)
[Issue 202](https://github.com/OpenConext/OpenConext-engineblock/issues/202)

Log signing algorithms

---

app/AppKernel.php
app/config/config.yml
composer.json
composer.lock
src/OpenConext/EngineBlock/CompatibilityBundle/DependencyInjection/OpenConextEngineBlockCompatibilityExtension.php
src/OpenConext/EngineBlock/CompatibilityBundle/Resources/config/services.yml

[Ticket 111131930](https://www.pivotaltracker.com/story/show/111131930)

Adds logger based on existing configuration

---

application/configs/application.ini
library/AttributeAggregation/Client.php
library/AttributeAggregation/Request.php
library/EngineBlock/Corto/Filter/Command/AttributeAggregator.php
library/EngineBlock/Corto/Filter/Input.php
library/EngineBlock/Corto/Filter/Output.php

Feature branch for attribute aggregation in EB for 5.x branch.

Added Attribute Aggregation as Corto inbound filter

---

bin/migrate_etc.php
database/patch/patch-0001.php
library/EngineBlock/Application/Bootstrapper.php

Renamed surfnet pointers to have a cleaner OpenConext base when checking out.

De-SURFnet Engineblock

---

composer.json
composer.lock

See https://github.com/ramsey/uuid/issues/80 for in depth info regarding the collision issue when generating random UUIDs.

Updated ramsey/uuid to prevent UUID collisions

---

src/OpenConext/EngineBlockBundle/Resources/config/routing.yml

see ~~https://www.pivotaltracker.com/story/show/117599315~~ https://www.pivotaltracker.com/story/show/117599373

Allow POST request for debugging sp

---

src/OpenConext/EngineBlockBridge/ResponseFactory.php
src/OpenConext/EngineBlockBundle/Controller/MetadataController.php

see https://www.pivotaltracker.com/story/show/117599315

Return response for edugain metadata

---

composer.json
composer.lock
database/DoctrineMigrations/Version20160721121856.php

The latest version of metadata lib is used, migration is provided
Fixes #298

Use latest stable version of metadata.

---

library/EngineBlock/Corto/Filter/Command/VerifyShibMdScopingAllowsEduPersonPrincipalName.php
library/EngineBlock/Corto/Filter/Command/VerifyShibMdScopingAllowsSchacHomeOrganisation.php
tests/library/EngineBlock/Test/Corto/Filter/Command/VerifyShibMdScopingAllowsEduPersonPrincipalNameTest.php
tests/library/EngineBlock/Test/Corto/Filter/Command/VerifyShibMdScopingAllowsSchacHomeOrganisationTest.php

This is essential information to understand violations.

Log which scope the IdP was sending that fails our data.

---

.travis.yml
build.xml
library/EngineBlock/Corto/Filter/Abstract.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/AttributeManipulation.feature
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MinkContext.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockSpContext.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Fixtures/ServiceRegistryFixture.php
tests/behat.yml

Attribute Manipulation Functional Tests

---

README.md
bin/migrate_etc.php
database/patch/patch-0001.php

Replace surfconext with openconext

---

src/OpenConext/EngineBlockBundle/Controller/FeedbackController.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/ClearErrorMessages.feature
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockSpContext.php

An Unknown preselected IdP results in the correct error page

---

app/config/config.yml
application/configs/application.ini
bin/composer/dump-required-ini-params.sh
ci/travis/files/engineblock.ini
library/EngineBlock/Application/DiContainer.php
library/EngineBlock/Application/FunctionalTestDiContainer.php
library/EngineBlock/Corto/Module/Bindings.php
src/OpenConext/EngineBlockBundle/Configuration/FeatureConfiguration.php
src/OpenConext/EngineBlockBundle/Configuration/FeatureConfigurationInterface.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Bindings.feature
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/ClearErrorMessages.feature
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/EngineBlockContext.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockIdpContext.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockSpContext.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Encryption.feature
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/SpProxy.feature
src/OpenConext/EngineBlockFunctionalTestingBundle/Fixtures/FunctionalTestingFeatureConfiguration.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/MockIdentityProvider.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Resources/config/services.yml

[OpenConext-deploy PR #88](https://github.com/OpenConext/OpenConext-deploy/pull/88)
[127988169](https://www.pivotaltracker.com/story/show/127988169)
[127987893](https://www.pivotaltracker.com/story/show/127987893)

SAML feature toggles

---

.travis.yml
build.xml

Unit tests and integration tests should not only be run locally (i.e. in the pre-commit hook), but also during CI.

Run unit and integration tests in Travis

---

README.md

Also standardized the layout and used markdown styles a bit.

Include development wiki page

---

src/OpenConext/EngineBlock/Service/MetadataService.php
src/OpenConext/EngineBlockBundle/Controller/Api/AttributeReleasePolicyController.php
src/OpenConext/EngineBlockBundle/Exception/InvalidArgumentException.php
src/OpenConext/EngineBlockBundle/Http/Request/JsonRequestHelper.php
src/OpenConext/EngineBlockBundle/Http/Response/JsonResponse.php
src/OpenConext/EngineBlockBundle/Resources/config/compat.yml
src/OpenConext/EngineBlockBundle/Resources/config/controllers/api.yml
src/OpenConext/EngineBlockBundle/Resources/config/routing_api.yml
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/AttributeManipulation.feature
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/AttributeManipulationWithAllManipulationsBeforeConsent.feature
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/AttributeReleasePolicy.feature
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/AttributeReleasePolicyWithAllManipulationsBeforeConsent.feature
tests/unit/OpenConext/EngineBlockBundle/Controller/AttributeReleasePolicyControllerTest.php

This implements OpenConext/OpenConext-Profile#51.
Relates to OpenConext/OpenConext-Profile#70.

Add ARP API in order to let clients apply ARPs to a set of attributes

---

library/EngineBlock/Corto/Module/Service/SingleSignOn.php
library/EngineBlock/Corto/ProxyServer.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockSpContext.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/StatusCodes.feature
src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/MockServiceProvider.php

[127716497](https://www.pivotaltracker.com/story/show/127716497)
#166 
Sub status codes should be nested in a higher level status code.
Functional tests have been added to make sure this is done correctly.

Nest sub status codes

---

library/Pdp/Client.php

[127343041](https://www.pivotaltracker.com/story/show/127343041)

Remove hard-coded support email address from PEP/PDP exceptions

---

.travis.yml
composer.json
composer.lock
library/EngineBlock/Saml2/AuthnRequestFactory.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/AuthnRequest.feature
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/EngineBlockContext.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/SingleSignOn.feature
tests/library/EngineBlock/Test/Corto/ProxyServerTest.php

See: #371 and https://github.com/simplesamlphp/saml2/commit/aecda70e72970c8d66af1d18d5b762a8df5731ed

Backport allow create fix

---

library/EngineBlock/User.php
src/OpenConext/EngineBlock/Authentication/Value/CollabPersonId.php
src/OpenConext/EngineBlockBridge/Authentication/Repository/UserDirectoryAdapter.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/AttributeManipulation.feature
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/AttributeManipulationWithAllManipulationsBeforeConsent.feature
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockIdpContext.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/LdapCompatibility.feature
src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/FakeUserDirectory.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/MockIdentityProvider.php
tests/unit/OpenConext/EngineBlock/Authentication/Value/CollabPersonIdTest.php
tests/unit/OpenConext/EngineBlockBridge/Authentication/Repository/UserDirectoryAdapterTest.php
tests/unit/OpenConext/EngineBlockBundle/Doctrine/Type/CollabPersonIdTypeTest.php

See: [134915765](https://www.pivotaltracker.com/story/show/134915765), #360 and #364.

Backport LDAP fix to 5.1

---

library/EngineBlock/Corto/Filter/Command/AttributeAggregator.php

This is a common case so not really deserving of notice status.

Make "No Attribute Aggregation for $SP" log message level info.

---

src/OpenConext/EngineBlock/Http/HttpClient.php
src/OpenConext/EngineBlockBundle/Pdp/PdpClient.php
src/OpenConext/EngineBlockBundle/Resources/config/services.yml

Bugfix: PDP client configuration

---

.travis.yml

* Specify manually installing APCU as this has been included in Travis (travis-ci/php-src-builder@a846a53)
* Remove 5.3 specific command from .travis.yml

Update travis apcu installation

---

library/EngineBlock/View.php

https://www.pivotaltracker.com/story/show/142487713
The result of the expression isn't used or captured in a variable, so it's dead code and should be removed.

Remove dead code from View.php

---

library/EngineBlock/Corto/Filter/Command/LogLogin.php
src/OpenConext/EngineBlock/Logger/AuthenticationLogger.php
src/OpenConext/EngineBlockBridge/Logger/AuthenticationLoggerAdapter.php
tests/unit/OpenConext/EngineBlock/Logger/AuthenticationLoggerTest.php
tests/unit/OpenConext/EngineBlockBridge/Logger/AuthenticationLoggerAdapterTest.php
tests/unit/OpenConext/Mockery/Matcher/ValueObjectListEqualsMatcher.php

Resolves https://www.pivotaltracker.com/story/show/118569209

Log the proxied service providers as part of the authentication log

---

database/DoctrineMigrations/Version20170331145533.php

Resolves https://www.pivotaltracker.com/story/show/116960181

Add a migration that drops the `log_logins` table

---

languages/en.php
languages/nl.php

Suggested improvements by our support team.

Updated EN/NL error texts.

---

src/OpenConext/EngineBlock/Authentication/Repository/ConsentRepository.php
src/OpenConext/EngineBlock/Service/ConsentService.php
src/OpenConext/EngineBlockBundle/Authentication/Repository/DbalConsentRepository.php
src/OpenConext/EngineBlockBundle/Resources/config/repositories.yml

https://www.pivotaltracker.com/story/show/117679053

Move ConsentRepository to EngineBlockBundle

---

README.md

Related to https://www.pivotaltracker.com/story/show/142941799
See https://github.com/OpenConext/OpenConext-engineblock/pull/411#issuecomment-297030991

Remove references to LDAP from the README

---

Makefile
app/AppKernel.php
build.xml

Depends on https://github.com/OpenConext/OpenConext-deploy/pull/130
Make a working development environment

Development Environment issues.

---

composer.lock

Previous version: 1.14.12
New version: 1.14.15
Security updates included since 1.14.12:
- 201704-01 Unauthenticated encryption in CBC mode
- 201704-02 Authentication context bypass in the multiauth module
- 201705-01 Session fixation issue and authentication bypass
- 201708-01 Invalid token creation and validation
More info on simplesamlphp.org:
- https://simplesamlphp.org/security/201704-01
- https://simplesamlphp.org/security/201704-02
- https://simplesamlphp.org/security/201705-01
- https://simplesamlphp.org/security/201708-01

Update simplesamlphp to version 1.14.15

---

composer.lock

Does not affect us, just to silence checkers.

Update simplesamlphp/simplesamlphp for security issue

---

library/EngineBlock/Corto/Adapter.php
library/EngineBlock/Corto/Filter/Command/ValidateRequiredAttributes.php
library/EngineBlock/Corto/Mapper/Metadata/Entity/SpSsoDescriptor/AssertionConsumerServices.php
library/EngineBlock/Corto/Mapper/Metadata/Entity/SpSsoDescriptor/AttributeConsumingService/RequestedAttributes.php
library/EngineBlock/Ssp/sspmod/saml/Message.php
src/OpenConext/EngineBlock/Metadata/Entity/AbstractRole.php
src/OpenConext/EngineBlock/Metadata/Entity/IdentityProvider.php
src/OpenConext/EngineBlock/Metadata/MetadataRepository/Visitor/CompositeVisitor.php
src/OpenConext/EngineBlock/Metadata/MetadataRepository/Visitor/DisableDisallowedEntitiesInWayfVisitor.php
src/OpenConext/EngineBlock/Service/ConsentServiceInterface.php
src/OpenConext/EngineBlockBridge/Configuration/EngineBlockConfiguration.php
src/OpenConext/EngineBlockBundle/Authentication/AuthenticationLoopGuard.php
src/OpenConext/EngineBlockBundle/Controller/IdentityProviderController.php
src/OpenConext/EngineBlockBundle/Controller/ServiceProviderController.php

This was mentioned in #479 as part of a project wide code inspection
but wasn't realy part of that PR. This commit cleans up those points.

Removed unused imports

---

src/OpenConext/EngineBlockFunctionalTestingBundle/Fixtures/ServiceRegistryFixture.php

Instead of regarding all entities in the 'service registry fixture' as
being of type AbstractRole, we now make a clear distinction between
SPs and IDPs so it can be easily verified with static analysis that
all properties used are actually defined on the type at hand.
For example:
- attributeReleasePolicy is a property of ServiceProvider
- getEntity(.., 'sp')->attributeReleasePolicy is wrong, since it
cannot be guaranteed to return a ServiceProvider in code (return
types) or annotations

Distinguish SP from IDP in ServiceRegistryFixture

---

app/Resources/views/modules/Authentication/View/Proxy/discover.phtml
theme/material/templates/modules/Authentication/View/Proxy/discover.phtml

DisplayName should have preference over the technical name

Reverse name/displayName order

---

UPGRADING.md

Although there are many changes in this release, only two might
require manual intervention on upgrade.
https://www.pivotaltracker.com/story/show/154966773

Add upgrade instructions for release 5.7

---

library/EngineBlock/Attributes/Validator/Type.php
library/EngineBlock/Validator/Uri.php
library/EngineBlock/Validator/Urn.php
tests/library/EngineBlock/Test/Attributes/Validator/TypeTest.php

See: https://www.pivotaltracker.com/story/show/155358923

Replace usage of Zend_Validate and Zend_Uri

---

library/EngineBlock/Corto/Module/Service/ProvideConsent.php
src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/Locale.php
theme/material/templates/layouts/scripts/default.html.twig
theme/material/templates/layouts/scripts/language-switcher.html.twig
theme/material/templates/modules/Authentication/View/Feedback/authorization-policy-violation.html.twig
theme/material/templates/modules/Authentication/View/Feedback/custom.html.twig
theme/material/templates/modules/Authentication/View/Feedback/invalid-acs-binding.html.twig
theme/material/templates/modules/Authentication/View/Feedback/invalid-acs-location.html.twig
theme/material/templates/modules/Authentication/View/Feedback/missing-required-fields.html.twig
theme/material/templates/modules/Authentication/View/Feedback/no-consent.html.twig
theme/material/templates/modules/Authentication/View/Feedback/no-idps.html.twig
theme/material/templates/modules/Authentication/View/Feedback/received-error-status-code.html.twig
theme/material/templates/modules/Authentication/View/Feedback/received-invalid-response.html.twig
theme/material/templates/modules/Authentication/View/Feedback/received-invalid-signed-response.html.twig
theme/material/templates/modules/Authentication/View/Feedback/session-lost.html.twig
theme/material/templates/modules/Authentication/View/Feedback/stuck-in-authentication-loop.html.twig
theme/material/templates/modules/Authentication/View/Feedback/unable-to-receive-message.html.twig
theme/material/templates/modules/Authentication/View/Feedback/unknown-issuer.html.twig
theme/material/templates/modules/Authentication/View/Feedback/unknown-preselected-idp.html.twig
theme/material/templates/modules/Authentication/View/Feedback/unknown-service-provider.html.twig
theme/material/templates/modules/Authentication/View/Feedback/unknown-service.html.twig
theme/material/templates/modules/Authentication/View/Feedback/unsupported-signature-method.html.twig
theme/material/templates/modules/Authentication/View/Proxy/consent-slidein-contact-details.html.twig

After the many changes in #497, this PR aims to remedy any bugs introduced during the migration from Zend_Layout to Twig.
See commit messages for more details on the specific bug fixes.

Twig conversion bugs

---

src/OpenConext/EngineBlockBundle/Controller/Api/AttributeReleasePolicyController.php

Previously we only allowed GET requests on the readArp endpoint. This
limited the number of entity id's that could be passed to the endpoint
as the query string is limited ot a certain length before it is cut off
By moving from a GET to a POST request we remedy this problem.
This change is made to be compatible with EB 5.5, hence the merge target: `release/5.5`
This PR is part of the fix for the following [bug](https://www.pivotaltracker.com/story/show/155497459)

Allow only POST requests on readArpAction

---

src/OpenConext/EngineBlock/Authentication/Dto/Consent.php

See: https://www.pivotaltracker.com/story/show/154912300

Send NameIDFormat of SP to profile in the consent API

---

src/OpenConext/EngineBlock/Authentication/Dto/Consent.php

See: https://www.pivotaltracker.com/story/show/107474726

Send support URLs of SP to profile in the consent API

---

composer.lock

Resolves the following security issues:
* CVE-2018-11407: CVE-2018-11407: Unauthorized access on a misconfigured LDAP server when using an empty password
https://symfony.com/cve-2018-11407
* CVE-2018-11386: CVE-2018-11386: Denial of service when using PDOSessionHandler
https://symfony.com/cve-2018-11386
* CVE-2018-11406: CVE-2018-11406: CSRF Token Fixation
https://symfony.com/cve-2018-11406
* CVE-2018-11408: CVE-2018-11408: Open redirect vulnerability on security handlers
https://symfony.com/cve-2018-11408
* CVE-2018-11385: CVE-2018-11385: Session Fixation Issue for Guard Authentication
https://symfony.com/cve-2018-11385

Update symfony to 2.8.41

---

src/OpenConext/EngineBlock/Metadata/Entity/Assembler/JanusPushMetadataAssembler.php

See: https://www.pivotaltracker.com/story/show/157872470

Store the support URLs to sso_provider_roles

---

src/OpenConext/EngineBlockBundle/Pdp/PolicyDecision.php

Related to issue: https://groups.google.com/forum/#!topic/openconext/Ec6Q8scnr9A

PDP: do not require a logo to function

---

library/EngineBlock/Arp/AttributeReleasePolicyEnforcer.php
library/EngineBlock/Corto/Filter/Abstract.php
library/EngineBlock/Corto/Filter/Command/Abstract.php
library/EngineBlock/Corto/Filter/Command/AttributeReleasePolicy.php
library/EngineBlock/Corto/Filter/Command/ResponseAttributeValueTypesModificationInterface.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockIdpContext.php

The AM/ARP bugfix was written as a hotfix for the 5.6 branch. This PR includes these changes for  EB 5.7.

Include Attribute manipulation / ARP bugfix in master

---

.travis.yml
library/EngineBlock/Arp/AttributeReleasePolicyEnforcer.php
library/EngineBlock/Corto/Filter/Abstract.php
library/EngineBlock/Corto/Filter/Command/Abstract.php
library/EngineBlock/Corto/Filter/Command/AttributeReleasePolicy.php
library/EngineBlock/Corto/Filter/Command/ResponseAttributeValueTypesModificationInterface.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockIdpContext.php

See #545, #541 and https://www.pivotaltracker.com/story/show/158184179 for more details. 
This is a backport to version 5.7

Include Attribute manipulation / ARP bugfix in 5.7

---

src/OpenConext/EngineBlock/Logger/AuthenticationLogger.php
src/OpenConext/EngineBlockBridge/ErrorReporter.php
src/OpenConext/EngineBlockBridge/Logger/AuthenticationLoggerAdapter.php
src/OpenConext/EngineBlockBundle/Controller/FeedbackController.php
tests/unit/OpenConext/EngineBlock/Logger/AuthenticationLoggerTest.php
tests/unit/OpenConext/EngineBlockBridge/Logger/AuthenticationLoggerAdapterTest.php
theme/material/templates/modules/Authentication/View/Feedback/authorization-policy-violation.html.twig
theme/material/templates/modules/Default/View/Error/error.html.twig

Cherry picks of #539 and #551  for the benefit of backporting this functionality to EB 5.7

Backport PDP and Workflow state logging to EB 5.7

---

composer.lock

See Pivotal: https://www.pivotaltracker.com/story/show/158438628

Upgrade SAML2 to 3.1.6

---

src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/Debug.php
src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/Feedback.php
src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/Locale.php
src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/Metadata.php
src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/UserAgent.php
theme/material/templates/layouts/scripts/default.html.twig
theme/material/templates/layouts/scripts/language-switcher.html.twig
theme/material/templates/modules/Authentication/View/Proxy/consent.html.twig

Backport of #563 to the current release

Backport twig xss vulnerability hardening to 5.7

---

library/EngineBlock/Corto/Filter/Command/VerifyShibMdScopingAllowsEduPersonPrincipalName.php
library/EngineBlock/Corto/Filter/Command/VerifyShibMdScopingAllowsSchacHomeOrganisation.php
library/EngineBlock/Corto/ProxyServer.php
src/OpenConext/EngineBlock/Metadata/MetadataRepository/DoctrineMetadataRepository.php

See https://www.pivotaltracker.com/story/show/115227481

Remove 5.3 compatibility

---

CHANGELOG.md
build.xml
ci/travis/phpcompat.xml
composer.json
composer.lock
src/OpenConext/EngineBlock/Authentication/Dto/Consent.php

Add extra codestyle commands to ant
https://www.pivotaltracker.com/story/show/115227481

Add CodeStyle fixer to the project and remove explicit PHP 5.3 compatibility

---

library/EngineBlock/Corto/ProxyServer.php

It is not right to disallow authnrequests without the protocolbinding,
since it's optional in the standard. EB only supports HTTP-POST, so that
seems a sane default. Further strengthened by saml2int's statement that
"The ProtocolBinding attribute, if present, MUST be set to
urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST."

ProtocolBinding is not a mandatory field. Assume HTTP-POST if it's lacking

---

languages/messages.nl.php

Fix translations

---

.editorconfig
theme/.editorconfig

The editorconfigs reflects current styling

Add an editorconfig

---

.travis.yml
languages/messages.en.php
languages/messages.nl.php
languages/messages.pt.php
library/EngineBlock/Corto/Module/Services.php
library/EngineBlock/Corto/ProxyServer.php
src/OpenConext/EngineBlockBundle/Authentication/AuthenticationState.php
src/OpenConext/EngineBlockBundle/Controller/FeedbackController.php
src/OpenConext/EngineBlockBundle/EventListener/RedirectToFeedbackPageExceptionListener.php
src/OpenConext/EngineBlockBundle/Resources/config/routing/feedback.yml
src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/Feedback.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/ClearErrorMessages.feature
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/EngineBlockContext.php
tests/phpunit.xml
tests/unit/OpenConext/EngineBlockBundle/Authentication/AuthenticationStateTest.php
theme/material/templates/modules/Authentication/View/Feedback/session-not-started.html.twig

The session exception needs te be differentiated based on lost
or not started.
https://www.pivotaltracker.com/story/show/164076545

Differentiate session exception

---

languages/messages.en.php
languages/messages.nl.php
languages/messages.pt.php
theme/material/stylesheets/error-page/_vars.css.sass
theme/material/stylesheets/error-page/base/_page.css.sass
theme/material/stylesheets/error-page/components/_language.css.sass
theme/material/stylesheets/error-page/error-page.sass
theme/material/stylesheets/error-page/modules/_background.sass
theme/material/stylesheets/error-page/modules/error-container/_error-container.css.sass
theme/material/stylesheets/error-page/modules/error-details/_error-details.css.sass
theme/material/stylesheets/error-page/modules/feedback-info/_feedback-info.css.sass
theme/material/stylesheets/error-page/modules/footer/_footer.css.sass
theme/material/templates/modules/Default/View/Error/error.html.twig
theme/material/templates/modules/Default/View/Error/partial/footer.html.twig

The different commits should provide you with context about the changes undertaken.
~~In addition to making the page responsive, I've added a watch styles grunt task. Which will be removed with the introduction of #672 I gues~~ I dropped that commit from this PR
This PR covers task 3 of this [Pivotal story](https://www.pivotaltracker.com/story/show/164121204)

Make the error page responsive for small viewports

---

languages/messages.en.php
languages/messages.nl.php
languages/messages.pt.php

The translations were discussed so now we have the latest version to
show the enduser.
https://www.pivotaltracker.com/story/show/164076545

Add the session exception translations

---

src/OpenConext/EngineBlockBundle/Authentication/AuthenticationState.php
tests/unit/OpenConext/EngineBlock/Validator/AcsRequestValidatorTest.php
tests/unit/OpenConext/EngineBlock/Validator/SsoRequestValidatorTest.php
tests/unit/OpenConext/EngineBlockBundle/Authentication/AuthenticationStateTest.php

The validator tests needed to be updated and not only the messages used.

Fix validator tests on messages

---

composer.lock

A specific security upgrade was installed and a more general package upgrade was performed.

Security upgrade and more

---

src/OpenConext/EngineBlockFunctionalTestingBundle/Controllers/FeedbackController.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Resources/config/controllers.yml
src/OpenConext/EngineBlockFunctionalTestingBundle/Resources/config/routing.yml

Added a test endpoint for exceptions.
https://www.pivotaltracker.com/story/show/165593518

Add test endpoint for exceptions

---

README.md
theme/.browserslistrc

The current browsers we are supporting are updated.
https://www.pivotaltracker.com/story/show/165377239

Update the browser support

---

src/OpenConext/EngineBlock/Validator/UnsolicitedSsoRequestValidator.php
src/OpenConext/EngineBlockBundle/Controller/IdentityProviderController.php
src/OpenConext/EngineBlockBundle/Resources/config/controllers/authentication.yml
src/OpenConext/EngineBlockBundle/Resources/config/services.yml
tests/unit/OpenConext/EngineBlock/Validator/UnsolicitedSsoRequestValidatorTest.php

The validator ensures the user is using a GET request with the sp-entity-id.
Resolves task 1 of https://www.pivotaltracker.com/story/show/165821300
:warning: Also cherry-pick the commit(s) from this branch on `master`

Unsolicited request validation

---

theme/package-lock.json
theme/package.json

Revert the tar resolution because the vulnerability is
patched in node-tar.
https://github.com/npm/node-tar/issues/212

Revert tar resolution

---

theme/material/stylesheets/theme/openconext/error-page/_background.sass

See point 9 of https://www.pivotaltracker.com/story/show/166437858

Make language switcher visible once again

---

theme/material/stylesheets/error-page/modules/_error-title.sass

The change resembles that of point 7 (#706)
Resolves point 6 of https://www.pivotaltracker.com/story/show/166437858

Allow overflow-wrap anywhere in the error title

---

application/configs/attributes-v2.2.0.json

A surf defined attribute, see https://wiki.surfnet.nl/display/surfconextdev/Attributen+in+SURFconext#AttributeninSURFconext-eckidECKID

 Add new attribute eckId

---

theme/package-lock.json

Lodash had a vulnerability and this PR will fix that.

Fix lodash vulnerability

---

.travis.yml
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MinkContext.php
theme/package.json

There was a mismatch between Chrome and the used Chromedrivers.

Update Selenium to fix the Selenium tests

---

languages/messages.en.php
languages/messages.nl.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/ClearErrorMessages.feature
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Encryption.feature
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/PolicyEnforcement.feature
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/SpProxy.feature

As preparation for the new error page designs.

Improved error texts

---

app/config/config.yml
app/config/parameters.yml
app/config/parameters.yml.dist
src/OpenConext/EngineBlockBundle/Configuration/ErrorFeedbackConfiguration.php
src/OpenConext/EngineBlockBundle/Configuration/ErrorFeedbackConfigurationInterface.php
src/OpenConext/EngineBlockBundle/Configuration/IdPContactPage.php
src/OpenConext/EngineBlockBundle/DependencyInjection/Configuration.php
src/OpenConext/EngineBlockBundle/DependencyInjection/OpenConextEngineBlockExtension.php
src/OpenConext/EngineBlockBundle/Resources/config/services.yml
src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/Feedback.php
src/OpenConext/EngineBlockBundle/Value/FeedbackInformationMap.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/ClearErrorMessages.feature
tests/unit/OpenConext/EngineBlockBundle/Configuration/ErrorFeedbackConfigurationTest.php
tests/unit/OpenConext/EngineBlockBundle/Configuration/IdPContactPageTest.php
theme/material/javascripts/tests/visual-regression/error-page/Footer.test.js
theme/material/templates/modules/Default/View/Error/partial/footer.html.twig

For details: https://www.pivotaltracker.com/story/show/165742809

Conditionally show a IdP support link on error pages

---

languages/messages.en.php
languages/messages.nl.php

Some messages were faulty and needed to be fixed.
https://www.pivotaltracker.com/story/show/166729843

Fix sfo messages

---

library/EngineBlock/Corto/Module/Service/StepupAssertionConsumer.php
library/EngineBlock/Corto/ProxyServer.php
library/EngineBlock/Saml2/AuthnRequestFactory.php
src/OpenConext/EngineBlockBundle/Stepup/StepupEntityFactory.php
src/OpenConext/EngineBlockBundle/Stepup/StepupGatewayCallOutHelper.php
src/OpenConext/EngineBlockBundle/Stepup/StepupGatewayLoaMapping.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/MockStepupGateway.php
tests/unit/OpenConext/EngineBlockBundle/Stepup/StepupGatewayLoaMappingTest.php

Map the LoA back from GW to EB value.
https://www.pivotaltracker.com/story/show/166729672

Map GW LoA result back

---

.travis.yml
library/EngineBlock/Application/DiContainer.php
library/EngineBlock/Corto/Module/Bindings.php
library/EngineBlock/Corto/Module/Service/Metadata.php
library/EngineBlock/Corto/Module/Service/StepupAssertionConsumer.php
library/EngineBlock/Corto/ProxyServer.php
library/EngineBlock/Saml2/AuthnRequestFactory.php
src/OpenConext/EngineBlockBundle/Stepup/StepupEntityFactory.php
src/OpenConext/EngineBlockBundle/Stepup/StepupGatewayCallOutHelper.php
src/OpenConext/EngineBlockBundle/Stepup/StepupGatewayLoaMapping.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Mock/MockStepupGateway.php
tests/unit/OpenConext/EngineBlockBundle/Stepup/StepupGatewayLoaMappingTest.php

In order to show valid metadata to use when configuring GW a SP
needs to be used. This is fixed now.
https://www.pivotaltracker.com/story/show/166737276

Use an SP for stepup authentication entity metadata

---

.travis.yml
theme/package-lock.json
theme/package.json

Those changes were made to allow development when the build pipeline
was broken.

Revert pipeline fixes

---

UPGRADING.md
app/config/parameters.yml.dist

The UPGRADING.md file was updated. And in the process a small addition to the parameters.yml.dist file was amended. This explains how the IdP support buttons can be configured.

Improve 5.11 installation instructions

---

database/DoctrineMigrations/Version20190710141146.php
src/OpenConext/EngineBlock/Metadata/Entity/AbstractRole.php
src/OpenConext/EngineBlock/Metadata/Entity/IdentityProvider.php
src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php

The old coin columns could be cleaned now and are no longer needed.

Cleanup old coin columns

---

CHANGELOG.md
app/AppKernel.php

This to improve the application performance when clearing and warming up the dev caches.
https://www.pivotaltracker.com/story/show/169144846

Move the dev cache location to /tmp/eb_dev_cache

---

theme/package-lock.json

The puppeteer-core needed to be updated.
https://www.npmjs.com/advisories/1184

Update puppeteer-core after audit

---

src/OpenConext/EngineBlock/Xml/MetadataRenderer.php
src/OpenConext/EngineBlockBundle/Resources/config/services.yml
tests/unit/OpenConext/EngineBlock/Xml/MetadataRendererTest.php
theme/material/templates/modules/Authentication/View/Metadata/idp.xml.twig
theme/material/templates/modules/Authentication/View/Metadata/idps.xml.twig
theme/material/templates/modules/Authentication/View/Metadata/sp.xml.twig

As requested in:
https://www.pivotaltracker.com/story/show/169199410

Render the terms of use in the XML metadata

---

theme/package-lock.json

See: https://www.npmjs.com/advisories/1316

Upgrade Handlebars to 4.5.3

---

theme/package-lock.json

Npm dependencies are updated to mitigate a vulnerability.
https://nodesecurity.io/advisories/1084

Prevent mem denial of service vulnerability

---

src/OpenConext/EngineBlockFunctionalTestingBundle/Controllers/ConsentController.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Helper/TestEntitySeeder.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Resources/config/controllers.yml
src/OpenConext/EngineBlockFunctionalTestingBundle/Resources/config/routing.yml
theme/material/javascripts/tests/visual-regression/consent/ConsentPage.test.js
theme/material/javascripts/tests/visual-regression/error-page/ErrorPage.test.js
theme/material/javascripts/tests/visual-regression/error-page/Footer.test.js

Add a simple visual regression test for the consent screen.
So the upgrading of build tools/dependencies could be more easily
verified.
The security warnings will be fixed in: #839

Add visual consent test

---

theme/material/javascripts/modules/IdpListElementFactory.js
theme/material/templates/modules/Authentication/View/Proxy/wayf.html.twig

This will probably give us some speedup on SP's with larger number of IdPs.

Implement lazy loading of WAYF logos.

---

theme/package-lock.json
theme/package.json

Update used assets to latest and resolve some problems with a
resolution.

Fix NPM security warning

---

CHANGELOG.md

Added the changes from 6.2 to the changelog.

Update 6.2 release CHANGELOG.md

---

application/configs/attributes.json

The attributes in OpenConext-deploy were changed and those
changes weren't yet added to Engineblock.

Add attributes.json changes from OpenConext-deploy

---

library/EngineBlock/Saml2/AuthnRequestFactory.php
tests/library/EngineBlock/Test/Corto/ProxyServerTest.php

This reverts commit df2678a6
https://github.com/OpenConext/OpenConext-engineblock/pull/848

Revert #848 "If the SP provided a RequestedAuthnContext in the AuthnRequest, replicate this to the IdP"

---

database/DoctrineMigrations/Version20200226103409.php

To be released post EngineBlock 6.2 for rollbackability.
See: https://www.pivotaltracker.com/story/show/171625471
Also relates to: 
#835 
https://www.pivotaltracker.com/story/show/168893683

Remove the remaining eduGAIN metadafields

---

docs/configurable_authncontextclassref.md
docs/index.md

This will add documentation for the configurable authncontextclassref.
https://www.pivotaltracker.com/n/projects/1425900/search?q=label%3A%22authncontext%22

Add authncontextclassref documentation

---

library/EngineBlock/Corto/ProxyServer.php
src/OpenConext/EngineBlock/Metadata/Coins.php
src/OpenConext/EngineBlock/Metadata/Entity/Assembler/PushMetadataAssembler.php
src/OpenConext/EngineBlock/Metadata/MfaEntity.php
src/OpenConext/EngineBlock/Metadata/MfaEntityCollection.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MfaEntitiesContext.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/MfaAuthncontextclassref.feature
src/OpenConext/EngineBlockFunctionalTestingBundle/Fixtures/ServiceRegistryFixture.php
tests/behat-ci.yml
tests/behat.yml
tests/unit/OpenConext/EngineBlock/Metadata/MfaEntityCollectionTest.php

If a configured authncontextclassref is configured in the
IdP for the current SP the authncontextclassref needs to be
set to the response.
https://www.pivotaltracker.com/story/show/172718137

Add authncontextclassref to SP if configured in IdP

---

languages/messages.en.php
languages/messages.nl.php
languages/messages.pt.php
src/OpenConext/EngineBlockBundle/Controller/FeedbackController.php
src/OpenConext/EngineBlockBundle/EventListener/RedirectToFeedbackPageExceptionListener.php
src/OpenConext/EngineBlockBundle/Resources/config/routing/feedback.yml
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/ClearErrorMessages.feature
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/MfaAuthnContextClassRef.feature
theme/material/javascripts/tests/visual-regression/ErrorPage.test.js
theme/material/templates/modules/Authentication/View/Feedback/invalid-mfa-authn-context-class-ref.html.twig

**Be aware this PR is build on top on #864 so this PR needs to be reviewed first**
Add a custom error page when the response from configured MFA IdP is
invalid.
https://www.pivotaltracker.com/story/show/172718794

Add custom MFA error page

---

theme/package-lock.json

minimist 1.2.5
yargs-parser 13.1.2

Bump yargs-parser and minimist to mitigate vulnerability

---

theme/base/stylesheets/pages/wayf.scss
theme/base/stylesheets/shared.scss
theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp.html.twig
theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/search.html.twig
theme/cypress/integration/skeune/wayf/WayfShowsConnectedIdps.spec.js
theme/cypress/integration/skeune/wayf/a11y.spec.js
theme/cypress/support/commands.js
theme/skeune/translations/messages.en.php
theme/skeune/translations/messages.nl.php
theme/skeune/translations/messages.pt.php

Added preliminary integration tests for the WAYF screen in the new design.
Fixed them as far as i could for now (without interactivity) and commented on those which need to be fixed in the future.  Skipped those that can't work atm.

Add integration tests for the new WAYF

---

theme/base/stylesheets/pages/wayf.scss
theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/remainingIdps.html.twig
theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/rememberChoice.html.twig
theme/base/templates/modules/Authentication/View/Proxy/wayf_content.html.twig
theme/package.json

After conferring with Arnout and Edwin, a spot was chosen for the rememberchoice feature.  This PR moves the form to that spot (between search and idp-list) & adds some styles for it.  The styles are a proposal.

Style rememberchoice form

---

theme/base/stylesheets/mixins.scss
theme/base/stylesheets/pages/consent.scss
theme/base/stylesheets/pages/wayf.scss
theme/base/stylesheets/shared.scss

Turns out tuning the paddings and margins was enough :-)

Style the WAYF for mobile

---

theme/base/stylesheets/fonts.scss
theme/base/stylesheets/helpers.scss
theme/base/stylesheets/mixins.scss
theme/base/stylesheets/normalize.scss
theme/base/stylesheets/pages/wayf.scss
theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/preselection.html.twig
theme/package-lock.json
theme/package.json

Fix various cross-browser issues
- label needs a container to be a grid item in IE11
- margin-top auto does not work in IE11
- add font-display swap to prevent content flashes or missing text while the font is loading
- on webkit browsers the input cannot get a height unless apearance none is added
- added a background size for the account button, so it's always completely visible
- increased size of 2nd column for previousselection section to avoid the focus style being messed up in chrome/ie11
Add normalize.css as scss
Removed it as a dependency because it caused an extra request & could not be found.
Instead added it inline as per our other css
NOTE: this PR was branched off from the mobile branch. I've put the base to that one so it's easier to review.  Before merging it needs to be …

Ensure the WAYF works cross-browser

---

theme/base/javascripts/application.js
theme/base/javascripts/index.js
theme/openconext/javascripts/application.js
theme/openconext/javascripts/index.js

Utilized initializePage function
Import right index.js in both openconext/base

Refactor JS for index page

---

theme/base/javascripts/utility/setCookie.js
theme/base/javascripts/wayf/rememberChoice.js
theme/base/javascripts/wayf/submitForm.js
theme/base/javascripts/wayf/utility/sortAndReindex.js
theme/base/javascripts/wayf/utility/sortListMethods.js

Also added some security features

Add remember choice support

---

theme/README.md
theme/base/javascripts/wayf/noAccess/handleCancelNoAccess.js
theme/base/stylesheets/pages/wayf.scss
theme/base/templates/layouts/scripts/default.html.twig
theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp/idpList.html.twig
theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/noAccess/noAccess.html.twig
theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/noAccess/requestForm.html.twig
theme/base/templates/modules/Authentication/View/Proxy/wayf_content.html.twig
theme/cypress/integration/skeune/wayf/WayfGeneralBehaviour.js

Hide unconnected idps when the flag says they are not desired

Hide disconnected idps when the flag is true

---

theme/base/javascripts/consent/addA11ySupport.js
theme/base/javascripts/consent/addInteractiveAriaHandlers.js
theme/base/javascripts/utility/animateInteractiveSections.js
theme/base/javascripts/wayf/utility/switchIdpSection.js
theme/base/stylesheets/mixins.scss
theme/base/stylesheets/pages/consent.scss
theme/base/stylesheets/pages/wayf.scss
theme/base/stylesheets/shared.scss
theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/defaultAttribute.html.twig
theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/name.html.twig
theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/toggle.html.twig
theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Attributes/tooltip.html.twig
theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/ctas.html.twig
theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/disclaimerList.html.twig
theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/idpRow.html.twig
theme/base/templates/modules/Default/Partials/toggleCheckbox.html.twig
theme/skeune/translations/messages.en.php
theme/skeune/translations/messages.nl.php
theme/skeune/translations/messages.pt.php

Add animations in an accessible way.  
For consent:
- tooltips
- modals
- show more button
- no consent button
For wayf:
- showing / hiding the previous/remaining section (a tad better, but couldn't really make it nice)

Add support for animations

---

theme/base/javascripts/wayf/handleEnter.js
theme/base/javascripts/wayf/handleIdpBanner.js
theme/base/javascripts/wayf/mouseBehaviour.js
theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/remainingIdps.html.twig
theme/cypress/integration/skeune/wayf/WayfGeneralBehaviour.js
theme/cypress/integration/skeune/wayf/WayfKeyboardBehaviour.js
theme/cypress/integration/skeune/wayf/WayfMouseBehaviour.js

When clicking on the banner IDP link, the focus should shift to the banner idp.

Preselect the banner IDP when clicking the banner link

---

theme/base/javascripts/wayf/handleEnter.js
theme/base/javascripts/wayf/handleIdpBanner.js
theme/base/javascripts/wayf/idpFocus/arrowDown.js
theme/base/javascripts/wayf/idpFocus/arrowUp.js
theme/base/javascripts/wayf/mouseBehaviour.js
theme/base/stylesheets/pages/wayf.scss
theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/ctas.html.twig
theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/remainingIdps.html.twig
theme/base/templates/modules/Authentication/View/Proxy/consent.html.twig
theme/base/templates/modules/Authentication/View/Proxy/wayf.html.twig
theme/cypress/integration/skeune/wayf/WayfGeneralBehaviour.js
theme/cypress/integration/skeune/wayf/WayfKeyboardBehaviour.js
theme/cypress/integration/skeune/wayf/WayfMouseBehaviour.js
theme/skeune/translations/messages.en.php
theme/skeune/translations/messages.nl.php
theme/skeune/translations/messages.pt.php

Wayf:
- Ensure that the organization noun is used everywhere.
- EduId needs to start with a small letter the banner.
Consent:
- add minimal consent variant

Support minimal consent & fix a few translation bugs

---

theme/base/stylesheets/mixins.scss
theme/base/stylesheets/pages/consent.scss
theme/base/stylesheets/pages/wayf.scss
theme/base/stylesheets/shared.scss
theme/skeune/translations/messages.en.php
theme/skeune/translations/messages.nl.php
theme/skeune/translations/messages.pt.php

replaces #951 which, due to my absence, is now in rebase hell

Ensure focus styles match the styleboard

---

src/OpenConext/EngineBlockFunctionalTestingBundle/Controllers/WayfController.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Resources/config/routing.yml
theme/base/javascripts/wayf/handleEnter.js
theme/base/javascripts/wayf/selectFirstIdPAndSubmitForm.js
theme/base/javascripts/wayf/submitForm.js
theme/cypress/integration/openconext/wayf/WayfMouseBehaviour.spec.js
theme/cypress/integration/skeune/wayf/WayfKeyboardBehaviour.js
theme/cypress/integration/skeune/wayf/WayfMouseBehaviour.js

Select the first visible IdP from the list when the user presses the enter/return button.

Select and Submit topmost IdP on enter

---

theme/base/javascripts/wayf/search/toggleSearchAndResetButton.js
theme/base/javascripts/wayf/searchBehaviour.js
theme/base/stylesheets/pages/wayf.scss
theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/SVG/close.svg
theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/SVG/delete.svg
theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/search.html.twig
theme/cypress/integration/skeune/wayf/WayfGeneralBehaviour.js

It is shown once the user starts typing text into the search bar. When the search term is cleared, the poirot icon is shown again. This toggle is performed using the toggleSearchAndResetButton function. It is also triggered when the user manually clicks the x button.
Todo: Improve styling @Badlapje do you have the energy to look into styling this button? I tried some myself, but it felt like going against the grain.

Add search field reset button

---

theme/base/stylesheets/pages/form.scss
theme/base/templates/modules/Authentication/View/Proxy/Partials/Shared/spinner.html.twig
theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/loadingSpinner.html.twig
theme/base/templates/modules/Authentication/View/Proxy/form.html.twig

The spinner is centered and is now reused from an existing partial.

Center the connecting to the service spinner

---

theme/base/javascripts/wayf/search/toggleSearchAndResetButton.js
theme/base/javascripts/wayf/searchBehaviour.js
theme/base/stylesheets/pages/wayf.scss
theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/preselection.html.twig
theme/cypress/integration/skeune/wayf/wayf.general.spec.js
theme/skeune/translations/messages.nl.php

Addresses several issues described in `https://www.pivotaltracker.com/story/show/175494262`

Address smaller WAYF issues

---

theme/base/javascripts/wayf/handleEnter.js
theme/base/javascripts/wayf/noAccess/attachClickHandlerToForm.js
theme/base/javascripts/wayf/noAccess/validation.js
theme/base/stylesheets/pages/wayf.scss
theme/base/templates/modules/Authentication/View/IdentityProvider/request-access.html.twig
theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/noAccess/requestForm.html.twig
theme/cypress/integration/skeune/wayf/wayf.keyboard.spec.js
theme/cypress/support/commands.js

Adding rudimentary validation to the request access form
~~Tests are not provided to prevent issues with #970~~ 
~~When that PR is merged, tests can be added to this PR.~~ Added them in https://github.com/OpenConext/OpenConext-engineblock/pull/975/commits/ccec1c4019e03861c8d6cc0181847d24e325a2ce

Validate required fields

---

theme/base/javascripts/wayf/utility/sortIdpMethods.js

Add a language/locale parameter so sort uses a localized comparison

Localize the sort

---

theme/base/templates/modules/Authentication/View/Proxy/debug-idp-mail.txt.twig
theme/base/templates/modules/Authentication/View/Proxy/debug-idp-response.html.twig

Two templates were missing, added them.

Add two missing templates

---

theme/base/templates/layouts/scripts/default.html.twig
theme/base/templates/modules/Authentication/View/Index/index.html.twig
theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/Modals/uniqueNumberExplanation.html.twig
theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/disclaimerList.html.twig
theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/idpRow.html.twig
theme/base/templates/modules/Default/Partials/footer.html.twig
theme/base/templates/modules/Default/View/Error/partial/footer.html.twig
theme/postcss.config.js

DONE:
- preload critical fonts
- use the charset meta-tag and make sure it's first
- add noreferrer/noopener to all _blank links
- minify css for better performance
TODO, added to [this ticket ](https://www.pivotaltracker.com/n/projects/1425900/stories/174968005)in pivotal:  
- correct wrong content-types
- add missing content-types
- check cache control headers
- ensure text-based resources are compressed
- add missing x-content-type headers

Implement optimizations found in lighthouse/webhint audits

---

theme/base/stylesheets/pages/consent/idpRow.scss
theme/base/stylesheets/shared.scss

- ensure line-height is 1.5 in the nok-section
- ensure the modal in the idp-row doesn't start to low

Fix various smaller styling feedback issues

---

theme/base/stylesheets/pages/front-page/modules/footer.scss
theme/base/stylesheets/pages/front-page/page.scss

Ensure the links on the index page meet the AA accessibility guidelines.

Ensure links have enough contrast

---

theme/base/templates/layouts/scripts/default.html.twig
theme/base/templates/modules/Authentication/View/Feedback/authorization-policy-violation.html.twig
theme/base/templates/modules/Authentication/View/Index/index.html.twig
theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/idpRow.html.twig
theme/base/templates/modules/Authentication/View/Proxy/Partials/Shared/spinner.html.twig
theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp/idp.html.twig
theme/base/templates/modules/Authentication/View/Proxy/debug-idp-response.html.twig
theme/base/templates/modules/Authentication/View/Proxy/form.html.twig
theme/openconext/templates/layouts/scripts/default.html.twig
theme/openconext/templates/modules/Authentication/View/Proxy/consent.html.twig
theme/openconext/templates/modules/Authentication/View/Proxy/form.html.twig
theme/openconext/templates/modules/Authentication/View/Proxy/wayf.html.twig
theme/openconext/templates/modules/Default/View/Error/partial/legacy_header.html.twig

Maybe marginal gains, but they follow best practices for cache-control and other file header related optimizations.
See individual commits for some more detail.
See: https://www.pivotaltracker.com/story/show/174968005

Performance and compatibility improvements

---

library/EngineBlock/Corto/Filter/Command/ValidateMfaAuthnContextClassRef.php

This so we can know from the logs that a login actually happened with
this context. The log_logins logger also includes the
AuthnContextClassRef but this is not complete as it will not be set
to the right value for legacy ADFS which has it in an attribute.

Add logging to ValidateMfaAuthnContextClassRef command.

---

theme/package-lock.json
theme/package.json

Prior to this change, there were 7 security warnings, of which 1 was high and needed manual review.
This change implements a resolution for the high security threat (manual review) and audit fix + npm upgrade for the others.

Resolve insecure packages to secure version

---

.github/workflows/test-integration.yml
README.md
build.xml
docs/php_testing.md

The test-integration was updated to include a Twig Lint action for the `theme` folder.

Include Twig linting in CI pipeline

---

library/EngineBlock/Application/DiContainer.php
library/EngineBlock/Corto/Module/Service/AssertionConsumer.php
library/EngineBlock/Corto/Module/Service/StepupAssertionConsumer.php
library/EngineBlock/Saml2/AuthnRequestAnnotationDecorator.php
src/OpenConext/EngineBlock/Metadata/LoaRepository.php
src/OpenConext/EngineBlock/Stepup/StepupDecision.php
src/OpenConext/EngineBlock/Stepup/StepupGatewayCallOutHelper.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Context/MockSpContext.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Stepup.feature
tests/library/EngineBlock/Test/Saml2/AuthnRequestAnnotationDecoratorTest.php
tests/unit/OpenConext/EngineBlock/Metadata/LoaRepositoryTest.php
tests/unit/OpenConext/EngineBlock/Stepup/StepupDecisionTest.php

When the AuthnContextClassRefs contain valid LoA(s), then they are to be included in the step up decision process.
https://www.pivotaltracker.com/story/show/176960392

Allow AuthnRequest based stepup requests

---

composer.json
composer.lock

This adds the `system` opcache information to the `/info` endpoint

Upgrade OpenConext Monitor Bundle to 2.1.0

---

docs/trusted_proxy.md

Trusted proxy documentation update

---

theme/base/javascripts/wayf/submitForm.js

Added the call to rememberChoice functionality in subMitForm.js

Make sure rememberChoice is called

---

theme/package-lock.json
theme/package.json

See: https://www.pivotaltracker.com/story/show/185145420

Move Socket IO to the devDependencies

---

languages/messages.nl.php
languages/messages.pt.php
theme/base/templates/modules/Authentication/View/Metadata/partial/organization.xml.twig

fixed variables in metadata md:organisation not translating

fixed variables in metadata md:organisation not translating

---

library/EngineBlock/Corto/Filter/Command/EnforcePolicy.php
src/OpenConext/EngineBlock/Metadata/Logo.php
src/OpenConext/EngineBlock/Metadata/Mdui.php
tests/unit/OpenConext/EngineBlock/Metadata/LogoTest.php

The logo is used unsafely in two placed (EnforcePolicy and Mdui) that was addressed here. And then, the test coverage of the Logo element was quite low. And that was also addressed here.
See: https://www.pivotaltracker.com/story/show/185540656

Improve MDUI Logo usage

---

src/OpenConext/EngineBlockBundle/Controller/MetadataController.php

As per 4.1.1 of the [OASIS SAML Metadata specification](https://docs.oasis-open.org/security/saml/v2.0/saml-metadata-2.0-os.pdf)

Fix metadata content type

---

theme/skeune/translations/messages.en.php
theme/skeune/translations/messages.nl.php
theme/skeune/translations/messages.pt.php

Fix link to moved documentation

---

library/EngineBlock/Application/ErrorHandler.php

There's no inherent guarantee in EB  whatsoever that this error type will be sent to any administrator. Do not let people believe that it will be and wait for it to magically go away if they do nothing.

Do not claim something has been sent to any administator

---

CHANGELOG.md
library/EngineBlock/Corto/Module/Service/AssertionConsumer.php
library/EngineBlock/Corto/ProxyServer.php
src/OpenConext/EngineBlockFunctionalTestingBundle/Features/Stepup.feature

https://github.com/OpenConext/OpenConext-engineblock/issues/1849

Prevent Stepup user attributes filtered by ARP
